
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model autor
 * 
 */
export type autor = Prisma.autorModel
/**
 * Model dodata
 * 
 */
export type dodata = Prisma.dodataModel
/**
 * Model izdavac
 * 
 */
export type izdavac = Prisma.izdavacModel
/**
 * Model knjiga
 * 
 */
export type knjiga = Prisma.knjigaModel
/**
 * Model korisnik
 * 
 */
export type korisnik = Prisma.korisnikModel
/**
 * Model porudzbina
 * 
 */
export type porudzbina = Prisma.porudzbinaModel
/**
 * Model slika_uzorak
 * 
 */
export type slika_uzorak = Prisma.slika_uzorakModel
/**
 * Model zanr
 * 
 */
export type zanr = Prisma.zanrModel
