
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/autor'
export type * from './models/dodata'
export type * from './models/izdavac'
export type * from './models/knjiga'
export type * from './models/korisnik'
export type * from './models/porudzbina'
export type * from './models/slika_uzorak'
export type * from './models/zanr'
export type * from './commonInputTypes'