
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.9.1
 * Query Engine version: e922089b7d7502aff4249d5da3420f6fa55fc6ad
 */
export const prismaVersion: PrismaVersion = {
  client: "7.9.1",
  engine: "e922089b7d7502aff4249d5da3420f6fa55fc6ad"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * Resolved type of the argument passed to the `PrismaClient` constructor.
 *
 * When called without a narrower options type (the common case), this resolves
 * to `PrismaClientOptions` directly, which produces a clear TypeScript error
 * message (`not assignable to parameter of type 'PrismaClientOptions'`) when
 * the argument is missing or incomplete. When the user supplies a narrower
 * options type (e.g. via a literal), it falls back to `Subset` to keep
 * filtering out unknown properties.
 */
export type PrismaClientConstructorArgs<Options extends PrismaClientOptions> =
  [PrismaClientOptions] extends [Options] ? PrismaClientOptions : Subset<Options, PrismaClientOptions>;

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    ((Without<T, U> & U) | (Without<U, T> & T)) & object
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  autor: 'autor',
  dodata: 'dodata',
  izdavac: 'izdavac',
  knjiga: 'knjiga',
  korisnik: 'korisnik',
  porudzbina: 'porudzbina',
  slika_uzorak: 'slika_uzorak',
  zanr: 'zanr'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "autor" | "dodata" | "izdavac" | "knjiga" | "korisnik" | "porudzbina" | "slika_uzorak" | "zanr"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    autor: {
      payload: Prisma.$autorPayload<ExtArgs>
      fields: Prisma.autorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.autorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$autorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.autorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$autorPayload>
        }
        findFirst: {
          args: Prisma.autorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$autorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.autorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$autorPayload>
        }
        findMany: {
          args: Prisma.autorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$autorPayload>[]
        }
        create: {
          args: Prisma.autorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$autorPayload>
        }
        createMany: {
          args: Prisma.autorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.autorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$autorPayload>
        }
        update: {
          args: Prisma.autorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$autorPayload>
        }
        deleteMany: {
          args: Prisma.autorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.autorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.autorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$autorPayload>
        }
        aggregate: {
          args: Prisma.AutorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAutor>
        }
        groupBy: {
          args: Prisma.autorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AutorGroupByOutputType>[]
        }
        count: {
          args: Prisma.autorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AutorCountAggregateOutputType> | number
        }
      }
    }
    dodata: {
      payload: Prisma.$dodataPayload<ExtArgs>
      fields: Prisma.dodataFieldRefs
      operations: {
        findUnique: {
          args: Prisma.dodataFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$dodataPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.dodataFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$dodataPayload>
        }
        findFirst: {
          args: Prisma.dodataFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$dodataPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.dodataFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$dodataPayload>
        }
        findMany: {
          args: Prisma.dodataFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$dodataPayload>[]
        }
        create: {
          args: Prisma.dodataCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$dodataPayload>
        }
        createMany: {
          args: Prisma.dodataCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.dodataDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$dodataPayload>
        }
        update: {
          args: Prisma.dodataUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$dodataPayload>
        }
        deleteMany: {
          args: Prisma.dodataDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.dodataUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.dodataUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$dodataPayload>
        }
        aggregate: {
          args: Prisma.DodataAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDodata>
        }
        groupBy: {
          args: Prisma.dodataGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DodataGroupByOutputType>[]
        }
        count: {
          args: Prisma.dodataCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DodataCountAggregateOutputType> | number
        }
      }
    }
    izdavac: {
      payload: Prisma.$izdavacPayload<ExtArgs>
      fields: Prisma.izdavacFieldRefs
      operations: {
        findUnique: {
          args: Prisma.izdavacFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$izdavacPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.izdavacFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$izdavacPayload>
        }
        findFirst: {
          args: Prisma.izdavacFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$izdavacPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.izdavacFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$izdavacPayload>
        }
        findMany: {
          args: Prisma.izdavacFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$izdavacPayload>[]
        }
        create: {
          args: Prisma.izdavacCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$izdavacPayload>
        }
        createMany: {
          args: Prisma.izdavacCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.izdavacDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$izdavacPayload>
        }
        update: {
          args: Prisma.izdavacUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$izdavacPayload>
        }
        deleteMany: {
          args: Prisma.izdavacDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.izdavacUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.izdavacUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$izdavacPayload>
        }
        aggregate: {
          args: Prisma.IzdavacAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIzdavac>
        }
        groupBy: {
          args: Prisma.izdavacGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IzdavacGroupByOutputType>[]
        }
        count: {
          args: Prisma.izdavacCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IzdavacCountAggregateOutputType> | number
        }
      }
    }
    knjiga: {
      payload: Prisma.$knjigaPayload<ExtArgs>
      fields: Prisma.knjigaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.knjigaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$knjigaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.knjigaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$knjigaPayload>
        }
        findFirst: {
          args: Prisma.knjigaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$knjigaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.knjigaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$knjigaPayload>
        }
        findMany: {
          args: Prisma.knjigaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$knjigaPayload>[]
        }
        create: {
          args: Prisma.knjigaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$knjigaPayload>
        }
        createMany: {
          args: Prisma.knjigaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.knjigaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$knjigaPayload>
        }
        update: {
          args: Prisma.knjigaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$knjigaPayload>
        }
        deleteMany: {
          args: Prisma.knjigaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.knjigaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.knjigaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$knjigaPayload>
        }
        aggregate: {
          args: Prisma.KnjigaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKnjiga>
        }
        groupBy: {
          args: Prisma.knjigaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KnjigaGroupByOutputType>[]
        }
        count: {
          args: Prisma.knjigaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KnjigaCountAggregateOutputType> | number
        }
      }
    }
    korisnik: {
      payload: Prisma.$korisnikPayload<ExtArgs>
      fields: Prisma.korisnikFieldRefs
      operations: {
        findUnique: {
          args: Prisma.korisnikFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$korisnikPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.korisnikFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$korisnikPayload>
        }
        findFirst: {
          args: Prisma.korisnikFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$korisnikPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.korisnikFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$korisnikPayload>
        }
        findMany: {
          args: Prisma.korisnikFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$korisnikPayload>[]
        }
        create: {
          args: Prisma.korisnikCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$korisnikPayload>
        }
        createMany: {
          args: Prisma.korisnikCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.korisnikDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$korisnikPayload>
        }
        update: {
          args: Prisma.korisnikUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$korisnikPayload>
        }
        deleteMany: {
          args: Prisma.korisnikDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.korisnikUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.korisnikUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$korisnikPayload>
        }
        aggregate: {
          args: Prisma.KorisnikAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKorisnik>
        }
        groupBy: {
          args: Prisma.korisnikGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KorisnikGroupByOutputType>[]
        }
        count: {
          args: Prisma.korisnikCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KorisnikCountAggregateOutputType> | number
        }
      }
    }
    porudzbina: {
      payload: Prisma.$porudzbinaPayload<ExtArgs>
      fields: Prisma.porudzbinaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.porudzbinaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$porudzbinaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.porudzbinaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$porudzbinaPayload>
        }
        findFirst: {
          args: Prisma.porudzbinaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$porudzbinaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.porudzbinaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$porudzbinaPayload>
        }
        findMany: {
          args: Prisma.porudzbinaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$porudzbinaPayload>[]
        }
        create: {
          args: Prisma.porudzbinaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$porudzbinaPayload>
        }
        createMany: {
          args: Prisma.porudzbinaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.porudzbinaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$porudzbinaPayload>
        }
        update: {
          args: Prisma.porudzbinaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$porudzbinaPayload>
        }
        deleteMany: {
          args: Prisma.porudzbinaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.porudzbinaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.porudzbinaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$porudzbinaPayload>
        }
        aggregate: {
          args: Prisma.PorudzbinaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePorudzbina>
        }
        groupBy: {
          args: Prisma.porudzbinaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PorudzbinaGroupByOutputType>[]
        }
        count: {
          args: Prisma.porudzbinaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PorudzbinaCountAggregateOutputType> | number
        }
      }
    }
    slika_uzorak: {
      payload: Prisma.$slika_uzorakPayload<ExtArgs>
      fields: Prisma.slika_uzorakFieldRefs
      operations: {
        findUnique: {
          args: Prisma.slika_uzorakFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$slika_uzorakPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.slika_uzorakFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$slika_uzorakPayload>
        }
        findFirst: {
          args: Prisma.slika_uzorakFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$slika_uzorakPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.slika_uzorakFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$slika_uzorakPayload>
        }
        findMany: {
          args: Prisma.slika_uzorakFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$slika_uzorakPayload>[]
        }
        create: {
          args: Prisma.slika_uzorakCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$slika_uzorakPayload>
        }
        createMany: {
          args: Prisma.slika_uzorakCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.slika_uzorakDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$slika_uzorakPayload>
        }
        update: {
          args: Prisma.slika_uzorakUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$slika_uzorakPayload>
        }
        deleteMany: {
          args: Prisma.slika_uzorakDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.slika_uzorakUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.slika_uzorakUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$slika_uzorakPayload>
        }
        aggregate: {
          args: Prisma.Slika_uzorakAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSlika_uzorak>
        }
        groupBy: {
          args: Prisma.slika_uzorakGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Slika_uzorakGroupByOutputType>[]
        }
        count: {
          args: Prisma.slika_uzorakCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Slika_uzorakCountAggregateOutputType> | number
        }
      }
    }
    zanr: {
      payload: Prisma.$zanrPayload<ExtArgs>
      fields: Prisma.zanrFieldRefs
      operations: {
        findUnique: {
          args: Prisma.zanrFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$zanrPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.zanrFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$zanrPayload>
        }
        findFirst: {
          args: Prisma.zanrFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$zanrPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.zanrFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$zanrPayload>
        }
        findMany: {
          args: Prisma.zanrFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$zanrPayload>[]
        }
        create: {
          args: Prisma.zanrCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$zanrPayload>
        }
        createMany: {
          args: Prisma.zanrCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.zanrDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$zanrPayload>
        }
        update: {
          args: Prisma.zanrUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$zanrPayload>
        }
        deleteMany: {
          args: Prisma.zanrDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.zanrUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.zanrUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$zanrPayload>
        }
        aggregate: {
          args: Prisma.ZanrAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateZanr>
        }
        groupBy: {
          args: Prisma.zanrGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ZanrGroupByOutputType>[]
        }
        count: {
          args: Prisma.zanrCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ZanrCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AutorScalarFieldEnum = {
  autor_id: 'autor_id',
  ime_autora: 'ime_autora',
  prezime_autora: 'prezime_autora',
  zemlja_autora: 'zemlja_autora'
} as const

export type AutorScalarFieldEnum = (typeof AutorScalarFieldEnum)[keyof typeof AutorScalarFieldEnum]


export const DodataScalarFieldEnum = {
  isbn: 'isbn',
  broj_racuna: 'broj_racuna',
  kolicina: 'kolicina'
} as const

export type DodataScalarFieldEnum = (typeof DodataScalarFieldEnum)[keyof typeof DodataScalarFieldEnum]


export const IzdavacScalarFieldEnum = {
  izdavac_id: 'izdavac_id',
  naziv_izdavaca: 'naziv_izdavaca',
  grad: 'grad'
} as const

export type IzdavacScalarFieldEnum = (typeof IzdavacScalarFieldEnum)[keyof typeof IzdavacScalarFieldEnum]


export const KnjigaScalarFieldEnum = {
  isbn: 'isbn',
  naslov: 'naslov',
  naslov_originala: 'naslov_originala',
  godina_izdavanja_originala: 'godina_izdavanja_originala',
  godina_izdavanja: 'godina_izdavanja',
  cena: 'cena',
  povez: 'povez',
  pismo: 'pismo',
  slika_korice: 'slika_korice',
  broj_strana: 'broj_strana',
  opis: 'opis',
  autor_id: 'autor_id',
  zanr_id: 'zanr_id',
  izdavac_id: 'izdavac_id'
} as const

export type KnjigaScalarFieldEnum = (typeof KnjigaScalarFieldEnum)[keyof typeof KnjigaScalarFieldEnum]


export const KorisnikScalarFieldEnum = {
  korisnik_id: 'korisnik_id',
  korisnicko_ime: 'korisnicko_ime',
  email: 'email',
  lozinka: 'lozinka',
  uloga: 'uloga'
} as const

export type KorisnikScalarFieldEnum = (typeof KorisnikScalarFieldEnum)[keyof typeof KorisnikScalarFieldEnum]


export const PorudzbinaScalarFieldEnum = {
  broj_racuna: 'broj_racuna',
  datum: 'datum',
  iznos: 'iznos',
  korisnik_id: 'korisnik_id'
} as const

export type PorudzbinaScalarFieldEnum = (typeof PorudzbinaScalarFieldEnum)[keyof typeof PorudzbinaScalarFieldEnum]


export const Slika_uzorakScalarFieldEnum = {
  slika_id: 'slika_id',
  naziv_slike: 'naziv_slike',
  link_slike: 'link_slike',
  isbn: 'isbn'
} as const

export type Slika_uzorakScalarFieldEnum = (typeof Slika_uzorakScalarFieldEnum)[keyof typeof Slika_uzorakScalarFieldEnum]


export const ZanrScalarFieldEnum = {
  zanr_id: 'zanr_id',
  naziv_zanra: 'naziv_zanra'
} as const

export type ZanrScalarFieldEnum = (typeof ZanrScalarFieldEnum)[keyof typeof ZanrScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const autorOrderByRelevanceFieldEnum = {
  ime_autora: 'ime_autora',
  prezime_autora: 'prezime_autora',
  zemlja_autora: 'zemlja_autora'
} as const

export type autorOrderByRelevanceFieldEnum = (typeof autorOrderByRelevanceFieldEnum)[keyof typeof autorOrderByRelevanceFieldEnum]


export const dodataOrderByRelevanceFieldEnum = {
  isbn: 'isbn'
} as const

export type dodataOrderByRelevanceFieldEnum = (typeof dodataOrderByRelevanceFieldEnum)[keyof typeof dodataOrderByRelevanceFieldEnum]


export const izdavacOrderByRelevanceFieldEnum = {
  naziv_izdavaca: 'naziv_izdavaca',
  grad: 'grad'
} as const

export type izdavacOrderByRelevanceFieldEnum = (typeof izdavacOrderByRelevanceFieldEnum)[keyof typeof izdavacOrderByRelevanceFieldEnum]


export const knjigaOrderByRelevanceFieldEnum = {
  isbn: 'isbn',
  naslov: 'naslov',
  naslov_originala: 'naslov_originala',
  povez: 'povez',
  pismo: 'pismo',
  slika_korice: 'slika_korice',
  opis: 'opis'
} as const

export type knjigaOrderByRelevanceFieldEnum = (typeof knjigaOrderByRelevanceFieldEnum)[keyof typeof knjigaOrderByRelevanceFieldEnum]


export const korisnikOrderByRelevanceFieldEnum = {
  korisnicko_ime: 'korisnicko_ime',
  email: 'email',
  lozinka: 'lozinka'
} as const

export type korisnikOrderByRelevanceFieldEnum = (typeof korisnikOrderByRelevanceFieldEnum)[keyof typeof korisnikOrderByRelevanceFieldEnum]


export const slika_uzorakOrderByRelevanceFieldEnum = {
  naziv_slike: 'naziv_slike',
  link_slike: 'link_slike',
  isbn: 'isbn'
} as const

export type slika_uzorakOrderByRelevanceFieldEnum = (typeof slika_uzorakOrderByRelevanceFieldEnum)[keyof typeof slika_uzorakOrderByRelevanceFieldEnum]


export const zanrOrderByRelevanceFieldEnum = {
  naziv_zanra: 'naziv_zanra'
} as const

export type zanrOrderByRelevanceFieldEnum = (typeof zanrOrderByRelevanceFieldEnum)[keyof typeof zanrOrderByRelevanceFieldEnum]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'korisnik_uloga'
 */
export type Enumkorisnik_ulogaFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'korisnik_uloga'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
/**
 * Options common to all variants of `PrismaClientOptions`, regardless of whether you connect to your database through a driver adapter or through Prisma Accelerate.
 */
export interface PrismaClientBaseOptions {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}

/**
 * `PrismaClient` options for connecting to your database through Prisma Accelerate instead of a driver adapter.
 * 
 * Learn more: https://pris.ly/d/accelerate
 */
export interface PrismaClientOptionsWithAccelerateUrl extends PrismaClientBaseOptions {
  /**
   * The Prisma Accelerate connection URL. Use this option to connect to your database through Prisma Accelerate instead of using a driver adapter to connect directly.
   * 
   * Learn more: https://pris.ly/d/accelerate
   */
  accelerateUrl: string
  adapter?: never
}

/**
 * `PrismaClient` options for connecting to your database through a driver adapter. This is the common case in Prisma 7.
 * 
 * Learn more: https://pris.ly/d/driver-adapters
 */
export interface PrismaClientOptionsWithAdapter extends PrismaClientBaseOptions {
  /**
   * A driver adapter that PrismaClient uses to connect to your database, such as the ones provided by `@prisma/adapter-pg`, `@prisma/adapter-libsql`, `@prisma/adapter-planetscale`, etc.
   * 
   * A driver adapter is **required** unless you connect to your database through Prisma Accelerate (in which case use `accelerateUrl` instead).
   * 
   * Learn more: https://pris.ly/d/driver-adapters
   * 
   * @example
   * ```ts
   * import { PrismaPg } from '@prisma/adapter-pg'
   * import { PrismaClient } from './generated/prisma/client'
   * 
   * const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
   * const prisma = new PrismaClient({ adapter })
   * ```
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
}

/**
 * Options passed to the `PrismaClient` constructor.
 * 
 * A driver adapter (or, alternatively, a Prisma Accelerate URL) is **required**. See {@link PrismaClientOptionsWithAdapter} and {@link PrismaClientOptionsWithAccelerateUrl} for the two variants. All other properties live in {@link PrismaClientBaseOptions} and are optional.
 * 
 * Learn more about driver adapters: https://pris.ly/d/driver-adapters
 */
export type PrismaClientOptions = PrismaClientOptionsWithAccelerateUrl | PrismaClientOptionsWithAdapter
export type GlobalOmitConfig = {
  autor?: Prisma.autorOmit
  dodata?: Prisma.dodataOmit
  izdavac?: Prisma.izdavacOmit
  knjiga?: Prisma.knjigaOmit
  korisnik?: Prisma.korisnikOmit
  porudzbina?: Prisma.porudzbinaOmit
  slika_uzorak?: Prisma.slika_uzorakOmit
  zanr?: Prisma.zanrOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

