
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  autor: 'autor',
  dodata: 'dodata',
  izdavac: 'izdavac',
  knjiga: 'knjiga',
  korisnik: 'korisnik',
  porudzbina: 'porudzbina',
  slika_uzorak: 'slika_uzorak',
  zanr: 'zanr'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AutorScalarFieldEnum = {
  autor_id: 'autor_id',
  ime_autora: 'ime_autora',
  prezime_autora: 'prezime_autora',
  zemlja_autora: 'zemlja_autora'
} as const

export type AutorScalarFieldEnum = (typeof AutorScalarFieldEnum)[keyof typeof AutorScalarFieldEnum]


export const DodataScalarFieldEnum = {
  isbn: 'isbn',
  broj_racuna: 'broj_racuna',
  kolicina: 'kolicina'
} as const

export type DodataScalarFieldEnum = (typeof DodataScalarFieldEnum)[keyof typeof DodataScalarFieldEnum]


export const IzdavacScalarFieldEnum = {
  izdavac_id: 'izdavac_id',
  naziv_izdavaca: 'naziv_izdavaca',
  grad: 'grad'
} as const

export type IzdavacScalarFieldEnum = (typeof IzdavacScalarFieldEnum)[keyof typeof IzdavacScalarFieldEnum]


export const KnjigaScalarFieldEnum = {
  isbn: 'isbn',
  naslov: 'naslov',
  naslov_originala: 'naslov_originala',
  godina_izdavanja_originala: 'godina_izdavanja_originala',
  godina_izdavanja: 'godina_izdavanja',
  cena: 'cena',
  povez: 'povez',
  pismo: 'pismo',
  slika_korice: 'slika_korice',
  broj_strana: 'broj_strana',
  opis: 'opis',
  autor_id: 'autor_id',
  zanr_id: 'zanr_id',
  izdavac_id: 'izdavac_id'
} as const

export type KnjigaScalarFieldEnum = (typeof KnjigaScalarFieldEnum)[keyof typeof KnjigaScalarFieldEnum]


export const KorisnikScalarFieldEnum = {
  korisnik_id: 'korisnik_id',
  korisnicko_ime: 'korisnicko_ime',
  email: 'email',
  lozinka: 'lozinka',
  uloga: 'uloga'
} as const

export type KorisnikScalarFieldEnum = (typeof KorisnikScalarFieldEnum)[keyof typeof KorisnikScalarFieldEnum]


export const PorudzbinaScalarFieldEnum = {
  broj_racuna: 'broj_racuna',
  datum: 'datum',
  iznos: 'iznos',
  korisnik_id: 'korisnik_id'
} as const

export type PorudzbinaScalarFieldEnum = (typeof PorudzbinaScalarFieldEnum)[keyof typeof PorudzbinaScalarFieldEnum]


export const Slika_uzorakScalarFieldEnum = {
  slika_id: 'slika_id',
  naziv_slike: 'naziv_slike',
  link_slike: 'link_slike',
  isbn: 'isbn'
} as const

export type Slika_uzorakScalarFieldEnum = (typeof Slika_uzorakScalarFieldEnum)[keyof typeof Slika_uzorakScalarFieldEnum]


export const ZanrScalarFieldEnum = {
  zanr_id: 'zanr_id',
  naziv_zanra: 'naziv_zanra'
} as const

export type ZanrScalarFieldEnum = (typeof ZanrScalarFieldEnum)[keyof typeof ZanrScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const autorOrderByRelevanceFieldEnum = {
  ime_autora: 'ime_autora',
  prezime_autora: 'prezime_autora',
  zemlja_autora: 'zemlja_autora'
} as const

export type autorOrderByRelevanceFieldEnum = (typeof autorOrderByRelevanceFieldEnum)[keyof typeof autorOrderByRelevanceFieldEnum]


export const dodataOrderByRelevanceFieldEnum = {
  isbn: 'isbn'
} as const

export type dodataOrderByRelevanceFieldEnum = (typeof dodataOrderByRelevanceFieldEnum)[keyof typeof dodataOrderByRelevanceFieldEnum]


export const izdavacOrderByRelevanceFieldEnum = {
  naziv_izdavaca: 'naziv_izdavaca',
  grad: 'grad'
} as const

export type izdavacOrderByRelevanceFieldEnum = (typeof izdavacOrderByRelevanceFieldEnum)[keyof typeof izdavacOrderByRelevanceFieldEnum]


export const knjigaOrderByRelevanceFieldEnum = {
  isbn: 'isbn',
  naslov: 'naslov',
  naslov_originala: 'naslov_originala',
  povez: 'povez',
  pismo: 'pismo',
  slika_korice: 'slika_korice',
  opis: 'opis'
} as const

export type knjigaOrderByRelevanceFieldEnum = (typeof knjigaOrderByRelevanceFieldEnum)[keyof typeof knjigaOrderByRelevanceFieldEnum]


export const korisnikOrderByRelevanceFieldEnum = {
  korisnicko_ime: 'korisnicko_ime',
  email: 'email',
  lozinka: 'lozinka'
} as const

export type korisnikOrderByRelevanceFieldEnum = (typeof korisnikOrderByRelevanceFieldEnum)[keyof typeof korisnikOrderByRelevanceFieldEnum]


export const slika_uzorakOrderByRelevanceFieldEnum = {
  naziv_slike: 'naziv_slike',
  link_slike: 'link_slike',
  isbn: 'isbn'
} as const

export type slika_uzorakOrderByRelevanceFieldEnum = (typeof slika_uzorakOrderByRelevanceFieldEnum)[keyof typeof slika_uzorakOrderByRelevanceFieldEnum]


export const zanrOrderByRelevanceFieldEnum = {
  naziv_zanra: 'naziv_zanra'
} as const

export type zanrOrderByRelevanceFieldEnum = (typeof zanrOrderByRelevanceFieldEnum)[keyof typeof zanrOrderByRelevanceFieldEnum]

