
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `autor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model autor
 * 
 */
export type autorModel = runtime.Types.Result.DefaultSelection<Prisma.$autorPayload>

export type AggregateAutor = {
  _count: AutorCountAggregateOutputType | null
  _avg: AutorAvgAggregateOutputType | null
  _sum: AutorSumAggregateOutputType | null
  _min: AutorMinAggregateOutputType | null
  _max: AutorMaxAggregateOutputType | null
}

export type AutorAvgAggregateOutputType = {
  autor_id: number | null
}

export type AutorSumAggregateOutputType = {
  autor_id: number | null
}

export type AutorMinAggregateOutputType = {
  autor_id: number | null
  ime_autora: string | null
  prezime_autora: string | null
  zemlja_autora: string | null
}

export type AutorMaxAggregateOutputType = {
  autor_id: number | null
  ime_autora: string | null
  prezime_autora: string | null
  zemlja_autora: string | null
}

export type AutorCountAggregateOutputType = {
  autor_id: number
  ime_autora: number
  prezime_autora: number
  zemlja_autora: number
  _all: number
}


export type AutorAvgAggregateInputType = {
  autor_id?: true
}

export type AutorSumAggregateInputType = {
  autor_id?: true
}

export type AutorMinAggregateInputType = {
  autor_id?: true
  ime_autora?: true
  prezime_autora?: true
  zemlja_autora?: true
}

export type AutorMaxAggregateInputType = {
  autor_id?: true
  ime_autora?: true
  prezime_autora?: true
  zemlja_autora?: true
}

export type AutorCountAggregateInputType = {
  autor_id?: true
  ime_autora?: true
  prezime_autora?: true
  zemlja_autora?: true
  _all?: true
}

export type AutorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which autor to aggregate.
   */
  where?: Prisma.autorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of autors to fetch.
   */
  orderBy?: Prisma.autorOrderByWithRelationInput | Prisma.autorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.autorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` autors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` autors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned autors
  **/
  _count?: true | AutorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AutorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AutorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AutorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AutorMaxAggregateInputType
}

export type GetAutorAggregateType<T extends AutorAggregateArgs> = {
      [P in keyof T & keyof AggregateAutor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAutor[P]>
    : Prisma.GetScalarType<T[P], AggregateAutor[P]>
}




export type autorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.autorWhereInput
  orderBy?: Prisma.autorOrderByWithAggregationInput | Prisma.autorOrderByWithAggregationInput[]
  by: Prisma.AutorScalarFieldEnum[] | Prisma.AutorScalarFieldEnum
  having?: Prisma.autorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AutorCountAggregateInputType | true
  _avg?: AutorAvgAggregateInputType
  _sum?: AutorSumAggregateInputType
  _min?: AutorMinAggregateInputType
  _max?: AutorMaxAggregateInputType
}

export type AutorGroupByOutputType = {
  autor_id: number
  ime_autora: string
  prezime_autora: string | null
  zemlja_autora: string | null
  _count: AutorCountAggregateOutputType | null
  _avg: AutorAvgAggregateOutputType | null
  _sum: AutorSumAggregateOutputType | null
  _min: AutorMinAggregateOutputType | null
  _max: AutorMaxAggregateOutputType | null
}

export type GetAutorGroupByPayload<T extends autorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AutorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AutorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AutorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AutorGroupByOutputType[P]>
      }
    >
  >



export type autorWhereInput = {
  AND?: Prisma.autorWhereInput | Prisma.autorWhereInput[]
  OR?: Prisma.autorWhereInput[]
  NOT?: Prisma.autorWhereInput | Prisma.autorWhereInput[]
  autor_id?: Prisma.IntFilter<"autor"> | number
  ime_autora?: Prisma.StringFilter<"autor"> | string
  prezime_autora?: Prisma.StringNullableFilter<"autor"> | string | null
  zemlja_autora?: Prisma.StringNullableFilter<"autor"> | string | null
  knjiga?: Prisma.KnjigaListRelationFilter
}

export type autorOrderByWithRelationInput = {
  autor_id?: Prisma.SortOrder
  ime_autora?: Prisma.SortOrder
  prezime_autora?: Prisma.SortOrderInput | Prisma.SortOrder
  zemlja_autora?: Prisma.SortOrderInput | Prisma.SortOrder
  knjiga?: Prisma.knjigaOrderByRelationAggregateInput
  _relevance?: Prisma.autorOrderByRelevanceInput
}

export type autorWhereUniqueInput = Prisma.AtLeast<{
  autor_id?: number
  AND?: Prisma.autorWhereInput | Prisma.autorWhereInput[]
  OR?: Prisma.autorWhereInput[]
  NOT?: Prisma.autorWhereInput | Prisma.autorWhereInput[]
  ime_autora?: Prisma.StringFilter<"autor"> | string
  prezime_autora?: Prisma.StringNullableFilter<"autor"> | string | null
  zemlja_autora?: Prisma.StringNullableFilter<"autor"> | string | null
  knjiga?: Prisma.KnjigaListRelationFilter
}, "autor_id">

export type autorOrderByWithAggregationInput = {
  autor_id?: Prisma.SortOrder
  ime_autora?: Prisma.SortOrder
  prezime_autora?: Prisma.SortOrderInput | Prisma.SortOrder
  zemlja_autora?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.autorCountOrderByAggregateInput
  _avg?: Prisma.autorAvgOrderByAggregateInput
  _max?: Prisma.autorMaxOrderByAggregateInput
  _min?: Prisma.autorMinOrderByAggregateInput
  _sum?: Prisma.autorSumOrderByAggregateInput
}

export type autorScalarWhereWithAggregatesInput = {
  AND?: Prisma.autorScalarWhereWithAggregatesInput | Prisma.autorScalarWhereWithAggregatesInput[]
  OR?: Prisma.autorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.autorScalarWhereWithAggregatesInput | Prisma.autorScalarWhereWithAggregatesInput[]
  autor_id?: Prisma.IntWithAggregatesFilter<"autor"> | number
  ime_autora?: Prisma.StringWithAggregatesFilter<"autor"> | string
  prezime_autora?: Prisma.StringNullableWithAggregatesFilter<"autor"> | string | null
  zemlja_autora?: Prisma.StringNullableWithAggregatesFilter<"autor"> | string | null
}

export type autorCreateInput = {
  ime_autora: string
  prezime_autora?: string | null
  zemlja_autora?: string | null
  knjiga?: Prisma.knjigaCreateNestedManyWithoutAutorInput
}

export type autorUncheckedCreateInput = {
  autor_id?: number
  ime_autora: string
  prezime_autora?: string | null
  zemlja_autora?: string | null
  knjiga?: Prisma.knjigaUncheckedCreateNestedManyWithoutAutorInput
}

export type autorUpdateInput = {
  ime_autora?: Prisma.StringFieldUpdateOperationsInput | string
  prezime_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zemlja_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  knjiga?: Prisma.knjigaUpdateManyWithoutAutorNestedInput
}

export type autorUncheckedUpdateInput = {
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  ime_autora?: Prisma.StringFieldUpdateOperationsInput | string
  prezime_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zemlja_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  knjiga?: Prisma.knjigaUncheckedUpdateManyWithoutAutorNestedInput
}

export type autorCreateManyInput = {
  autor_id?: number
  ime_autora: string
  prezime_autora?: string | null
  zemlja_autora?: string | null
}

export type autorUpdateManyMutationInput = {
  ime_autora?: Prisma.StringFieldUpdateOperationsInput | string
  prezime_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zemlja_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type autorUncheckedUpdateManyInput = {
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  ime_autora?: Prisma.StringFieldUpdateOperationsInput | string
  prezime_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zemlja_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type autorOrderByRelevanceInput = {
  fields: Prisma.autorOrderByRelevanceFieldEnum | Prisma.autorOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type autorCountOrderByAggregateInput = {
  autor_id?: Prisma.SortOrder
  ime_autora?: Prisma.SortOrder
  prezime_autora?: Prisma.SortOrder
  zemlja_autora?: Prisma.SortOrder
}

export type autorAvgOrderByAggregateInput = {
  autor_id?: Prisma.SortOrder
}

export type autorMaxOrderByAggregateInput = {
  autor_id?: Prisma.SortOrder
  ime_autora?: Prisma.SortOrder
  prezime_autora?: Prisma.SortOrder
  zemlja_autora?: Prisma.SortOrder
}

export type autorMinOrderByAggregateInput = {
  autor_id?: Prisma.SortOrder
  ime_autora?: Prisma.SortOrder
  prezime_autora?: Prisma.SortOrder
  zemlja_autora?: Prisma.SortOrder
}

export type autorSumOrderByAggregateInput = {
  autor_id?: Prisma.SortOrder
}

export type AutorScalarRelationFilter = {
  is?: Prisma.autorWhereInput
  isNot?: Prisma.autorWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type autorCreateNestedOneWithoutKnjigaInput = {
  create?: Prisma.XOR<Prisma.autorCreateWithoutKnjigaInput, Prisma.autorUncheckedCreateWithoutKnjigaInput>
  connectOrCreate?: Prisma.autorCreateOrConnectWithoutKnjigaInput
  connect?: Prisma.autorWhereUniqueInput
}

export type autorUpdateOneRequiredWithoutKnjigaNestedInput = {
  create?: Prisma.XOR<Prisma.autorCreateWithoutKnjigaInput, Prisma.autorUncheckedCreateWithoutKnjigaInput>
  connectOrCreate?: Prisma.autorCreateOrConnectWithoutKnjigaInput
  upsert?: Prisma.autorUpsertWithoutKnjigaInput
  connect?: Prisma.autorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.autorUpdateToOneWithWhereWithoutKnjigaInput, Prisma.autorUpdateWithoutKnjigaInput>, Prisma.autorUncheckedUpdateWithoutKnjigaInput>
}

export type autorCreateWithoutKnjigaInput = {
  ime_autora: string
  prezime_autora?: string | null
  zemlja_autora?: string | null
}

export type autorUncheckedCreateWithoutKnjigaInput = {
  autor_id?: number
  ime_autora: string
  prezime_autora?: string | null
  zemlja_autora?: string | null
}

export type autorCreateOrConnectWithoutKnjigaInput = {
  where: Prisma.autorWhereUniqueInput
  create: Prisma.XOR<Prisma.autorCreateWithoutKnjigaInput, Prisma.autorUncheckedCreateWithoutKnjigaInput>
}

export type autorUpsertWithoutKnjigaInput = {
  update: Prisma.XOR<Prisma.autorUpdateWithoutKnjigaInput, Prisma.autorUncheckedUpdateWithoutKnjigaInput>
  create: Prisma.XOR<Prisma.autorCreateWithoutKnjigaInput, Prisma.autorUncheckedCreateWithoutKnjigaInput>
  where?: Prisma.autorWhereInput
}

export type autorUpdateToOneWithWhereWithoutKnjigaInput = {
  where?: Prisma.autorWhereInput
  data: Prisma.XOR<Prisma.autorUpdateWithoutKnjigaInput, Prisma.autorUncheckedUpdateWithoutKnjigaInput>
}

export type autorUpdateWithoutKnjigaInput = {
  ime_autora?: Prisma.StringFieldUpdateOperationsInput | string
  prezime_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zemlja_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type autorUncheckedUpdateWithoutKnjigaInput = {
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  ime_autora?: Prisma.StringFieldUpdateOperationsInput | string
  prezime_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zemlja_autora?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type AutorCountOutputType
 */

export type AutorCountOutputType = {
  knjiga: number
}

export type AutorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  knjiga?: boolean | AutorCountOutputTypeCountKnjigaArgs
}

/**
 * AutorCountOutputType without action
 */
export type AutorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutorCountOutputType
   */
  select?: Prisma.AutorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AutorCountOutputType without action
 */
export type AutorCountOutputTypeCountKnjigaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.knjigaWhereInput
}


export type autorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  autor_id?: boolean
  ime_autora?: boolean
  prezime_autora?: boolean
  zemlja_autora?: boolean
  knjiga?: boolean | Prisma.autor$knjigaArgs<ExtArgs>
  _count?: boolean | Prisma.AutorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["autor"]>



export type autorSelectScalar = {
  autor_id?: boolean
  ime_autora?: boolean
  prezime_autora?: boolean
  zemlja_autora?: boolean
}

export type autorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"autor_id" | "ime_autora" | "prezime_autora" | "zemlja_autora", ExtArgs["result"]["autor"]>
export type autorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  knjiga?: boolean | Prisma.autor$knjigaArgs<ExtArgs>
  _count?: boolean | Prisma.AutorCountOutputTypeDefaultArgs<ExtArgs>
}

export type $autorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "autor"
  objects: {
    knjiga: Prisma.$knjigaPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    autor_id: number
    ime_autora: string
    prezime_autora: string | null
    zemlja_autora: string | null
  }, ExtArgs["result"]["autor"]>
  composites: {}
}

export type autorGetPayload<S extends boolean | null | undefined | autorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$autorPayload, S>

export type autorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<autorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AutorCountAggregateInputType | true
  }

export interface autorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['autor'], meta: { name: 'autor' } }
  /**
   * Find zero or one Autor that matches the filter.
   * @param {autorFindUniqueArgs} args - Arguments to find a Autor
   * @example
   * // Get one Autor
   * const autor = await prisma.autor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends autorFindUniqueArgs>(args: Prisma.SelectSubset<T, autorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__autorClient<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Autor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {autorFindUniqueOrThrowArgs} args - Arguments to find a Autor
   * @example
   * // Get one Autor
   * const autor = await prisma.autor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends autorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, autorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__autorClient<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Autor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {autorFindFirstArgs} args - Arguments to find a Autor
   * @example
   * // Get one Autor
   * const autor = await prisma.autor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends autorFindFirstArgs>(args?: Prisma.SelectSubset<T, autorFindFirstArgs<ExtArgs>>): Prisma.Prisma__autorClient<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Autor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {autorFindFirstOrThrowArgs} args - Arguments to find a Autor
   * @example
   * // Get one Autor
   * const autor = await prisma.autor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends autorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, autorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__autorClient<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Autors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {autorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Autors
   * const autors = await prisma.autor.findMany()
   * 
   * // Get first 10 Autors
   * const autors = await prisma.autor.findMany({ take: 10 })
   * 
   * // Only select the `autor_id`
   * const autorWithAutor_idOnly = await prisma.autor.findMany({ select: { autor_id: true } })
   * 
   */
  findMany<T extends autorFindManyArgs>(args?: Prisma.SelectSubset<T, autorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Autor.
   * @param {autorCreateArgs} args - Arguments to create a Autor.
   * @example
   * // Create one Autor
   * const Autor = await prisma.autor.create({
   *   data: {
   *     // ... data to create a Autor
   *   }
   * })
   * 
   */
  create<T extends autorCreateArgs>(args: Prisma.SelectSubset<T, autorCreateArgs<ExtArgs>>): Prisma.Prisma__autorClient<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Autors.
   * @param {autorCreateManyArgs} args - Arguments to create many Autors.
   * @example
   * // Create many Autors
   * const autor = await prisma.autor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends autorCreateManyArgs>(args?: Prisma.SelectSubset<T, autorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Autor.
   * @param {autorDeleteArgs} args - Arguments to delete one Autor.
   * @example
   * // Delete one Autor
   * const Autor = await prisma.autor.delete({
   *   where: {
   *     // ... filter to delete one Autor
   *   }
   * })
   * 
   */
  delete<T extends autorDeleteArgs>(args: Prisma.SelectSubset<T, autorDeleteArgs<ExtArgs>>): Prisma.Prisma__autorClient<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Autor.
   * @param {autorUpdateArgs} args - Arguments to update one Autor.
   * @example
   * // Update one Autor
   * const autor = await prisma.autor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends autorUpdateArgs>(args: Prisma.SelectSubset<T, autorUpdateArgs<ExtArgs>>): Prisma.Prisma__autorClient<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Autors.
   * @param {autorDeleteManyArgs} args - Arguments to filter Autors to delete.
   * @example
   * // Delete a few Autors
   * const { count } = await prisma.autor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends autorDeleteManyArgs>(args?: Prisma.SelectSubset<T, autorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Autors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {autorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Autors
   * const autor = await prisma.autor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends autorUpdateManyArgs>(args: Prisma.SelectSubset<T, autorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Autor.
   * @param {autorUpsertArgs} args - Arguments to update or create a Autor.
   * @example
   * // Update or create a Autor
   * const autor = await prisma.autor.upsert({
   *   create: {
   *     // ... data to create a Autor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Autor we want to update
   *   }
   * })
   */
  upsert<T extends autorUpsertArgs>(args: Prisma.SelectSubset<T, autorUpsertArgs<ExtArgs>>): Prisma.Prisma__autorClient<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Autors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {autorCountArgs} args - Arguments to filter Autors to count.
   * @example
   * // Count the number of Autors
   * const count = await prisma.autor.count({
   *   where: {
   *     // ... the filter for the Autors we want to count
   *   }
   * })
  **/
  count<T extends autorCountArgs>(
    args?: Prisma.Subset<T, autorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AutorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Autor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AutorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AutorAggregateArgs>(args: Prisma.Subset<T, AutorAggregateArgs>): Prisma.PrismaPromise<GetAutorAggregateType<T>>

  /**
   * Group by Autor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {autorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends autorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: autorGroupByArgs['orderBy'] }
      : { orderBy?: autorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, autorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAutorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the autor model
 */
readonly fields: autorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for autor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__autorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  knjiga<T extends Prisma.autor$knjigaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.autor$knjigaArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the autor model
 */
export interface autorFieldRefs {
  readonly autor_id: Prisma.FieldRef<"autor", 'Int'>
  readonly ime_autora: Prisma.FieldRef<"autor", 'String'>
  readonly prezime_autora: Prisma.FieldRef<"autor", 'String'>
  readonly zemlja_autora: Prisma.FieldRef<"autor", 'String'>
}
    

// Custom InputTypes
/**
 * autor findUnique
 */
export type autorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
  /**
   * Filter, which autor to fetch.
   */
  where: Prisma.autorWhereUniqueInput
}

/**
 * autor findUniqueOrThrow
 */
export type autorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
  /**
   * Filter, which autor to fetch.
   */
  where: Prisma.autorWhereUniqueInput
}

/**
 * autor findFirst
 */
export type autorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
  /**
   * Filter, which autor to fetch.
   */
  where?: Prisma.autorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of autors to fetch.
   */
  orderBy?: Prisma.autorOrderByWithRelationInput | Prisma.autorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for autors.
   */
  cursor?: Prisma.autorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` autors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` autors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of autors.
   */
  distinct?: Prisma.AutorScalarFieldEnum | Prisma.AutorScalarFieldEnum[]
}

/**
 * autor findFirstOrThrow
 */
export type autorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
  /**
   * Filter, which autor to fetch.
   */
  where?: Prisma.autorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of autors to fetch.
   */
  orderBy?: Prisma.autorOrderByWithRelationInput | Prisma.autorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for autors.
   */
  cursor?: Prisma.autorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` autors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` autors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of autors.
   */
  distinct?: Prisma.AutorScalarFieldEnum | Prisma.AutorScalarFieldEnum[]
}

/**
 * autor findMany
 */
export type autorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
  /**
   * Filter, which autors to fetch.
   */
  where?: Prisma.autorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of autors to fetch.
   */
  orderBy?: Prisma.autorOrderByWithRelationInput | Prisma.autorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing autors.
   */
  cursor?: Prisma.autorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` autors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` autors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of autors.
   */
  distinct?: Prisma.AutorScalarFieldEnum | Prisma.AutorScalarFieldEnum[]
}

/**
 * autor create
 */
export type autorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
  /**
   * The data needed to create a autor.
   */
  data: Prisma.XOR<Prisma.autorCreateInput, Prisma.autorUncheckedCreateInput>
}

/**
 * autor createMany
 */
export type autorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many autors.
   */
  data: Prisma.autorCreateManyInput | Prisma.autorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * autor update
 */
export type autorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
  /**
   * The data needed to update a autor.
   */
  data: Prisma.XOR<Prisma.autorUpdateInput, Prisma.autorUncheckedUpdateInput>
  /**
   * Choose, which autor to update.
   */
  where: Prisma.autorWhereUniqueInput
}

/**
 * autor updateMany
 */
export type autorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update autors.
   */
  data: Prisma.XOR<Prisma.autorUpdateManyMutationInput, Prisma.autorUncheckedUpdateManyInput>
  /**
   * Filter which autors to update
   */
  where?: Prisma.autorWhereInput
  /**
   * Limit how many autors to update.
   */
  limit?: number
}

/**
 * autor upsert
 */
export type autorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
  /**
   * The filter to search for the autor to update in case it exists.
   */
  where: Prisma.autorWhereUniqueInput
  /**
   * In case the autor found by the `where` argument doesn't exist, create a new autor with this data.
   */
  create: Prisma.XOR<Prisma.autorCreateInput, Prisma.autorUncheckedCreateInput>
  /**
   * In case the autor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.autorUpdateInput, Prisma.autorUncheckedUpdateInput>
}

/**
 * autor delete
 */
export type autorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
  /**
   * Filter which autor to delete.
   */
  where: Prisma.autorWhereUniqueInput
}

/**
 * autor deleteMany
 */
export type autorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which autors to delete
   */
  where?: Prisma.autorWhereInput
  /**
   * Limit how many autors to delete.
   */
  limit?: number
}

/**
 * autor.knjiga
 */
export type autor$knjigaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  where?: Prisma.knjigaWhereInput
  orderBy?: Prisma.knjigaOrderByWithRelationInput | Prisma.knjigaOrderByWithRelationInput[]
  cursor?: Prisma.knjigaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KnjigaScalarFieldEnum | Prisma.KnjigaScalarFieldEnum[]
}

/**
 * autor without action
 */
export type autorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the autor
   */
  select?: Prisma.autorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the autor
   */
  omit?: Prisma.autorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.autorInclude<ExtArgs> | null
}
