
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dodata` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dodata
 * 
 */
export type dodataModel = runtime.Types.Result.DefaultSelection<Prisma.$dodataPayload>

export type AggregateDodata = {
  _count: DodataCountAggregateOutputType | null
  _avg: DodataAvgAggregateOutputType | null
  _sum: DodataSumAggregateOutputType | null
  _min: DodataMinAggregateOutputType | null
  _max: DodataMaxAggregateOutputType | null
}

export type DodataAvgAggregateOutputType = {
  broj_racuna: number | null
  kolicina: number | null
}

export type DodataSumAggregateOutputType = {
  broj_racuna: number | null
  kolicina: number | null
}

export type DodataMinAggregateOutputType = {
  isbn: string | null
  broj_racuna: number | null
  kolicina: number | null
}

export type DodataMaxAggregateOutputType = {
  isbn: string | null
  broj_racuna: number | null
  kolicina: number | null
}

export type DodataCountAggregateOutputType = {
  isbn: number
  broj_racuna: number
  kolicina: number
  _all: number
}


export type DodataAvgAggregateInputType = {
  broj_racuna?: true
  kolicina?: true
}

export type DodataSumAggregateInputType = {
  broj_racuna?: true
  kolicina?: true
}

export type DodataMinAggregateInputType = {
  isbn?: true
  broj_racuna?: true
  kolicina?: true
}

export type DodataMaxAggregateInputType = {
  isbn?: true
  broj_racuna?: true
  kolicina?: true
}

export type DodataCountAggregateInputType = {
  isbn?: true
  broj_racuna?: true
  kolicina?: true
  _all?: true
}

export type DodataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dodata to aggregate.
   */
  where?: Prisma.dodataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dodata to fetch.
   */
  orderBy?: Prisma.dodataOrderByWithRelationInput | Prisma.dodataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dodataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dodata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dodata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dodata
  **/
  _count?: true | DodataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DodataAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DodataSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DodataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DodataMaxAggregateInputType
}

export type GetDodataAggregateType<T extends DodataAggregateArgs> = {
      [P in keyof T & keyof AggregateDodata]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDodata[P]>
    : Prisma.GetScalarType<T[P], AggregateDodata[P]>
}




export type dodataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dodataWhereInput
  orderBy?: Prisma.dodataOrderByWithAggregationInput | Prisma.dodataOrderByWithAggregationInput[]
  by: Prisma.DodataScalarFieldEnum[] | Prisma.DodataScalarFieldEnum
  having?: Prisma.dodataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DodataCountAggregateInputType | true
  _avg?: DodataAvgAggregateInputType
  _sum?: DodataSumAggregateInputType
  _min?: DodataMinAggregateInputType
  _max?: DodataMaxAggregateInputType
}

export type DodataGroupByOutputType = {
  isbn: string
  broj_racuna: number
  kolicina: number
  _count: DodataCountAggregateOutputType | null
  _avg: DodataAvgAggregateOutputType | null
  _sum: DodataSumAggregateOutputType | null
  _min: DodataMinAggregateOutputType | null
  _max: DodataMaxAggregateOutputType | null
}

export type GetDodataGroupByPayload<T extends dodataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DodataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DodataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DodataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DodataGroupByOutputType[P]>
      }
    >
  >



export type dodataWhereInput = {
  AND?: Prisma.dodataWhereInput | Prisma.dodataWhereInput[]
  OR?: Prisma.dodataWhereInput[]
  NOT?: Prisma.dodataWhereInput | Prisma.dodataWhereInput[]
  isbn?: Prisma.StringFilter<"dodata"> | string
  broj_racuna?: Prisma.IntFilter<"dodata"> | number
  kolicina?: Prisma.IntFilter<"dodata"> | number
  knjiga?: Prisma.XOR<Prisma.KnjigaScalarRelationFilter, Prisma.knjigaWhereInput>
  porudzbina?: Prisma.XOR<Prisma.PorudzbinaScalarRelationFilter, Prisma.porudzbinaWhereInput>
}

export type dodataOrderByWithRelationInput = {
  isbn?: Prisma.SortOrder
  broj_racuna?: Prisma.SortOrder
  kolicina?: Prisma.SortOrder
  knjiga?: Prisma.knjigaOrderByWithRelationInput
  porudzbina?: Prisma.porudzbinaOrderByWithRelationInput
  _relevance?: Prisma.dodataOrderByRelevanceInput
}

export type dodataWhereUniqueInput = Prisma.AtLeast<{
  isbn_broj_racuna?: Prisma.dodataIsbnBroj_racunaCompoundUniqueInput
  AND?: Prisma.dodataWhereInput | Prisma.dodataWhereInput[]
  OR?: Prisma.dodataWhereInput[]
  NOT?: Prisma.dodataWhereInput | Prisma.dodataWhereInput[]
  isbn?: Prisma.StringFilter<"dodata"> | string
  broj_racuna?: Prisma.IntFilter<"dodata"> | number
  kolicina?: Prisma.IntFilter<"dodata"> | number
  knjiga?: Prisma.XOR<Prisma.KnjigaScalarRelationFilter, Prisma.knjigaWhereInput>
  porudzbina?: Prisma.XOR<Prisma.PorudzbinaScalarRelationFilter, Prisma.porudzbinaWhereInput>
}, "isbn_broj_racuna">

export type dodataOrderByWithAggregationInput = {
  isbn?: Prisma.SortOrder
  broj_racuna?: Prisma.SortOrder
  kolicina?: Prisma.SortOrder
  _count?: Prisma.dodataCountOrderByAggregateInput
  _avg?: Prisma.dodataAvgOrderByAggregateInput
  _max?: Prisma.dodataMaxOrderByAggregateInput
  _min?: Prisma.dodataMinOrderByAggregateInput
  _sum?: Prisma.dodataSumOrderByAggregateInput
}

export type dodataScalarWhereWithAggregatesInput = {
  AND?: Prisma.dodataScalarWhereWithAggregatesInput | Prisma.dodataScalarWhereWithAggregatesInput[]
  OR?: Prisma.dodataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dodataScalarWhereWithAggregatesInput | Prisma.dodataScalarWhereWithAggregatesInput[]
  isbn?: Prisma.StringWithAggregatesFilter<"dodata"> | string
  broj_racuna?: Prisma.IntWithAggregatesFilter<"dodata"> | number
  kolicina?: Prisma.IntWithAggregatesFilter<"dodata"> | number
}

export type dodataCreateInput = {
  kolicina?: number
  knjiga: Prisma.knjigaCreateNestedOneWithoutDodataInput
  porudzbina: Prisma.porudzbinaCreateNestedOneWithoutDodataInput
}

export type dodataUncheckedCreateInput = {
  isbn: string
  broj_racuna: number
  kolicina?: number
}

export type dodataUpdateInput = {
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
  knjiga?: Prisma.knjigaUpdateOneRequiredWithoutDodataNestedInput
  porudzbina?: Prisma.porudzbinaUpdateOneRequiredWithoutDodataNestedInput
}

export type dodataUncheckedUpdateInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  broj_racuna?: Prisma.IntFieldUpdateOperationsInput | number
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dodataCreateManyInput = {
  isbn: string
  broj_racuna: number
  kolicina?: number
}

export type dodataUpdateManyMutationInput = {
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dodataUncheckedUpdateManyInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  broj_racuna?: Prisma.IntFieldUpdateOperationsInput | number
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dodataOrderByRelevanceInput = {
  fields: Prisma.dodataOrderByRelevanceFieldEnum | Prisma.dodataOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type dodataIsbnBroj_racunaCompoundUniqueInput = {
  isbn: string
  broj_racuna: number
}

export type dodataCountOrderByAggregateInput = {
  isbn?: Prisma.SortOrder
  broj_racuna?: Prisma.SortOrder
  kolicina?: Prisma.SortOrder
}

export type dodataAvgOrderByAggregateInput = {
  broj_racuna?: Prisma.SortOrder
  kolicina?: Prisma.SortOrder
}

export type dodataMaxOrderByAggregateInput = {
  isbn?: Prisma.SortOrder
  broj_racuna?: Prisma.SortOrder
  kolicina?: Prisma.SortOrder
}

export type dodataMinOrderByAggregateInput = {
  isbn?: Prisma.SortOrder
  broj_racuna?: Prisma.SortOrder
  kolicina?: Prisma.SortOrder
}

export type dodataSumOrderByAggregateInput = {
  broj_racuna?: Prisma.SortOrder
  kolicina?: Prisma.SortOrder
}

export type DodataListRelationFilter = {
  every?: Prisma.dodataWhereInput
  some?: Prisma.dodataWhereInput
  none?: Prisma.dodataWhereInput
}

export type dodataOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type dodataCreateNestedManyWithoutKnjigaInput = {
  create?: Prisma.XOR<Prisma.dodataCreateWithoutKnjigaInput, Prisma.dodataUncheckedCreateWithoutKnjigaInput> | Prisma.dodataCreateWithoutKnjigaInput[] | Prisma.dodataUncheckedCreateWithoutKnjigaInput[]
  connectOrCreate?: Prisma.dodataCreateOrConnectWithoutKnjigaInput | Prisma.dodataCreateOrConnectWithoutKnjigaInput[]
  createMany?: Prisma.dodataCreateManyKnjigaInputEnvelope
  connect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
}

export type dodataUncheckedCreateNestedManyWithoutKnjigaInput = {
  create?: Prisma.XOR<Prisma.dodataCreateWithoutKnjigaInput, Prisma.dodataUncheckedCreateWithoutKnjigaInput> | Prisma.dodataCreateWithoutKnjigaInput[] | Prisma.dodataUncheckedCreateWithoutKnjigaInput[]
  connectOrCreate?: Prisma.dodataCreateOrConnectWithoutKnjigaInput | Prisma.dodataCreateOrConnectWithoutKnjigaInput[]
  createMany?: Prisma.dodataCreateManyKnjigaInputEnvelope
  connect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
}

export type dodataUpdateManyWithoutKnjigaNestedInput = {
  create?: Prisma.XOR<Prisma.dodataCreateWithoutKnjigaInput, Prisma.dodataUncheckedCreateWithoutKnjigaInput> | Prisma.dodataCreateWithoutKnjigaInput[] | Prisma.dodataUncheckedCreateWithoutKnjigaInput[]
  connectOrCreate?: Prisma.dodataCreateOrConnectWithoutKnjigaInput | Prisma.dodataCreateOrConnectWithoutKnjigaInput[]
  upsert?: Prisma.dodataUpsertWithWhereUniqueWithoutKnjigaInput | Prisma.dodataUpsertWithWhereUniqueWithoutKnjigaInput[]
  createMany?: Prisma.dodataCreateManyKnjigaInputEnvelope
  set?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  disconnect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  delete?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  connect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  update?: Prisma.dodataUpdateWithWhereUniqueWithoutKnjigaInput | Prisma.dodataUpdateWithWhereUniqueWithoutKnjigaInput[]
  updateMany?: Prisma.dodataUpdateManyWithWhereWithoutKnjigaInput | Prisma.dodataUpdateManyWithWhereWithoutKnjigaInput[]
  deleteMany?: Prisma.dodataScalarWhereInput | Prisma.dodataScalarWhereInput[]
}

export type dodataUncheckedUpdateManyWithoutKnjigaNestedInput = {
  create?: Prisma.XOR<Prisma.dodataCreateWithoutKnjigaInput, Prisma.dodataUncheckedCreateWithoutKnjigaInput> | Prisma.dodataCreateWithoutKnjigaInput[] | Prisma.dodataUncheckedCreateWithoutKnjigaInput[]
  connectOrCreate?: Prisma.dodataCreateOrConnectWithoutKnjigaInput | Prisma.dodataCreateOrConnectWithoutKnjigaInput[]
  upsert?: Prisma.dodataUpsertWithWhereUniqueWithoutKnjigaInput | Prisma.dodataUpsertWithWhereUniqueWithoutKnjigaInput[]
  createMany?: Prisma.dodataCreateManyKnjigaInputEnvelope
  set?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  disconnect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  delete?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  connect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  update?: Prisma.dodataUpdateWithWhereUniqueWithoutKnjigaInput | Prisma.dodataUpdateWithWhereUniqueWithoutKnjigaInput[]
  updateMany?: Prisma.dodataUpdateManyWithWhereWithoutKnjigaInput | Prisma.dodataUpdateManyWithWhereWithoutKnjigaInput[]
  deleteMany?: Prisma.dodataScalarWhereInput | Prisma.dodataScalarWhereInput[]
}

export type dodataCreateNestedManyWithoutPorudzbinaInput = {
  create?: Prisma.XOR<Prisma.dodataCreateWithoutPorudzbinaInput, Prisma.dodataUncheckedCreateWithoutPorudzbinaInput> | Prisma.dodataCreateWithoutPorudzbinaInput[] | Prisma.dodataUncheckedCreateWithoutPorudzbinaInput[]
  connectOrCreate?: Prisma.dodataCreateOrConnectWithoutPorudzbinaInput | Prisma.dodataCreateOrConnectWithoutPorudzbinaInput[]
  createMany?: Prisma.dodataCreateManyPorudzbinaInputEnvelope
  connect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
}

export type dodataUncheckedCreateNestedManyWithoutPorudzbinaInput = {
  create?: Prisma.XOR<Prisma.dodataCreateWithoutPorudzbinaInput, Prisma.dodataUncheckedCreateWithoutPorudzbinaInput> | Prisma.dodataCreateWithoutPorudzbinaInput[] | Prisma.dodataUncheckedCreateWithoutPorudzbinaInput[]
  connectOrCreate?: Prisma.dodataCreateOrConnectWithoutPorudzbinaInput | Prisma.dodataCreateOrConnectWithoutPorudzbinaInput[]
  createMany?: Prisma.dodataCreateManyPorudzbinaInputEnvelope
  connect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
}

export type dodataUpdateManyWithoutPorudzbinaNestedInput = {
  create?: Prisma.XOR<Prisma.dodataCreateWithoutPorudzbinaInput, Prisma.dodataUncheckedCreateWithoutPorudzbinaInput> | Prisma.dodataCreateWithoutPorudzbinaInput[] | Prisma.dodataUncheckedCreateWithoutPorudzbinaInput[]
  connectOrCreate?: Prisma.dodataCreateOrConnectWithoutPorudzbinaInput | Prisma.dodataCreateOrConnectWithoutPorudzbinaInput[]
  upsert?: Prisma.dodataUpsertWithWhereUniqueWithoutPorudzbinaInput | Prisma.dodataUpsertWithWhereUniqueWithoutPorudzbinaInput[]
  createMany?: Prisma.dodataCreateManyPorudzbinaInputEnvelope
  set?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  disconnect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  delete?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  connect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  update?: Prisma.dodataUpdateWithWhereUniqueWithoutPorudzbinaInput | Prisma.dodataUpdateWithWhereUniqueWithoutPorudzbinaInput[]
  updateMany?: Prisma.dodataUpdateManyWithWhereWithoutPorudzbinaInput | Prisma.dodataUpdateManyWithWhereWithoutPorudzbinaInput[]
  deleteMany?: Prisma.dodataScalarWhereInput | Prisma.dodataScalarWhereInput[]
}

export type dodataUncheckedUpdateManyWithoutPorudzbinaNestedInput = {
  create?: Prisma.XOR<Prisma.dodataCreateWithoutPorudzbinaInput, Prisma.dodataUncheckedCreateWithoutPorudzbinaInput> | Prisma.dodataCreateWithoutPorudzbinaInput[] | Prisma.dodataUncheckedCreateWithoutPorudzbinaInput[]
  connectOrCreate?: Prisma.dodataCreateOrConnectWithoutPorudzbinaInput | Prisma.dodataCreateOrConnectWithoutPorudzbinaInput[]
  upsert?: Prisma.dodataUpsertWithWhereUniqueWithoutPorudzbinaInput | Prisma.dodataUpsertWithWhereUniqueWithoutPorudzbinaInput[]
  createMany?: Prisma.dodataCreateManyPorudzbinaInputEnvelope
  set?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  disconnect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  delete?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  connect?: Prisma.dodataWhereUniqueInput | Prisma.dodataWhereUniqueInput[]
  update?: Prisma.dodataUpdateWithWhereUniqueWithoutPorudzbinaInput | Prisma.dodataUpdateWithWhereUniqueWithoutPorudzbinaInput[]
  updateMany?: Prisma.dodataUpdateManyWithWhereWithoutPorudzbinaInput | Prisma.dodataUpdateManyWithWhereWithoutPorudzbinaInput[]
  deleteMany?: Prisma.dodataScalarWhereInput | Prisma.dodataScalarWhereInput[]
}

export type dodataCreateWithoutKnjigaInput = {
  kolicina?: number
  porudzbina: Prisma.porudzbinaCreateNestedOneWithoutDodataInput
}

export type dodataUncheckedCreateWithoutKnjigaInput = {
  broj_racuna: number
  kolicina?: number
}

export type dodataCreateOrConnectWithoutKnjigaInput = {
  where: Prisma.dodataWhereUniqueInput
  create: Prisma.XOR<Prisma.dodataCreateWithoutKnjigaInput, Prisma.dodataUncheckedCreateWithoutKnjigaInput>
}

export type dodataCreateManyKnjigaInputEnvelope = {
  data: Prisma.dodataCreateManyKnjigaInput | Prisma.dodataCreateManyKnjigaInput[]
  skipDuplicates?: boolean
}

export type dodataUpsertWithWhereUniqueWithoutKnjigaInput = {
  where: Prisma.dodataWhereUniqueInput
  update: Prisma.XOR<Prisma.dodataUpdateWithoutKnjigaInput, Prisma.dodataUncheckedUpdateWithoutKnjigaInput>
  create: Prisma.XOR<Prisma.dodataCreateWithoutKnjigaInput, Prisma.dodataUncheckedCreateWithoutKnjigaInput>
}

export type dodataUpdateWithWhereUniqueWithoutKnjigaInput = {
  where: Prisma.dodataWhereUniqueInput
  data: Prisma.XOR<Prisma.dodataUpdateWithoutKnjigaInput, Prisma.dodataUncheckedUpdateWithoutKnjigaInput>
}

export type dodataUpdateManyWithWhereWithoutKnjigaInput = {
  where: Prisma.dodataScalarWhereInput
  data: Prisma.XOR<Prisma.dodataUpdateManyMutationInput, Prisma.dodataUncheckedUpdateManyWithoutKnjigaInput>
}

export type dodataScalarWhereInput = {
  AND?: Prisma.dodataScalarWhereInput | Prisma.dodataScalarWhereInput[]
  OR?: Prisma.dodataScalarWhereInput[]
  NOT?: Prisma.dodataScalarWhereInput | Prisma.dodataScalarWhereInput[]
  isbn?: Prisma.StringFilter<"dodata"> | string
  broj_racuna?: Prisma.IntFilter<"dodata"> | number
  kolicina?: Prisma.IntFilter<"dodata"> | number
}

export type dodataCreateWithoutPorudzbinaInput = {
  kolicina?: number
  knjiga: Prisma.knjigaCreateNestedOneWithoutDodataInput
}

export type dodataUncheckedCreateWithoutPorudzbinaInput = {
  isbn: string
  kolicina?: number
}

export type dodataCreateOrConnectWithoutPorudzbinaInput = {
  where: Prisma.dodataWhereUniqueInput
  create: Prisma.XOR<Prisma.dodataCreateWithoutPorudzbinaInput, Prisma.dodataUncheckedCreateWithoutPorudzbinaInput>
}

export type dodataCreateManyPorudzbinaInputEnvelope = {
  data: Prisma.dodataCreateManyPorudzbinaInput | Prisma.dodataCreateManyPorudzbinaInput[]
  skipDuplicates?: boolean
}

export type dodataUpsertWithWhereUniqueWithoutPorudzbinaInput = {
  where: Prisma.dodataWhereUniqueInput
  update: Prisma.XOR<Prisma.dodataUpdateWithoutPorudzbinaInput, Prisma.dodataUncheckedUpdateWithoutPorudzbinaInput>
  create: Prisma.XOR<Prisma.dodataCreateWithoutPorudzbinaInput, Prisma.dodataUncheckedCreateWithoutPorudzbinaInput>
}

export type dodataUpdateWithWhereUniqueWithoutPorudzbinaInput = {
  where: Prisma.dodataWhereUniqueInput
  data: Prisma.XOR<Prisma.dodataUpdateWithoutPorudzbinaInput, Prisma.dodataUncheckedUpdateWithoutPorudzbinaInput>
}

export type dodataUpdateManyWithWhereWithoutPorudzbinaInput = {
  where: Prisma.dodataScalarWhereInput
  data: Prisma.XOR<Prisma.dodataUpdateManyMutationInput, Prisma.dodataUncheckedUpdateManyWithoutPorudzbinaInput>
}

export type dodataCreateManyKnjigaInput = {
  broj_racuna: number
  kolicina?: number
}

export type dodataUpdateWithoutKnjigaInput = {
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
  porudzbina?: Prisma.porudzbinaUpdateOneRequiredWithoutDodataNestedInput
}

export type dodataUncheckedUpdateWithoutKnjigaInput = {
  broj_racuna?: Prisma.IntFieldUpdateOperationsInput | number
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dodataUncheckedUpdateManyWithoutKnjigaInput = {
  broj_racuna?: Prisma.IntFieldUpdateOperationsInput | number
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dodataCreateManyPorudzbinaInput = {
  isbn: string
  kolicina?: number
}

export type dodataUpdateWithoutPorudzbinaInput = {
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
  knjiga?: Prisma.knjigaUpdateOneRequiredWithoutDodataNestedInput
}

export type dodataUncheckedUpdateWithoutPorudzbinaInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dodataUncheckedUpdateManyWithoutPorudzbinaInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  kolicina?: Prisma.IntFieldUpdateOperationsInput | number
}



export type dodataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  isbn?: boolean
  broj_racuna?: boolean
  kolicina?: boolean
  knjiga?: boolean | Prisma.knjigaDefaultArgs<ExtArgs>
  porudzbina?: boolean | Prisma.porudzbinaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dodata"]>



export type dodataSelectScalar = {
  isbn?: boolean
  broj_racuna?: boolean
  kolicina?: boolean
}

export type dodataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"isbn" | "broj_racuna" | "kolicina", ExtArgs["result"]["dodata"]>
export type dodataInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  knjiga?: boolean | Prisma.knjigaDefaultArgs<ExtArgs>
  porudzbina?: boolean | Prisma.porudzbinaDefaultArgs<ExtArgs>
}

export type $dodataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dodata"
  objects: {
    knjiga: Prisma.$knjigaPayload<ExtArgs>
    porudzbina: Prisma.$porudzbinaPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    isbn: string
    broj_racuna: number
    kolicina: number
  }, ExtArgs["result"]["dodata"]>
  composites: {}
}

export type dodataGetPayload<S extends boolean | null | undefined | dodataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dodataPayload, S>

export type dodataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dodataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DodataCountAggregateInputType | true
  }

export interface dodataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dodata'], meta: { name: 'dodata' } }
  /**
   * Find zero or one Dodata that matches the filter.
   * @param {dodataFindUniqueArgs} args - Arguments to find a Dodata
   * @example
   * // Get one Dodata
   * const dodata = await prisma.dodata.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dodataFindUniqueArgs>(args: Prisma.SelectSubset<T, dodataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dodataClient<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dodata that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dodataFindUniqueOrThrowArgs} args - Arguments to find a Dodata
   * @example
   * // Get one Dodata
   * const dodata = await prisma.dodata.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dodataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dodataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dodataClient<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dodata that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dodataFindFirstArgs} args - Arguments to find a Dodata
   * @example
   * // Get one Dodata
   * const dodata = await prisma.dodata.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dodataFindFirstArgs>(args?: Prisma.SelectSubset<T, dodataFindFirstArgs<ExtArgs>>): Prisma.Prisma__dodataClient<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dodata that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dodataFindFirstOrThrowArgs} args - Arguments to find a Dodata
   * @example
   * // Get one Dodata
   * const dodata = await prisma.dodata.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dodataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dodataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dodataClient<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dodata that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dodataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dodata
   * const dodata = await prisma.dodata.findMany()
   * 
   * // Get first 10 Dodata
   * const dodata = await prisma.dodata.findMany({ take: 10 })
   * 
   * // Only select the `isbn`
   * const dodataWithIsbnOnly = await prisma.dodata.findMany({ select: { isbn: true } })
   * 
   */
  findMany<T extends dodataFindManyArgs>(args?: Prisma.SelectSubset<T, dodataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dodata.
   * @param {dodataCreateArgs} args - Arguments to create a Dodata.
   * @example
   * // Create one Dodata
   * const Dodata = await prisma.dodata.create({
   *   data: {
   *     // ... data to create a Dodata
   *   }
   * })
   * 
   */
  create<T extends dodataCreateArgs>(args: Prisma.SelectSubset<T, dodataCreateArgs<ExtArgs>>): Prisma.Prisma__dodataClient<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dodata.
   * @param {dodataCreateManyArgs} args - Arguments to create many Dodata.
   * @example
   * // Create many Dodata
   * const dodata = await prisma.dodata.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dodataCreateManyArgs>(args?: Prisma.SelectSubset<T, dodataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Dodata.
   * @param {dodataDeleteArgs} args - Arguments to delete one Dodata.
   * @example
   * // Delete one Dodata
   * const Dodata = await prisma.dodata.delete({
   *   where: {
   *     // ... filter to delete one Dodata
   *   }
   * })
   * 
   */
  delete<T extends dodataDeleteArgs>(args: Prisma.SelectSubset<T, dodataDeleteArgs<ExtArgs>>): Prisma.Prisma__dodataClient<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dodata.
   * @param {dodataUpdateArgs} args - Arguments to update one Dodata.
   * @example
   * // Update one Dodata
   * const dodata = await prisma.dodata.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dodataUpdateArgs>(args: Prisma.SelectSubset<T, dodataUpdateArgs<ExtArgs>>): Prisma.Prisma__dodataClient<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dodata.
   * @param {dodataDeleteManyArgs} args - Arguments to filter Dodata to delete.
   * @example
   * // Delete a few Dodata
   * const { count } = await prisma.dodata.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dodataDeleteManyArgs>(args?: Prisma.SelectSubset<T, dodataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dodata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dodataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dodata
   * const dodata = await prisma.dodata.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dodataUpdateManyArgs>(args: Prisma.SelectSubset<T, dodataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Dodata.
   * @param {dodataUpsertArgs} args - Arguments to update or create a Dodata.
   * @example
   * // Update or create a Dodata
   * const dodata = await prisma.dodata.upsert({
   *   create: {
   *     // ... data to create a Dodata
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dodata we want to update
   *   }
   * })
   */
  upsert<T extends dodataUpsertArgs>(args: Prisma.SelectSubset<T, dodataUpsertArgs<ExtArgs>>): Prisma.Prisma__dodataClient<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dodata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dodataCountArgs} args - Arguments to filter Dodata to count.
   * @example
   * // Count the number of Dodata
   * const count = await prisma.dodata.count({
   *   where: {
   *     // ... the filter for the Dodata we want to count
   *   }
   * })
  **/
  count<T extends dodataCountArgs>(
    args?: Prisma.Subset<T, dodataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DodataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dodata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DodataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DodataAggregateArgs>(args: Prisma.Subset<T, DodataAggregateArgs>): Prisma.PrismaPromise<GetDodataAggregateType<T>>

  /**
   * Group by Dodata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dodataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dodataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dodataGroupByArgs['orderBy'] }
      : { orderBy?: dodataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dodataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDodataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dodata model
 */
readonly fields: dodataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dodata.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dodataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  knjiga<T extends Prisma.knjigaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.knjigaDefaultArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  porudzbina<T extends Prisma.porudzbinaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.porudzbinaDefaultArgs<ExtArgs>>): Prisma.Prisma__porudzbinaClient<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dodata model
 */
export interface dodataFieldRefs {
  readonly isbn: Prisma.FieldRef<"dodata", 'String'>
  readonly broj_racuna: Prisma.FieldRef<"dodata", 'Int'>
  readonly kolicina: Prisma.FieldRef<"dodata", 'Int'>
}
    

// Custom InputTypes
/**
 * dodata findUnique
 */
export type dodataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  /**
   * Filter, which dodata to fetch.
   */
  where: Prisma.dodataWhereUniqueInput
}

/**
 * dodata findUniqueOrThrow
 */
export type dodataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  /**
   * Filter, which dodata to fetch.
   */
  where: Prisma.dodataWhereUniqueInput
}

/**
 * dodata findFirst
 */
export type dodataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  /**
   * Filter, which dodata to fetch.
   */
  where?: Prisma.dodataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dodata to fetch.
   */
  orderBy?: Prisma.dodataOrderByWithRelationInput | Prisma.dodataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dodata.
   */
  cursor?: Prisma.dodataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dodata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dodata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dodata.
   */
  distinct?: Prisma.DodataScalarFieldEnum | Prisma.DodataScalarFieldEnum[]
}

/**
 * dodata findFirstOrThrow
 */
export type dodataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  /**
   * Filter, which dodata to fetch.
   */
  where?: Prisma.dodataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dodata to fetch.
   */
  orderBy?: Prisma.dodataOrderByWithRelationInput | Prisma.dodataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dodata.
   */
  cursor?: Prisma.dodataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dodata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dodata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dodata.
   */
  distinct?: Prisma.DodataScalarFieldEnum | Prisma.DodataScalarFieldEnum[]
}

/**
 * dodata findMany
 */
export type dodataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  /**
   * Filter, which dodata to fetch.
   */
  where?: Prisma.dodataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dodata to fetch.
   */
  orderBy?: Prisma.dodataOrderByWithRelationInput | Prisma.dodataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dodata.
   */
  cursor?: Prisma.dodataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dodata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dodata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dodata.
   */
  distinct?: Prisma.DodataScalarFieldEnum | Prisma.DodataScalarFieldEnum[]
}

/**
 * dodata create
 */
export type dodataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  /**
   * The data needed to create a dodata.
   */
  data: Prisma.XOR<Prisma.dodataCreateInput, Prisma.dodataUncheckedCreateInput>
}

/**
 * dodata createMany
 */
export type dodataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dodata.
   */
  data: Prisma.dodataCreateManyInput | Prisma.dodataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dodata update
 */
export type dodataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  /**
   * The data needed to update a dodata.
   */
  data: Prisma.XOR<Prisma.dodataUpdateInput, Prisma.dodataUncheckedUpdateInput>
  /**
   * Choose, which dodata to update.
   */
  where: Prisma.dodataWhereUniqueInput
}

/**
 * dodata updateMany
 */
export type dodataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dodata.
   */
  data: Prisma.XOR<Prisma.dodataUpdateManyMutationInput, Prisma.dodataUncheckedUpdateManyInput>
  /**
   * Filter which dodata to update
   */
  where?: Prisma.dodataWhereInput
  /**
   * Limit how many dodata to update.
   */
  limit?: number
}

/**
 * dodata upsert
 */
export type dodataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  /**
   * The filter to search for the dodata to update in case it exists.
   */
  where: Prisma.dodataWhereUniqueInput
  /**
   * In case the dodata found by the `where` argument doesn't exist, create a new dodata with this data.
   */
  create: Prisma.XOR<Prisma.dodataCreateInput, Prisma.dodataUncheckedCreateInput>
  /**
   * In case the dodata was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dodataUpdateInput, Prisma.dodataUncheckedUpdateInput>
}

/**
 * dodata delete
 */
export type dodataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  /**
   * Filter which dodata to delete.
   */
  where: Prisma.dodataWhereUniqueInput
}

/**
 * dodata deleteMany
 */
export type dodataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dodata to delete
   */
  where?: Prisma.dodataWhereInput
  /**
   * Limit how many dodata to delete.
   */
  limit?: number
}

/**
 * dodata without action
 */
export type dodataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
}
