
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `knjiga` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model knjiga
 * 
 */
export type knjigaModel = runtime.Types.Result.DefaultSelection<Prisma.$knjigaPayload>

export type AggregateKnjiga = {
  _count: KnjigaCountAggregateOutputType | null
  _avg: KnjigaAvgAggregateOutputType | null
  _sum: KnjigaSumAggregateOutputType | null
  _min: KnjigaMinAggregateOutputType | null
  _max: KnjigaMaxAggregateOutputType | null
}

export type KnjigaAvgAggregateOutputType = {
  godina_izdavanja_originala: number | null
  godina_izdavanja: number | null
  cena: runtime.Decimal | null
  broj_strana: number | null
  autor_id: number | null
  zanr_id: number | null
  izdavac_id: number | null
}

export type KnjigaSumAggregateOutputType = {
  godina_izdavanja_originala: number | null
  godina_izdavanja: number | null
  cena: runtime.Decimal | null
  broj_strana: number | null
  autor_id: number | null
  zanr_id: number | null
  izdavac_id: number | null
}

export type KnjigaMinAggregateOutputType = {
  isbn: string | null
  naslov: string | null
  naslov_originala: string | null
  godina_izdavanja_originala: number | null
  godina_izdavanja: number | null
  cena: runtime.Decimal | null
  povez: string | null
  pismo: string | null
  slika_korice: string | null
  broj_strana: number | null
  opis: string | null
  autor_id: number | null
  zanr_id: number | null
  izdavac_id: number | null
}

export type KnjigaMaxAggregateOutputType = {
  isbn: string | null
  naslov: string | null
  naslov_originala: string | null
  godina_izdavanja_originala: number | null
  godina_izdavanja: number | null
  cena: runtime.Decimal | null
  povez: string | null
  pismo: string | null
  slika_korice: string | null
  broj_strana: number | null
  opis: string | null
  autor_id: number | null
  zanr_id: number | null
  izdavac_id: number | null
}

export type KnjigaCountAggregateOutputType = {
  isbn: number
  naslov: number
  naslov_originala: number
  godina_izdavanja_originala: number
  godina_izdavanja: number
  cena: number
  povez: number
  pismo: number
  slika_korice: number
  broj_strana: number
  opis: number
  autor_id: number
  zanr_id: number
  izdavac_id: number
  _all: number
}


export type KnjigaAvgAggregateInputType = {
  godina_izdavanja_originala?: true
  godina_izdavanja?: true
  cena?: true
  broj_strana?: true
  autor_id?: true
  zanr_id?: true
  izdavac_id?: true
}

export type KnjigaSumAggregateInputType = {
  godina_izdavanja_originala?: true
  godina_izdavanja?: true
  cena?: true
  broj_strana?: true
  autor_id?: true
  zanr_id?: true
  izdavac_id?: true
}

export type KnjigaMinAggregateInputType = {
  isbn?: true
  naslov?: true
  naslov_originala?: true
  godina_izdavanja_originala?: true
  godina_izdavanja?: true
  cena?: true
  povez?: true
  pismo?: true
  slika_korice?: true
  broj_strana?: true
  opis?: true
  autor_id?: true
  zanr_id?: true
  izdavac_id?: true
}

export type KnjigaMaxAggregateInputType = {
  isbn?: true
  naslov?: true
  naslov_originala?: true
  godina_izdavanja_originala?: true
  godina_izdavanja?: true
  cena?: true
  povez?: true
  pismo?: true
  slika_korice?: true
  broj_strana?: true
  opis?: true
  autor_id?: true
  zanr_id?: true
  izdavac_id?: true
}

export type KnjigaCountAggregateInputType = {
  isbn?: true
  naslov?: true
  naslov_originala?: true
  godina_izdavanja_originala?: true
  godina_izdavanja?: true
  cena?: true
  povez?: true
  pismo?: true
  slika_korice?: true
  broj_strana?: true
  opis?: true
  autor_id?: true
  zanr_id?: true
  izdavac_id?: true
  _all?: true
}

export type KnjigaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which knjiga to aggregate.
   */
  where?: Prisma.knjigaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of knjigas to fetch.
   */
  orderBy?: Prisma.knjigaOrderByWithRelationInput | Prisma.knjigaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.knjigaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` knjigas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` knjigas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned knjigas
  **/
  _count?: true | KnjigaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: KnjigaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: KnjigaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KnjigaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KnjigaMaxAggregateInputType
}

export type GetKnjigaAggregateType<T extends KnjigaAggregateArgs> = {
      [P in keyof T & keyof AggregateKnjiga]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKnjiga[P]>
    : Prisma.GetScalarType<T[P], AggregateKnjiga[P]>
}




export type knjigaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.knjigaWhereInput
  orderBy?: Prisma.knjigaOrderByWithAggregationInput | Prisma.knjigaOrderByWithAggregationInput[]
  by: Prisma.KnjigaScalarFieldEnum[] | Prisma.KnjigaScalarFieldEnum
  having?: Prisma.knjigaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KnjigaCountAggregateInputType | true
  _avg?: KnjigaAvgAggregateInputType
  _sum?: KnjigaSumAggregateInputType
  _min?: KnjigaMinAggregateInputType
  _max?: KnjigaMaxAggregateInputType
}

export type KnjigaGroupByOutputType = {
  isbn: string
  naslov: string
  naslov_originala: string | null
  godina_izdavanja_originala: number | null
  godina_izdavanja: number | null
  cena: runtime.Decimal
  povez: string | null
  pismo: string | null
  slika_korice: string | null
  broj_strana: number | null
  opis: string | null
  autor_id: number
  zanr_id: number
  izdavac_id: number
  _count: KnjigaCountAggregateOutputType | null
  _avg: KnjigaAvgAggregateOutputType | null
  _sum: KnjigaSumAggregateOutputType | null
  _min: KnjigaMinAggregateOutputType | null
  _max: KnjigaMaxAggregateOutputType | null
}

export type GetKnjigaGroupByPayload<T extends knjigaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KnjigaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KnjigaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KnjigaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KnjigaGroupByOutputType[P]>
      }
    >
  >



export type knjigaWhereInput = {
  AND?: Prisma.knjigaWhereInput | Prisma.knjigaWhereInput[]
  OR?: Prisma.knjigaWhereInput[]
  NOT?: Prisma.knjigaWhereInput | Prisma.knjigaWhereInput[]
  isbn?: Prisma.StringFilter<"knjiga"> | string
  naslov?: Prisma.StringFilter<"knjiga"> | string
  naslov_originala?: Prisma.StringNullableFilter<"knjiga"> | string | null
  godina_izdavanja_originala?: Prisma.IntNullableFilter<"knjiga"> | number | null
  godina_izdavanja?: Prisma.IntNullableFilter<"knjiga"> | number | null
  cena?: Prisma.DecimalFilter<"knjiga"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.StringNullableFilter<"knjiga"> | string | null
  pismo?: Prisma.StringNullableFilter<"knjiga"> | string | null
  slika_korice?: Prisma.StringNullableFilter<"knjiga"> | string | null
  broj_strana?: Prisma.IntNullableFilter<"knjiga"> | number | null
  opis?: Prisma.StringNullableFilter<"knjiga"> | string | null
  autor_id?: Prisma.IntFilter<"knjiga"> | number
  zanr_id?: Prisma.IntFilter<"knjiga"> | number
  izdavac_id?: Prisma.IntFilter<"knjiga"> | number
  dodata?: Prisma.DodataListRelationFilter
  autor?: Prisma.XOR<Prisma.AutorScalarRelationFilter, Prisma.autorWhereInput>
  zanr?: Prisma.XOR<Prisma.ZanrScalarRelationFilter, Prisma.zanrWhereInput>
  izdavac?: Prisma.XOR<Prisma.IzdavacScalarRelationFilter, Prisma.izdavacWhereInput>
  slika_uzorak?: Prisma.Slika_uzorakListRelationFilter
}

export type knjigaOrderByWithRelationInput = {
  isbn?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  naslov_originala?: Prisma.SortOrderInput | Prisma.SortOrder
  godina_izdavanja_originala?: Prisma.SortOrderInput | Prisma.SortOrder
  godina_izdavanja?: Prisma.SortOrderInput | Prisma.SortOrder
  cena?: Prisma.SortOrder
  povez?: Prisma.SortOrderInput | Prisma.SortOrder
  pismo?: Prisma.SortOrderInput | Prisma.SortOrder
  slika_korice?: Prisma.SortOrderInput | Prisma.SortOrder
  broj_strana?: Prisma.SortOrderInput | Prisma.SortOrder
  opis?: Prisma.SortOrderInput | Prisma.SortOrder
  autor_id?: Prisma.SortOrder
  zanr_id?: Prisma.SortOrder
  izdavac_id?: Prisma.SortOrder
  dodata?: Prisma.dodataOrderByRelationAggregateInput
  autor?: Prisma.autorOrderByWithRelationInput
  zanr?: Prisma.zanrOrderByWithRelationInput
  izdavac?: Prisma.izdavacOrderByWithRelationInput
  slika_uzorak?: Prisma.slika_uzorakOrderByRelationAggregateInput
  _relevance?: Prisma.knjigaOrderByRelevanceInput
}

export type knjigaWhereUniqueInput = Prisma.AtLeast<{
  isbn?: string
  AND?: Prisma.knjigaWhereInput | Prisma.knjigaWhereInput[]
  OR?: Prisma.knjigaWhereInput[]
  NOT?: Prisma.knjigaWhereInput | Prisma.knjigaWhereInput[]
  naslov?: Prisma.StringFilter<"knjiga"> | string
  naslov_originala?: Prisma.StringNullableFilter<"knjiga"> | string | null
  godina_izdavanja_originala?: Prisma.IntNullableFilter<"knjiga"> | number | null
  godina_izdavanja?: Prisma.IntNullableFilter<"knjiga"> | number | null
  cena?: Prisma.DecimalFilter<"knjiga"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.StringNullableFilter<"knjiga"> | string | null
  pismo?: Prisma.StringNullableFilter<"knjiga"> | string | null
  slika_korice?: Prisma.StringNullableFilter<"knjiga"> | string | null
  broj_strana?: Prisma.IntNullableFilter<"knjiga"> | number | null
  opis?: Prisma.StringNullableFilter<"knjiga"> | string | null
  autor_id?: Prisma.IntFilter<"knjiga"> | number
  zanr_id?: Prisma.IntFilter<"knjiga"> | number
  izdavac_id?: Prisma.IntFilter<"knjiga"> | number
  dodata?: Prisma.DodataListRelationFilter
  autor?: Prisma.XOR<Prisma.AutorScalarRelationFilter, Prisma.autorWhereInput>
  zanr?: Prisma.XOR<Prisma.ZanrScalarRelationFilter, Prisma.zanrWhereInput>
  izdavac?: Prisma.XOR<Prisma.IzdavacScalarRelationFilter, Prisma.izdavacWhereInput>
  slika_uzorak?: Prisma.Slika_uzorakListRelationFilter
}, "isbn">

export type knjigaOrderByWithAggregationInput = {
  isbn?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  naslov_originala?: Prisma.SortOrderInput | Prisma.SortOrder
  godina_izdavanja_originala?: Prisma.SortOrderInput | Prisma.SortOrder
  godina_izdavanja?: Prisma.SortOrderInput | Prisma.SortOrder
  cena?: Prisma.SortOrder
  povez?: Prisma.SortOrderInput | Prisma.SortOrder
  pismo?: Prisma.SortOrderInput | Prisma.SortOrder
  slika_korice?: Prisma.SortOrderInput | Prisma.SortOrder
  broj_strana?: Prisma.SortOrderInput | Prisma.SortOrder
  opis?: Prisma.SortOrderInput | Prisma.SortOrder
  autor_id?: Prisma.SortOrder
  zanr_id?: Prisma.SortOrder
  izdavac_id?: Prisma.SortOrder
  _count?: Prisma.knjigaCountOrderByAggregateInput
  _avg?: Prisma.knjigaAvgOrderByAggregateInput
  _max?: Prisma.knjigaMaxOrderByAggregateInput
  _min?: Prisma.knjigaMinOrderByAggregateInput
  _sum?: Prisma.knjigaSumOrderByAggregateInput
}

export type knjigaScalarWhereWithAggregatesInput = {
  AND?: Prisma.knjigaScalarWhereWithAggregatesInput | Prisma.knjigaScalarWhereWithAggregatesInput[]
  OR?: Prisma.knjigaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.knjigaScalarWhereWithAggregatesInput | Prisma.knjigaScalarWhereWithAggregatesInput[]
  isbn?: Prisma.StringWithAggregatesFilter<"knjiga"> | string
  naslov?: Prisma.StringWithAggregatesFilter<"knjiga"> | string
  naslov_originala?: Prisma.StringNullableWithAggregatesFilter<"knjiga"> | string | null
  godina_izdavanja_originala?: Prisma.IntNullableWithAggregatesFilter<"knjiga"> | number | null
  godina_izdavanja?: Prisma.IntNullableWithAggregatesFilter<"knjiga"> | number | null
  cena?: Prisma.DecimalWithAggregatesFilter<"knjiga"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.StringNullableWithAggregatesFilter<"knjiga"> | string | null
  pismo?: Prisma.StringNullableWithAggregatesFilter<"knjiga"> | string | null
  slika_korice?: Prisma.StringNullableWithAggregatesFilter<"knjiga"> | string | null
  broj_strana?: Prisma.IntNullableWithAggregatesFilter<"knjiga"> | number | null
  opis?: Prisma.StringNullableWithAggregatesFilter<"knjiga"> | string | null
  autor_id?: Prisma.IntWithAggregatesFilter<"knjiga"> | number
  zanr_id?: Prisma.IntWithAggregatesFilter<"knjiga"> | number
  izdavac_id?: Prisma.IntWithAggregatesFilter<"knjiga"> | number
}

export type knjigaCreateInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  dodata?: Prisma.dodataCreateNestedManyWithoutKnjigaInput
  autor: Prisma.autorCreateNestedOneWithoutKnjigaInput
  zanr: Prisma.zanrCreateNestedOneWithoutKnjigaInput
  izdavac: Prisma.izdavacCreateNestedOneWithoutKnjigaInput
  slika_uzorak?: Prisma.slika_uzorakCreateNestedManyWithoutKnjigaInput
}

export type knjigaUncheckedCreateInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  autor_id: number
  zanr_id: number
  izdavac_id: number
  dodata?: Prisma.dodataUncheckedCreateNestedManyWithoutKnjigaInput
  slika_uzorak?: Prisma.slika_uzorakUncheckedCreateNestedManyWithoutKnjigaInput
}

export type knjigaUpdateInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dodata?: Prisma.dodataUpdateManyWithoutKnjigaNestedInput
  autor?: Prisma.autorUpdateOneRequiredWithoutKnjigaNestedInput
  zanr?: Prisma.zanrUpdateOneRequiredWithoutKnjigaNestedInput
  izdavac?: Prisma.izdavacUpdateOneRequiredWithoutKnjigaNestedInput
  slika_uzorak?: Prisma.slika_uzorakUpdateManyWithoutKnjigaNestedInput
}

export type knjigaUncheckedUpdateInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  izdavac_id?: Prisma.IntFieldUpdateOperationsInput | number
  dodata?: Prisma.dodataUncheckedUpdateManyWithoutKnjigaNestedInput
  slika_uzorak?: Prisma.slika_uzorakUncheckedUpdateManyWithoutKnjigaNestedInput
}

export type knjigaCreateManyInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  autor_id: number
  zanr_id: number
  izdavac_id: number
}

export type knjigaUpdateManyMutationInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type knjigaUncheckedUpdateManyInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  izdavac_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type KnjigaListRelationFilter = {
  every?: Prisma.knjigaWhereInput
  some?: Prisma.knjigaWhereInput
  none?: Prisma.knjigaWhereInput
}

export type knjigaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KnjigaScalarRelationFilter = {
  is?: Prisma.knjigaWhereInput
  isNot?: Prisma.knjigaWhereInput
}

export type knjigaOrderByRelevanceInput = {
  fields: Prisma.knjigaOrderByRelevanceFieldEnum | Prisma.knjigaOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type knjigaCountOrderByAggregateInput = {
  isbn?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  naslov_originala?: Prisma.SortOrder
  godina_izdavanja_originala?: Prisma.SortOrder
  godina_izdavanja?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  povez?: Prisma.SortOrder
  pismo?: Prisma.SortOrder
  slika_korice?: Prisma.SortOrder
  broj_strana?: Prisma.SortOrder
  opis?: Prisma.SortOrder
  autor_id?: Prisma.SortOrder
  zanr_id?: Prisma.SortOrder
  izdavac_id?: Prisma.SortOrder
}

export type knjigaAvgOrderByAggregateInput = {
  godina_izdavanja_originala?: Prisma.SortOrder
  godina_izdavanja?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  broj_strana?: Prisma.SortOrder
  autor_id?: Prisma.SortOrder
  zanr_id?: Prisma.SortOrder
  izdavac_id?: Prisma.SortOrder
}

export type knjigaMaxOrderByAggregateInput = {
  isbn?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  naslov_originala?: Prisma.SortOrder
  godina_izdavanja_originala?: Prisma.SortOrder
  godina_izdavanja?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  povez?: Prisma.SortOrder
  pismo?: Prisma.SortOrder
  slika_korice?: Prisma.SortOrder
  broj_strana?: Prisma.SortOrder
  opis?: Prisma.SortOrder
  autor_id?: Prisma.SortOrder
  zanr_id?: Prisma.SortOrder
  izdavac_id?: Prisma.SortOrder
}

export type knjigaMinOrderByAggregateInput = {
  isbn?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  naslov_originala?: Prisma.SortOrder
  godina_izdavanja_originala?: Prisma.SortOrder
  godina_izdavanja?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  povez?: Prisma.SortOrder
  pismo?: Prisma.SortOrder
  slika_korice?: Prisma.SortOrder
  broj_strana?: Prisma.SortOrder
  opis?: Prisma.SortOrder
  autor_id?: Prisma.SortOrder
  zanr_id?: Prisma.SortOrder
  izdavac_id?: Prisma.SortOrder
}

export type knjigaSumOrderByAggregateInput = {
  godina_izdavanja_originala?: Prisma.SortOrder
  godina_izdavanja?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  broj_strana?: Prisma.SortOrder
  autor_id?: Prisma.SortOrder
  zanr_id?: Prisma.SortOrder
  izdavac_id?: Prisma.SortOrder
}

export type knjigaCreateNestedManyWithoutAutorInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutAutorInput, Prisma.knjigaUncheckedCreateWithoutAutorInput> | Prisma.knjigaCreateWithoutAutorInput[] | Prisma.knjigaUncheckedCreateWithoutAutorInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutAutorInput | Prisma.knjigaCreateOrConnectWithoutAutorInput[]
  createMany?: Prisma.knjigaCreateManyAutorInputEnvelope
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
}

export type knjigaUncheckedCreateNestedManyWithoutAutorInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutAutorInput, Prisma.knjigaUncheckedCreateWithoutAutorInput> | Prisma.knjigaCreateWithoutAutorInput[] | Prisma.knjigaUncheckedCreateWithoutAutorInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutAutorInput | Prisma.knjigaCreateOrConnectWithoutAutorInput[]
  createMany?: Prisma.knjigaCreateManyAutorInputEnvelope
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
}

export type knjigaUpdateManyWithoutAutorNestedInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutAutorInput, Prisma.knjigaUncheckedCreateWithoutAutorInput> | Prisma.knjigaCreateWithoutAutorInput[] | Prisma.knjigaUncheckedCreateWithoutAutorInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutAutorInput | Prisma.knjigaCreateOrConnectWithoutAutorInput[]
  upsert?: Prisma.knjigaUpsertWithWhereUniqueWithoutAutorInput | Prisma.knjigaUpsertWithWhereUniqueWithoutAutorInput[]
  createMany?: Prisma.knjigaCreateManyAutorInputEnvelope
  set?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  disconnect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  delete?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  update?: Prisma.knjigaUpdateWithWhereUniqueWithoutAutorInput | Prisma.knjigaUpdateWithWhereUniqueWithoutAutorInput[]
  updateMany?: Prisma.knjigaUpdateManyWithWhereWithoutAutorInput | Prisma.knjigaUpdateManyWithWhereWithoutAutorInput[]
  deleteMany?: Prisma.knjigaScalarWhereInput | Prisma.knjigaScalarWhereInput[]
}

export type knjigaUncheckedUpdateManyWithoutAutorNestedInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutAutorInput, Prisma.knjigaUncheckedCreateWithoutAutorInput> | Prisma.knjigaCreateWithoutAutorInput[] | Prisma.knjigaUncheckedCreateWithoutAutorInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutAutorInput | Prisma.knjigaCreateOrConnectWithoutAutorInput[]
  upsert?: Prisma.knjigaUpsertWithWhereUniqueWithoutAutorInput | Prisma.knjigaUpsertWithWhereUniqueWithoutAutorInput[]
  createMany?: Prisma.knjigaCreateManyAutorInputEnvelope
  set?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  disconnect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  delete?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  update?: Prisma.knjigaUpdateWithWhereUniqueWithoutAutorInput | Prisma.knjigaUpdateWithWhereUniqueWithoutAutorInput[]
  updateMany?: Prisma.knjigaUpdateManyWithWhereWithoutAutorInput | Prisma.knjigaUpdateManyWithWhereWithoutAutorInput[]
  deleteMany?: Prisma.knjigaScalarWhereInput | Prisma.knjigaScalarWhereInput[]
}

export type knjigaCreateNestedOneWithoutDodataInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutDodataInput, Prisma.knjigaUncheckedCreateWithoutDodataInput>
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutDodataInput
  connect?: Prisma.knjigaWhereUniqueInput
}

export type knjigaUpdateOneRequiredWithoutDodataNestedInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutDodataInput, Prisma.knjigaUncheckedCreateWithoutDodataInput>
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutDodataInput
  upsert?: Prisma.knjigaUpsertWithoutDodataInput
  connect?: Prisma.knjigaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.knjigaUpdateToOneWithWhereWithoutDodataInput, Prisma.knjigaUpdateWithoutDodataInput>, Prisma.knjigaUncheckedUpdateWithoutDodataInput>
}

export type knjigaCreateNestedManyWithoutIzdavacInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutIzdavacInput, Prisma.knjigaUncheckedCreateWithoutIzdavacInput> | Prisma.knjigaCreateWithoutIzdavacInput[] | Prisma.knjigaUncheckedCreateWithoutIzdavacInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutIzdavacInput | Prisma.knjigaCreateOrConnectWithoutIzdavacInput[]
  createMany?: Prisma.knjigaCreateManyIzdavacInputEnvelope
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
}

export type knjigaUncheckedCreateNestedManyWithoutIzdavacInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutIzdavacInput, Prisma.knjigaUncheckedCreateWithoutIzdavacInput> | Prisma.knjigaCreateWithoutIzdavacInput[] | Prisma.knjigaUncheckedCreateWithoutIzdavacInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutIzdavacInput | Prisma.knjigaCreateOrConnectWithoutIzdavacInput[]
  createMany?: Prisma.knjigaCreateManyIzdavacInputEnvelope
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
}

export type knjigaUpdateManyWithoutIzdavacNestedInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutIzdavacInput, Prisma.knjigaUncheckedCreateWithoutIzdavacInput> | Prisma.knjigaCreateWithoutIzdavacInput[] | Prisma.knjigaUncheckedCreateWithoutIzdavacInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutIzdavacInput | Prisma.knjigaCreateOrConnectWithoutIzdavacInput[]
  upsert?: Prisma.knjigaUpsertWithWhereUniqueWithoutIzdavacInput | Prisma.knjigaUpsertWithWhereUniqueWithoutIzdavacInput[]
  createMany?: Prisma.knjigaCreateManyIzdavacInputEnvelope
  set?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  disconnect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  delete?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  update?: Prisma.knjigaUpdateWithWhereUniqueWithoutIzdavacInput | Prisma.knjigaUpdateWithWhereUniqueWithoutIzdavacInput[]
  updateMany?: Prisma.knjigaUpdateManyWithWhereWithoutIzdavacInput | Prisma.knjigaUpdateManyWithWhereWithoutIzdavacInput[]
  deleteMany?: Prisma.knjigaScalarWhereInput | Prisma.knjigaScalarWhereInput[]
}

export type knjigaUncheckedUpdateManyWithoutIzdavacNestedInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutIzdavacInput, Prisma.knjigaUncheckedCreateWithoutIzdavacInput> | Prisma.knjigaCreateWithoutIzdavacInput[] | Prisma.knjigaUncheckedCreateWithoutIzdavacInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutIzdavacInput | Prisma.knjigaCreateOrConnectWithoutIzdavacInput[]
  upsert?: Prisma.knjigaUpsertWithWhereUniqueWithoutIzdavacInput | Prisma.knjigaUpsertWithWhereUniqueWithoutIzdavacInput[]
  createMany?: Prisma.knjigaCreateManyIzdavacInputEnvelope
  set?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  disconnect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  delete?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  update?: Prisma.knjigaUpdateWithWhereUniqueWithoutIzdavacInput | Prisma.knjigaUpdateWithWhereUniqueWithoutIzdavacInput[]
  updateMany?: Prisma.knjigaUpdateManyWithWhereWithoutIzdavacInput | Prisma.knjigaUpdateManyWithWhereWithoutIzdavacInput[]
  deleteMany?: Prisma.knjigaScalarWhereInput | Prisma.knjigaScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type knjigaCreateNestedOneWithoutSlika_uzorakInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutSlika_uzorakInput, Prisma.knjigaUncheckedCreateWithoutSlika_uzorakInput>
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutSlika_uzorakInput
  connect?: Prisma.knjigaWhereUniqueInput
}

export type knjigaUpdateOneRequiredWithoutSlika_uzorakNestedInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutSlika_uzorakInput, Prisma.knjigaUncheckedCreateWithoutSlika_uzorakInput>
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutSlika_uzorakInput
  upsert?: Prisma.knjigaUpsertWithoutSlika_uzorakInput
  connect?: Prisma.knjigaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.knjigaUpdateToOneWithWhereWithoutSlika_uzorakInput, Prisma.knjigaUpdateWithoutSlika_uzorakInput>, Prisma.knjigaUncheckedUpdateWithoutSlika_uzorakInput>
}

export type knjigaCreateNestedManyWithoutZanrInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutZanrInput, Prisma.knjigaUncheckedCreateWithoutZanrInput> | Prisma.knjigaCreateWithoutZanrInput[] | Prisma.knjigaUncheckedCreateWithoutZanrInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutZanrInput | Prisma.knjigaCreateOrConnectWithoutZanrInput[]
  createMany?: Prisma.knjigaCreateManyZanrInputEnvelope
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
}

export type knjigaUncheckedCreateNestedManyWithoutZanrInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutZanrInput, Prisma.knjigaUncheckedCreateWithoutZanrInput> | Prisma.knjigaCreateWithoutZanrInput[] | Prisma.knjigaUncheckedCreateWithoutZanrInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutZanrInput | Prisma.knjigaCreateOrConnectWithoutZanrInput[]
  createMany?: Prisma.knjigaCreateManyZanrInputEnvelope
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
}

export type knjigaUpdateManyWithoutZanrNestedInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutZanrInput, Prisma.knjigaUncheckedCreateWithoutZanrInput> | Prisma.knjigaCreateWithoutZanrInput[] | Prisma.knjigaUncheckedCreateWithoutZanrInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutZanrInput | Prisma.knjigaCreateOrConnectWithoutZanrInput[]
  upsert?: Prisma.knjigaUpsertWithWhereUniqueWithoutZanrInput | Prisma.knjigaUpsertWithWhereUniqueWithoutZanrInput[]
  createMany?: Prisma.knjigaCreateManyZanrInputEnvelope
  set?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  disconnect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  delete?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  update?: Prisma.knjigaUpdateWithWhereUniqueWithoutZanrInput | Prisma.knjigaUpdateWithWhereUniqueWithoutZanrInput[]
  updateMany?: Prisma.knjigaUpdateManyWithWhereWithoutZanrInput | Prisma.knjigaUpdateManyWithWhereWithoutZanrInput[]
  deleteMany?: Prisma.knjigaScalarWhereInput | Prisma.knjigaScalarWhereInput[]
}

export type knjigaUncheckedUpdateManyWithoutZanrNestedInput = {
  create?: Prisma.XOR<Prisma.knjigaCreateWithoutZanrInput, Prisma.knjigaUncheckedCreateWithoutZanrInput> | Prisma.knjigaCreateWithoutZanrInput[] | Prisma.knjigaUncheckedCreateWithoutZanrInput[]
  connectOrCreate?: Prisma.knjigaCreateOrConnectWithoutZanrInput | Prisma.knjigaCreateOrConnectWithoutZanrInput[]
  upsert?: Prisma.knjigaUpsertWithWhereUniqueWithoutZanrInput | Prisma.knjigaUpsertWithWhereUniqueWithoutZanrInput[]
  createMany?: Prisma.knjigaCreateManyZanrInputEnvelope
  set?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  disconnect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  delete?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  connect?: Prisma.knjigaWhereUniqueInput | Prisma.knjigaWhereUniqueInput[]
  update?: Prisma.knjigaUpdateWithWhereUniqueWithoutZanrInput | Prisma.knjigaUpdateWithWhereUniqueWithoutZanrInput[]
  updateMany?: Prisma.knjigaUpdateManyWithWhereWithoutZanrInput | Prisma.knjigaUpdateManyWithWhereWithoutZanrInput[]
  deleteMany?: Prisma.knjigaScalarWhereInput | Prisma.knjigaScalarWhereInput[]
}

export type knjigaCreateWithoutAutorInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  dodata?: Prisma.dodataCreateNestedManyWithoutKnjigaInput
  zanr: Prisma.zanrCreateNestedOneWithoutKnjigaInput
  izdavac: Prisma.izdavacCreateNestedOneWithoutKnjigaInput
  slika_uzorak?: Prisma.slika_uzorakCreateNestedManyWithoutKnjigaInput
}

export type knjigaUncheckedCreateWithoutAutorInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  zanr_id: number
  izdavac_id: number
  dodata?: Prisma.dodataUncheckedCreateNestedManyWithoutKnjigaInput
  slika_uzorak?: Prisma.slika_uzorakUncheckedCreateNestedManyWithoutKnjigaInput
}

export type knjigaCreateOrConnectWithoutAutorInput = {
  where: Prisma.knjigaWhereUniqueInput
  create: Prisma.XOR<Prisma.knjigaCreateWithoutAutorInput, Prisma.knjigaUncheckedCreateWithoutAutorInput>
}

export type knjigaCreateManyAutorInputEnvelope = {
  data: Prisma.knjigaCreateManyAutorInput | Prisma.knjigaCreateManyAutorInput[]
  skipDuplicates?: boolean
}

export type knjigaUpsertWithWhereUniqueWithoutAutorInput = {
  where: Prisma.knjigaWhereUniqueInput
  update: Prisma.XOR<Prisma.knjigaUpdateWithoutAutorInput, Prisma.knjigaUncheckedUpdateWithoutAutorInput>
  create: Prisma.XOR<Prisma.knjigaCreateWithoutAutorInput, Prisma.knjigaUncheckedCreateWithoutAutorInput>
}

export type knjigaUpdateWithWhereUniqueWithoutAutorInput = {
  where: Prisma.knjigaWhereUniqueInput
  data: Prisma.XOR<Prisma.knjigaUpdateWithoutAutorInput, Prisma.knjigaUncheckedUpdateWithoutAutorInput>
}

export type knjigaUpdateManyWithWhereWithoutAutorInput = {
  where: Prisma.knjigaScalarWhereInput
  data: Prisma.XOR<Prisma.knjigaUpdateManyMutationInput, Prisma.knjigaUncheckedUpdateManyWithoutAutorInput>
}

export type knjigaScalarWhereInput = {
  AND?: Prisma.knjigaScalarWhereInput | Prisma.knjigaScalarWhereInput[]
  OR?: Prisma.knjigaScalarWhereInput[]
  NOT?: Prisma.knjigaScalarWhereInput | Prisma.knjigaScalarWhereInput[]
  isbn?: Prisma.StringFilter<"knjiga"> | string
  naslov?: Prisma.StringFilter<"knjiga"> | string
  naslov_originala?: Prisma.StringNullableFilter<"knjiga"> | string | null
  godina_izdavanja_originala?: Prisma.IntNullableFilter<"knjiga"> | number | null
  godina_izdavanja?: Prisma.IntNullableFilter<"knjiga"> | number | null
  cena?: Prisma.DecimalFilter<"knjiga"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.StringNullableFilter<"knjiga"> | string | null
  pismo?: Prisma.StringNullableFilter<"knjiga"> | string | null
  slika_korice?: Prisma.StringNullableFilter<"knjiga"> | string | null
  broj_strana?: Prisma.IntNullableFilter<"knjiga"> | number | null
  opis?: Prisma.StringNullableFilter<"knjiga"> | string | null
  autor_id?: Prisma.IntFilter<"knjiga"> | number
  zanr_id?: Prisma.IntFilter<"knjiga"> | number
  izdavac_id?: Prisma.IntFilter<"knjiga"> | number
}

export type knjigaCreateWithoutDodataInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  autor: Prisma.autorCreateNestedOneWithoutKnjigaInput
  zanr: Prisma.zanrCreateNestedOneWithoutKnjigaInput
  izdavac: Prisma.izdavacCreateNestedOneWithoutKnjigaInput
  slika_uzorak?: Prisma.slika_uzorakCreateNestedManyWithoutKnjigaInput
}

export type knjigaUncheckedCreateWithoutDodataInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  autor_id: number
  zanr_id: number
  izdavac_id: number
  slika_uzorak?: Prisma.slika_uzorakUncheckedCreateNestedManyWithoutKnjigaInput
}

export type knjigaCreateOrConnectWithoutDodataInput = {
  where: Prisma.knjigaWhereUniqueInput
  create: Prisma.XOR<Prisma.knjigaCreateWithoutDodataInput, Prisma.knjigaUncheckedCreateWithoutDodataInput>
}

export type knjigaUpsertWithoutDodataInput = {
  update: Prisma.XOR<Prisma.knjigaUpdateWithoutDodataInput, Prisma.knjigaUncheckedUpdateWithoutDodataInput>
  create: Prisma.XOR<Prisma.knjigaCreateWithoutDodataInput, Prisma.knjigaUncheckedCreateWithoutDodataInput>
  where?: Prisma.knjigaWhereInput
}

export type knjigaUpdateToOneWithWhereWithoutDodataInput = {
  where?: Prisma.knjigaWhereInput
  data: Prisma.XOR<Prisma.knjigaUpdateWithoutDodataInput, Prisma.knjigaUncheckedUpdateWithoutDodataInput>
}

export type knjigaUpdateWithoutDodataInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  autor?: Prisma.autorUpdateOneRequiredWithoutKnjigaNestedInput
  zanr?: Prisma.zanrUpdateOneRequiredWithoutKnjigaNestedInput
  izdavac?: Prisma.izdavacUpdateOneRequiredWithoutKnjigaNestedInput
  slika_uzorak?: Prisma.slika_uzorakUpdateManyWithoutKnjigaNestedInput
}

export type knjigaUncheckedUpdateWithoutDodataInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  izdavac_id?: Prisma.IntFieldUpdateOperationsInput | number
  slika_uzorak?: Prisma.slika_uzorakUncheckedUpdateManyWithoutKnjigaNestedInput
}

export type knjigaCreateWithoutIzdavacInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  dodata?: Prisma.dodataCreateNestedManyWithoutKnjigaInput
  autor: Prisma.autorCreateNestedOneWithoutKnjigaInput
  zanr: Prisma.zanrCreateNestedOneWithoutKnjigaInput
  slika_uzorak?: Prisma.slika_uzorakCreateNestedManyWithoutKnjigaInput
}

export type knjigaUncheckedCreateWithoutIzdavacInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  autor_id: number
  zanr_id: number
  dodata?: Prisma.dodataUncheckedCreateNestedManyWithoutKnjigaInput
  slika_uzorak?: Prisma.slika_uzorakUncheckedCreateNestedManyWithoutKnjigaInput
}

export type knjigaCreateOrConnectWithoutIzdavacInput = {
  where: Prisma.knjigaWhereUniqueInput
  create: Prisma.XOR<Prisma.knjigaCreateWithoutIzdavacInput, Prisma.knjigaUncheckedCreateWithoutIzdavacInput>
}

export type knjigaCreateManyIzdavacInputEnvelope = {
  data: Prisma.knjigaCreateManyIzdavacInput | Prisma.knjigaCreateManyIzdavacInput[]
  skipDuplicates?: boolean
}

export type knjigaUpsertWithWhereUniqueWithoutIzdavacInput = {
  where: Prisma.knjigaWhereUniqueInput
  update: Prisma.XOR<Prisma.knjigaUpdateWithoutIzdavacInput, Prisma.knjigaUncheckedUpdateWithoutIzdavacInput>
  create: Prisma.XOR<Prisma.knjigaCreateWithoutIzdavacInput, Prisma.knjigaUncheckedCreateWithoutIzdavacInput>
}

export type knjigaUpdateWithWhereUniqueWithoutIzdavacInput = {
  where: Prisma.knjigaWhereUniqueInput
  data: Prisma.XOR<Prisma.knjigaUpdateWithoutIzdavacInput, Prisma.knjigaUncheckedUpdateWithoutIzdavacInput>
}

export type knjigaUpdateManyWithWhereWithoutIzdavacInput = {
  where: Prisma.knjigaScalarWhereInput
  data: Prisma.XOR<Prisma.knjigaUpdateManyMutationInput, Prisma.knjigaUncheckedUpdateManyWithoutIzdavacInput>
}

export type knjigaCreateWithoutSlika_uzorakInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  dodata?: Prisma.dodataCreateNestedManyWithoutKnjigaInput
  autor: Prisma.autorCreateNestedOneWithoutKnjigaInput
  zanr: Prisma.zanrCreateNestedOneWithoutKnjigaInput
  izdavac: Prisma.izdavacCreateNestedOneWithoutKnjigaInput
}

export type knjigaUncheckedCreateWithoutSlika_uzorakInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  autor_id: number
  zanr_id: number
  izdavac_id: number
  dodata?: Prisma.dodataUncheckedCreateNestedManyWithoutKnjigaInput
}

export type knjigaCreateOrConnectWithoutSlika_uzorakInput = {
  where: Prisma.knjigaWhereUniqueInput
  create: Prisma.XOR<Prisma.knjigaCreateWithoutSlika_uzorakInput, Prisma.knjigaUncheckedCreateWithoutSlika_uzorakInput>
}

export type knjigaUpsertWithoutSlika_uzorakInput = {
  update: Prisma.XOR<Prisma.knjigaUpdateWithoutSlika_uzorakInput, Prisma.knjigaUncheckedUpdateWithoutSlika_uzorakInput>
  create: Prisma.XOR<Prisma.knjigaCreateWithoutSlika_uzorakInput, Prisma.knjigaUncheckedCreateWithoutSlika_uzorakInput>
  where?: Prisma.knjigaWhereInput
}

export type knjigaUpdateToOneWithWhereWithoutSlika_uzorakInput = {
  where?: Prisma.knjigaWhereInput
  data: Prisma.XOR<Prisma.knjigaUpdateWithoutSlika_uzorakInput, Prisma.knjigaUncheckedUpdateWithoutSlika_uzorakInput>
}

export type knjigaUpdateWithoutSlika_uzorakInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dodata?: Prisma.dodataUpdateManyWithoutKnjigaNestedInput
  autor?: Prisma.autorUpdateOneRequiredWithoutKnjigaNestedInput
  zanr?: Prisma.zanrUpdateOneRequiredWithoutKnjigaNestedInput
  izdavac?: Prisma.izdavacUpdateOneRequiredWithoutKnjigaNestedInput
}

export type knjigaUncheckedUpdateWithoutSlika_uzorakInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  izdavac_id?: Prisma.IntFieldUpdateOperationsInput | number
  dodata?: Prisma.dodataUncheckedUpdateManyWithoutKnjigaNestedInput
}

export type knjigaCreateWithoutZanrInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  dodata?: Prisma.dodataCreateNestedManyWithoutKnjigaInput
  autor: Prisma.autorCreateNestedOneWithoutKnjigaInput
  izdavac: Prisma.izdavacCreateNestedOneWithoutKnjigaInput
  slika_uzorak?: Prisma.slika_uzorakCreateNestedManyWithoutKnjigaInput
}

export type knjigaUncheckedCreateWithoutZanrInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  autor_id: number
  izdavac_id: number
  dodata?: Prisma.dodataUncheckedCreateNestedManyWithoutKnjigaInput
  slika_uzorak?: Prisma.slika_uzorakUncheckedCreateNestedManyWithoutKnjigaInput
}

export type knjigaCreateOrConnectWithoutZanrInput = {
  where: Prisma.knjigaWhereUniqueInput
  create: Prisma.XOR<Prisma.knjigaCreateWithoutZanrInput, Prisma.knjigaUncheckedCreateWithoutZanrInput>
}

export type knjigaCreateManyZanrInputEnvelope = {
  data: Prisma.knjigaCreateManyZanrInput | Prisma.knjigaCreateManyZanrInput[]
  skipDuplicates?: boolean
}

export type knjigaUpsertWithWhereUniqueWithoutZanrInput = {
  where: Prisma.knjigaWhereUniqueInput
  update: Prisma.XOR<Prisma.knjigaUpdateWithoutZanrInput, Prisma.knjigaUncheckedUpdateWithoutZanrInput>
  create: Prisma.XOR<Prisma.knjigaCreateWithoutZanrInput, Prisma.knjigaUncheckedCreateWithoutZanrInput>
}

export type knjigaUpdateWithWhereUniqueWithoutZanrInput = {
  where: Prisma.knjigaWhereUniqueInput
  data: Prisma.XOR<Prisma.knjigaUpdateWithoutZanrInput, Prisma.knjigaUncheckedUpdateWithoutZanrInput>
}

export type knjigaUpdateManyWithWhereWithoutZanrInput = {
  where: Prisma.knjigaScalarWhereInput
  data: Prisma.XOR<Prisma.knjigaUpdateManyMutationInput, Prisma.knjigaUncheckedUpdateManyWithoutZanrInput>
}

export type knjigaCreateManyAutorInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  zanr_id: number
  izdavac_id: number
}

export type knjigaUpdateWithoutAutorInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dodata?: Prisma.dodataUpdateManyWithoutKnjigaNestedInput
  zanr?: Prisma.zanrUpdateOneRequiredWithoutKnjigaNestedInput
  izdavac?: Prisma.izdavacUpdateOneRequiredWithoutKnjigaNestedInput
  slika_uzorak?: Prisma.slika_uzorakUpdateManyWithoutKnjigaNestedInput
}

export type knjigaUncheckedUpdateWithoutAutorInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  izdavac_id?: Prisma.IntFieldUpdateOperationsInput | number
  dodata?: Prisma.dodataUncheckedUpdateManyWithoutKnjigaNestedInput
  slika_uzorak?: Prisma.slika_uzorakUncheckedUpdateManyWithoutKnjigaNestedInput
}

export type knjigaUncheckedUpdateManyWithoutAutorInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  izdavac_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type knjigaCreateManyIzdavacInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  autor_id: number
  zanr_id: number
}

export type knjigaUpdateWithoutIzdavacInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dodata?: Prisma.dodataUpdateManyWithoutKnjigaNestedInput
  autor?: Prisma.autorUpdateOneRequiredWithoutKnjigaNestedInput
  zanr?: Prisma.zanrUpdateOneRequiredWithoutKnjigaNestedInput
  slika_uzorak?: Prisma.slika_uzorakUpdateManyWithoutKnjigaNestedInput
}

export type knjigaUncheckedUpdateWithoutIzdavacInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  dodata?: Prisma.dodataUncheckedUpdateManyWithoutKnjigaNestedInput
  slika_uzorak?: Prisma.slika_uzorakUncheckedUpdateManyWithoutKnjigaNestedInput
}

export type knjigaUncheckedUpdateManyWithoutIzdavacInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type knjigaCreateManyZanrInput = {
  isbn: string
  naslov: string
  naslov_originala?: string | null
  godina_izdavanja_originala?: number | null
  godina_izdavanja?: number | null
  cena: runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: string | null
  pismo?: string | null
  slika_korice?: string | null
  broj_strana?: number | null
  opis?: string | null
  autor_id: number
  izdavac_id: number
}

export type knjigaUpdateWithoutZanrInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dodata?: Prisma.dodataUpdateManyWithoutKnjigaNestedInput
  autor?: Prisma.autorUpdateOneRequiredWithoutKnjigaNestedInput
  izdavac?: Prisma.izdavacUpdateOneRequiredWithoutKnjigaNestedInput
  slika_uzorak?: Prisma.slika_uzorakUpdateManyWithoutKnjigaNestedInput
}

export type knjigaUncheckedUpdateWithoutZanrInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  izdavac_id?: Prisma.IntFieldUpdateOperationsInput | number
  dodata?: Prisma.dodataUncheckedUpdateManyWithoutKnjigaNestedInput
  slika_uzorak?: Prisma.slika_uzorakUncheckedUpdateManyWithoutKnjigaNestedInput
}

export type knjigaUncheckedUpdateManyWithoutZanrInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  naslov_originala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  godina_izdavanja_originala?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  godina_izdavanja?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cena?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  povez?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pismo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slika_korice?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  broj_strana?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  opis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  autor_id?: Prisma.IntFieldUpdateOperationsInput | number
  izdavac_id?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type KnjigaCountOutputType
 */

export type KnjigaCountOutputType = {
  dodata: number
  slika_uzorak: number
}

export type KnjigaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dodata?: boolean | KnjigaCountOutputTypeCountDodataArgs
  slika_uzorak?: boolean | KnjigaCountOutputTypeCountSlika_uzorakArgs
}

/**
 * KnjigaCountOutputType without action
 */
export type KnjigaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnjigaCountOutputType
   */
  select?: Prisma.KnjigaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * KnjigaCountOutputType without action
 */
export type KnjigaCountOutputTypeCountDodataArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dodataWhereInput
}

/**
 * KnjigaCountOutputType without action
 */
export type KnjigaCountOutputTypeCountSlika_uzorakArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.slika_uzorakWhereInput
}


export type knjigaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  isbn?: boolean
  naslov?: boolean
  naslov_originala?: boolean
  godina_izdavanja_originala?: boolean
  godina_izdavanja?: boolean
  cena?: boolean
  povez?: boolean
  pismo?: boolean
  slika_korice?: boolean
  broj_strana?: boolean
  opis?: boolean
  autor_id?: boolean
  zanr_id?: boolean
  izdavac_id?: boolean
  dodata?: boolean | Prisma.knjiga$dodataArgs<ExtArgs>
  autor?: boolean | Prisma.autorDefaultArgs<ExtArgs>
  zanr?: boolean | Prisma.zanrDefaultArgs<ExtArgs>
  izdavac?: boolean | Prisma.izdavacDefaultArgs<ExtArgs>
  slika_uzorak?: boolean | Prisma.knjiga$slika_uzorakArgs<ExtArgs>
  _count?: boolean | Prisma.KnjigaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["knjiga"]>



export type knjigaSelectScalar = {
  isbn?: boolean
  naslov?: boolean
  naslov_originala?: boolean
  godina_izdavanja_originala?: boolean
  godina_izdavanja?: boolean
  cena?: boolean
  povez?: boolean
  pismo?: boolean
  slika_korice?: boolean
  broj_strana?: boolean
  opis?: boolean
  autor_id?: boolean
  zanr_id?: boolean
  izdavac_id?: boolean
}

export type knjigaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"isbn" | "naslov" | "naslov_originala" | "godina_izdavanja_originala" | "godina_izdavanja" | "cena" | "povez" | "pismo" | "slika_korice" | "broj_strana" | "opis" | "autor_id" | "zanr_id" | "izdavac_id", ExtArgs["result"]["knjiga"]>
export type knjigaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dodata?: boolean | Prisma.knjiga$dodataArgs<ExtArgs>
  autor?: boolean | Prisma.autorDefaultArgs<ExtArgs>
  zanr?: boolean | Prisma.zanrDefaultArgs<ExtArgs>
  izdavac?: boolean | Prisma.izdavacDefaultArgs<ExtArgs>
  slika_uzorak?: boolean | Prisma.knjiga$slika_uzorakArgs<ExtArgs>
  _count?: boolean | Prisma.KnjigaCountOutputTypeDefaultArgs<ExtArgs>
}

export type $knjigaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "knjiga"
  objects: {
    dodata: Prisma.$dodataPayload<ExtArgs>[]
    autor: Prisma.$autorPayload<ExtArgs>
    zanr: Prisma.$zanrPayload<ExtArgs>
    izdavac: Prisma.$izdavacPayload<ExtArgs>
    slika_uzorak: Prisma.$slika_uzorakPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    isbn: string
    naslov: string
    naslov_originala: string | null
    godina_izdavanja_originala: number | null
    godina_izdavanja: number | null
    cena: runtime.Decimal
    povez: string | null
    pismo: string | null
    slika_korice: string | null
    broj_strana: number | null
    opis: string | null
    autor_id: number
    zanr_id: number
    izdavac_id: number
  }, ExtArgs["result"]["knjiga"]>
  composites: {}
}

export type knjigaGetPayload<S extends boolean | null | undefined | knjigaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$knjigaPayload, S>

export type knjigaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<knjigaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KnjigaCountAggregateInputType | true
  }

export interface knjigaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['knjiga'], meta: { name: 'knjiga' } }
  /**
   * Find zero or one Knjiga that matches the filter.
   * @param {knjigaFindUniqueArgs} args - Arguments to find a Knjiga
   * @example
   * // Get one Knjiga
   * const knjiga = await prisma.knjiga.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends knjigaFindUniqueArgs>(args: Prisma.SelectSubset<T, knjigaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Knjiga that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {knjigaFindUniqueOrThrowArgs} args - Arguments to find a Knjiga
   * @example
   * // Get one Knjiga
   * const knjiga = await prisma.knjiga.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends knjigaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, knjigaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Knjiga that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {knjigaFindFirstArgs} args - Arguments to find a Knjiga
   * @example
   * // Get one Knjiga
   * const knjiga = await prisma.knjiga.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends knjigaFindFirstArgs>(args?: Prisma.SelectSubset<T, knjigaFindFirstArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Knjiga that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {knjigaFindFirstOrThrowArgs} args - Arguments to find a Knjiga
   * @example
   * // Get one Knjiga
   * const knjiga = await prisma.knjiga.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends knjigaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, knjigaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Knjigas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {knjigaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Knjigas
   * const knjigas = await prisma.knjiga.findMany()
   * 
   * // Get first 10 Knjigas
   * const knjigas = await prisma.knjiga.findMany({ take: 10 })
   * 
   * // Only select the `isbn`
   * const knjigaWithIsbnOnly = await prisma.knjiga.findMany({ select: { isbn: true } })
   * 
   */
  findMany<T extends knjigaFindManyArgs>(args?: Prisma.SelectSubset<T, knjigaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Knjiga.
   * @param {knjigaCreateArgs} args - Arguments to create a Knjiga.
   * @example
   * // Create one Knjiga
   * const Knjiga = await prisma.knjiga.create({
   *   data: {
   *     // ... data to create a Knjiga
   *   }
   * })
   * 
   */
  create<T extends knjigaCreateArgs>(args: Prisma.SelectSubset<T, knjigaCreateArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Knjigas.
   * @param {knjigaCreateManyArgs} args - Arguments to create many Knjigas.
   * @example
   * // Create many Knjigas
   * const knjiga = await prisma.knjiga.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends knjigaCreateManyArgs>(args?: Prisma.SelectSubset<T, knjigaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Knjiga.
   * @param {knjigaDeleteArgs} args - Arguments to delete one Knjiga.
   * @example
   * // Delete one Knjiga
   * const Knjiga = await prisma.knjiga.delete({
   *   where: {
   *     // ... filter to delete one Knjiga
   *   }
   * })
   * 
   */
  delete<T extends knjigaDeleteArgs>(args: Prisma.SelectSubset<T, knjigaDeleteArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Knjiga.
   * @param {knjigaUpdateArgs} args - Arguments to update one Knjiga.
   * @example
   * // Update one Knjiga
   * const knjiga = await prisma.knjiga.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends knjigaUpdateArgs>(args: Prisma.SelectSubset<T, knjigaUpdateArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Knjigas.
   * @param {knjigaDeleteManyArgs} args - Arguments to filter Knjigas to delete.
   * @example
   * // Delete a few Knjigas
   * const { count } = await prisma.knjiga.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends knjigaDeleteManyArgs>(args?: Prisma.SelectSubset<T, knjigaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Knjigas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {knjigaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Knjigas
   * const knjiga = await prisma.knjiga.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends knjigaUpdateManyArgs>(args: Prisma.SelectSubset<T, knjigaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Knjiga.
   * @param {knjigaUpsertArgs} args - Arguments to update or create a Knjiga.
   * @example
   * // Update or create a Knjiga
   * const knjiga = await prisma.knjiga.upsert({
   *   create: {
   *     // ... data to create a Knjiga
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Knjiga we want to update
   *   }
   * })
   */
  upsert<T extends knjigaUpsertArgs>(args: Prisma.SelectSubset<T, knjigaUpsertArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Knjigas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {knjigaCountArgs} args - Arguments to filter Knjigas to count.
   * @example
   * // Count the number of Knjigas
   * const count = await prisma.knjiga.count({
   *   where: {
   *     // ... the filter for the Knjigas we want to count
   *   }
   * })
  **/
  count<T extends knjigaCountArgs>(
    args?: Prisma.Subset<T, knjigaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KnjigaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Knjiga.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KnjigaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KnjigaAggregateArgs>(args: Prisma.Subset<T, KnjigaAggregateArgs>): Prisma.PrismaPromise<GetKnjigaAggregateType<T>>

  /**
   * Group by Knjiga.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {knjigaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends knjigaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: knjigaGroupByArgs['orderBy'] }
      : { orderBy?: knjigaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, knjigaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKnjigaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the knjiga model
 */
readonly fields: knjigaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for knjiga.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__knjigaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dodata<T extends Prisma.knjiga$dodataArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.knjiga$dodataArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  autor<T extends Prisma.autorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.autorDefaultArgs<ExtArgs>>): Prisma.Prisma__autorClient<runtime.Types.Result.GetResult<Prisma.$autorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  zanr<T extends Prisma.zanrDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.zanrDefaultArgs<ExtArgs>>): Prisma.Prisma__zanrClient<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  izdavac<T extends Prisma.izdavacDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.izdavacDefaultArgs<ExtArgs>>): Prisma.Prisma__izdavacClient<runtime.Types.Result.GetResult<Prisma.$izdavacPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  slika_uzorak<T extends Prisma.knjiga$slika_uzorakArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.knjiga$slika_uzorakArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the knjiga model
 */
export interface knjigaFieldRefs {
  readonly isbn: Prisma.FieldRef<"knjiga", 'String'>
  readonly naslov: Prisma.FieldRef<"knjiga", 'String'>
  readonly naslov_originala: Prisma.FieldRef<"knjiga", 'String'>
  readonly godina_izdavanja_originala: Prisma.FieldRef<"knjiga", 'Int'>
  readonly godina_izdavanja: Prisma.FieldRef<"knjiga", 'Int'>
  readonly cena: Prisma.FieldRef<"knjiga", 'Decimal'>
  readonly povez: Prisma.FieldRef<"knjiga", 'String'>
  readonly pismo: Prisma.FieldRef<"knjiga", 'String'>
  readonly slika_korice: Prisma.FieldRef<"knjiga", 'String'>
  readonly broj_strana: Prisma.FieldRef<"knjiga", 'Int'>
  readonly opis: Prisma.FieldRef<"knjiga", 'String'>
  readonly autor_id: Prisma.FieldRef<"knjiga", 'Int'>
  readonly zanr_id: Prisma.FieldRef<"knjiga", 'Int'>
  readonly izdavac_id: Prisma.FieldRef<"knjiga", 'Int'>
}
    

// Custom InputTypes
/**
 * knjiga findUnique
 */
export type knjigaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  /**
   * Filter, which knjiga to fetch.
   */
  where: Prisma.knjigaWhereUniqueInput
}

/**
 * knjiga findUniqueOrThrow
 */
export type knjigaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  /**
   * Filter, which knjiga to fetch.
   */
  where: Prisma.knjigaWhereUniqueInput
}

/**
 * knjiga findFirst
 */
export type knjigaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  /**
   * Filter, which knjiga to fetch.
   */
  where?: Prisma.knjigaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of knjigas to fetch.
   */
  orderBy?: Prisma.knjigaOrderByWithRelationInput | Prisma.knjigaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for knjigas.
   */
  cursor?: Prisma.knjigaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` knjigas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` knjigas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of knjigas.
   */
  distinct?: Prisma.KnjigaScalarFieldEnum | Prisma.KnjigaScalarFieldEnum[]
}

/**
 * knjiga findFirstOrThrow
 */
export type knjigaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  /**
   * Filter, which knjiga to fetch.
   */
  where?: Prisma.knjigaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of knjigas to fetch.
   */
  orderBy?: Prisma.knjigaOrderByWithRelationInput | Prisma.knjigaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for knjigas.
   */
  cursor?: Prisma.knjigaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` knjigas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` knjigas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of knjigas.
   */
  distinct?: Prisma.KnjigaScalarFieldEnum | Prisma.KnjigaScalarFieldEnum[]
}

/**
 * knjiga findMany
 */
export type knjigaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  /**
   * Filter, which knjigas to fetch.
   */
  where?: Prisma.knjigaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of knjigas to fetch.
   */
  orderBy?: Prisma.knjigaOrderByWithRelationInput | Prisma.knjigaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing knjigas.
   */
  cursor?: Prisma.knjigaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` knjigas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` knjigas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of knjigas.
   */
  distinct?: Prisma.KnjigaScalarFieldEnum | Prisma.KnjigaScalarFieldEnum[]
}

/**
 * knjiga create
 */
export type knjigaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  /**
   * The data needed to create a knjiga.
   */
  data: Prisma.XOR<Prisma.knjigaCreateInput, Prisma.knjigaUncheckedCreateInput>
}

/**
 * knjiga createMany
 */
export type knjigaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many knjigas.
   */
  data: Prisma.knjigaCreateManyInput | Prisma.knjigaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * knjiga update
 */
export type knjigaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  /**
   * The data needed to update a knjiga.
   */
  data: Prisma.XOR<Prisma.knjigaUpdateInput, Prisma.knjigaUncheckedUpdateInput>
  /**
   * Choose, which knjiga to update.
   */
  where: Prisma.knjigaWhereUniqueInput
}

/**
 * knjiga updateMany
 */
export type knjigaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update knjigas.
   */
  data: Prisma.XOR<Prisma.knjigaUpdateManyMutationInput, Prisma.knjigaUncheckedUpdateManyInput>
  /**
   * Filter which knjigas to update
   */
  where?: Prisma.knjigaWhereInput
  /**
   * Limit how many knjigas to update.
   */
  limit?: number
}

/**
 * knjiga upsert
 */
export type knjigaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  /**
   * The filter to search for the knjiga to update in case it exists.
   */
  where: Prisma.knjigaWhereUniqueInput
  /**
   * In case the knjiga found by the `where` argument doesn't exist, create a new knjiga with this data.
   */
  create: Prisma.XOR<Prisma.knjigaCreateInput, Prisma.knjigaUncheckedCreateInput>
  /**
   * In case the knjiga was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.knjigaUpdateInput, Prisma.knjigaUncheckedUpdateInput>
}

/**
 * knjiga delete
 */
export type knjigaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  /**
   * Filter which knjiga to delete.
   */
  where: Prisma.knjigaWhereUniqueInput
}

/**
 * knjiga deleteMany
 */
export type knjigaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which knjigas to delete
   */
  where?: Prisma.knjigaWhereInput
  /**
   * Limit how many knjigas to delete.
   */
  limit?: number
}

/**
 * knjiga.dodata
 */
export type knjiga$dodataArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  where?: Prisma.dodataWhereInput
  orderBy?: Prisma.dodataOrderByWithRelationInput | Prisma.dodataOrderByWithRelationInput[]
  cursor?: Prisma.dodataWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DodataScalarFieldEnum | Prisma.DodataScalarFieldEnum[]
}

/**
 * knjiga.slika_uzorak
 */
export type knjiga$slika_uzorakArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  where?: Prisma.slika_uzorakWhereInput
  orderBy?: Prisma.slika_uzorakOrderByWithRelationInput | Prisma.slika_uzorakOrderByWithRelationInput[]
  cursor?: Prisma.slika_uzorakWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Slika_uzorakScalarFieldEnum | Prisma.Slika_uzorakScalarFieldEnum[]
}

/**
 * knjiga without action
 */
export type knjigaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
}
