
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `porudzbina` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model porudzbina
 * 
 */
export type porudzbinaModel = runtime.Types.Result.DefaultSelection<Prisma.$porudzbinaPayload>

export type AggregatePorudzbina = {
  _count: PorudzbinaCountAggregateOutputType | null
  _avg: PorudzbinaAvgAggregateOutputType | null
  _sum: PorudzbinaSumAggregateOutputType | null
  _min: PorudzbinaMinAggregateOutputType | null
  _max: PorudzbinaMaxAggregateOutputType | null
}

export type PorudzbinaAvgAggregateOutputType = {
  broj_racuna: number | null
  iznos: runtime.Decimal | null
  korisnik_id: number | null
}

export type PorudzbinaSumAggregateOutputType = {
  broj_racuna: number | null
  iznos: runtime.Decimal | null
  korisnik_id: number | null
}

export type PorudzbinaMinAggregateOutputType = {
  broj_racuna: number | null
  datum: Date | null
  iznos: runtime.Decimal | null
  korisnik_id: number | null
}

export type PorudzbinaMaxAggregateOutputType = {
  broj_racuna: number | null
  datum: Date | null
  iznos: runtime.Decimal | null
  korisnik_id: number | null
}

export type PorudzbinaCountAggregateOutputType = {
  broj_racuna: number
  datum: number
  iznos: number
  korisnik_id: number
  _all: number
}


export type PorudzbinaAvgAggregateInputType = {
  broj_racuna?: true
  iznos?: true
  korisnik_id?: true
}

export type PorudzbinaSumAggregateInputType = {
  broj_racuna?: true
  iznos?: true
  korisnik_id?: true
}

export type PorudzbinaMinAggregateInputType = {
  broj_racuna?: true
  datum?: true
  iznos?: true
  korisnik_id?: true
}

export type PorudzbinaMaxAggregateInputType = {
  broj_racuna?: true
  datum?: true
  iznos?: true
  korisnik_id?: true
}

export type PorudzbinaCountAggregateInputType = {
  broj_racuna?: true
  datum?: true
  iznos?: true
  korisnik_id?: true
  _all?: true
}

export type PorudzbinaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which porudzbina to aggregate.
   */
  where?: Prisma.porudzbinaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of porudzbinas to fetch.
   */
  orderBy?: Prisma.porudzbinaOrderByWithRelationInput | Prisma.porudzbinaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.porudzbinaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` porudzbinas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` porudzbinas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned porudzbinas
  **/
  _count?: true | PorudzbinaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PorudzbinaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PorudzbinaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PorudzbinaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PorudzbinaMaxAggregateInputType
}

export type GetPorudzbinaAggregateType<T extends PorudzbinaAggregateArgs> = {
      [P in keyof T & keyof AggregatePorudzbina]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePorudzbina[P]>
    : Prisma.GetScalarType<T[P], AggregatePorudzbina[P]>
}




export type porudzbinaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.porudzbinaWhereInput
  orderBy?: Prisma.porudzbinaOrderByWithAggregationInput | Prisma.porudzbinaOrderByWithAggregationInput[]
  by: Prisma.PorudzbinaScalarFieldEnum[] | Prisma.PorudzbinaScalarFieldEnum
  having?: Prisma.porudzbinaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PorudzbinaCountAggregateInputType | true
  _avg?: PorudzbinaAvgAggregateInputType
  _sum?: PorudzbinaSumAggregateInputType
  _min?: PorudzbinaMinAggregateInputType
  _max?: PorudzbinaMaxAggregateInputType
}

export type PorudzbinaGroupByOutputType = {
  broj_racuna: number
  datum: Date
  iznos: runtime.Decimal
  korisnik_id: number
  _count: PorudzbinaCountAggregateOutputType | null
  _avg: PorudzbinaAvgAggregateOutputType | null
  _sum: PorudzbinaSumAggregateOutputType | null
  _min: PorudzbinaMinAggregateOutputType | null
  _max: PorudzbinaMaxAggregateOutputType | null
}

export type GetPorudzbinaGroupByPayload<T extends porudzbinaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PorudzbinaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PorudzbinaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PorudzbinaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PorudzbinaGroupByOutputType[P]>
      }
    >
  >



export type porudzbinaWhereInput = {
  AND?: Prisma.porudzbinaWhereInput | Prisma.porudzbinaWhereInput[]
  OR?: Prisma.porudzbinaWhereInput[]
  NOT?: Prisma.porudzbinaWhereInput | Prisma.porudzbinaWhereInput[]
  broj_racuna?: Prisma.IntFilter<"porudzbina"> | number
  datum?: Prisma.DateTimeFilter<"porudzbina"> | Date | string
  iznos?: Prisma.DecimalFilter<"porudzbina"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id?: Prisma.IntFilter<"porudzbina"> | number
  dodata?: Prisma.DodataListRelationFilter
  korisnik?: Prisma.XOR<Prisma.KorisnikScalarRelationFilter, Prisma.korisnikWhereInput>
}

export type porudzbinaOrderByWithRelationInput = {
  broj_racuna?: Prisma.SortOrder
  datum?: Prisma.SortOrder
  iznos?: Prisma.SortOrder
  korisnik_id?: Prisma.SortOrder
  dodata?: Prisma.dodataOrderByRelationAggregateInput
  korisnik?: Prisma.korisnikOrderByWithRelationInput
}

export type porudzbinaWhereUniqueInput = Prisma.AtLeast<{
  broj_racuna?: number
  AND?: Prisma.porudzbinaWhereInput | Prisma.porudzbinaWhereInput[]
  OR?: Prisma.porudzbinaWhereInput[]
  NOT?: Prisma.porudzbinaWhereInput | Prisma.porudzbinaWhereInput[]
  datum?: Prisma.DateTimeFilter<"porudzbina"> | Date | string
  iznos?: Prisma.DecimalFilter<"porudzbina"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id?: Prisma.IntFilter<"porudzbina"> | number
  dodata?: Prisma.DodataListRelationFilter
  korisnik?: Prisma.XOR<Prisma.KorisnikScalarRelationFilter, Prisma.korisnikWhereInput>
}, "broj_racuna">

export type porudzbinaOrderByWithAggregationInput = {
  broj_racuna?: Prisma.SortOrder
  datum?: Prisma.SortOrder
  iznos?: Prisma.SortOrder
  korisnik_id?: Prisma.SortOrder
  _count?: Prisma.porudzbinaCountOrderByAggregateInput
  _avg?: Prisma.porudzbinaAvgOrderByAggregateInput
  _max?: Prisma.porudzbinaMaxOrderByAggregateInput
  _min?: Prisma.porudzbinaMinOrderByAggregateInput
  _sum?: Prisma.porudzbinaSumOrderByAggregateInput
}

export type porudzbinaScalarWhereWithAggregatesInput = {
  AND?: Prisma.porudzbinaScalarWhereWithAggregatesInput | Prisma.porudzbinaScalarWhereWithAggregatesInput[]
  OR?: Prisma.porudzbinaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.porudzbinaScalarWhereWithAggregatesInput | Prisma.porudzbinaScalarWhereWithAggregatesInput[]
  broj_racuna?: Prisma.IntWithAggregatesFilter<"porudzbina"> | number
  datum?: Prisma.DateTimeWithAggregatesFilter<"porudzbina"> | Date | string
  iznos?: Prisma.DecimalWithAggregatesFilter<"porudzbina"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id?: Prisma.IntWithAggregatesFilter<"porudzbina"> | number
}

export type porudzbinaCreateInput = {
  datum?: Date | string
  iznos?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dodata?: Prisma.dodataCreateNestedManyWithoutPorudzbinaInput
  korisnik: Prisma.korisnikCreateNestedOneWithoutPorudzbinaInput
}

export type porudzbinaUncheckedCreateInput = {
  broj_racuna?: number
  datum?: Date | string
  iznos?: runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id: number
  dodata?: Prisma.dodataUncheckedCreateNestedManyWithoutPorudzbinaInput
}

export type porudzbinaUpdateInput = {
  datum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iznos?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dodata?: Prisma.dodataUpdateManyWithoutPorudzbinaNestedInput
  korisnik?: Prisma.korisnikUpdateOneRequiredWithoutPorudzbinaNestedInput
}

export type porudzbinaUncheckedUpdateInput = {
  broj_racuna?: Prisma.IntFieldUpdateOperationsInput | number
  datum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iznos?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id?: Prisma.IntFieldUpdateOperationsInput | number
  dodata?: Prisma.dodataUncheckedUpdateManyWithoutPorudzbinaNestedInput
}

export type porudzbinaCreateManyInput = {
  broj_racuna?: number
  datum?: Date | string
  iznos?: runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id: number
}

export type porudzbinaUpdateManyMutationInput = {
  datum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iznos?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type porudzbinaUncheckedUpdateManyInput = {
  broj_racuna?: Prisma.IntFieldUpdateOperationsInput | number
  datum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iznos?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PorudzbinaScalarRelationFilter = {
  is?: Prisma.porudzbinaWhereInput
  isNot?: Prisma.porudzbinaWhereInput
}

export type PorudzbinaListRelationFilter = {
  every?: Prisma.porudzbinaWhereInput
  some?: Prisma.porudzbinaWhereInput
  none?: Prisma.porudzbinaWhereInput
}

export type porudzbinaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type porudzbinaCountOrderByAggregateInput = {
  broj_racuna?: Prisma.SortOrder
  datum?: Prisma.SortOrder
  iznos?: Prisma.SortOrder
  korisnik_id?: Prisma.SortOrder
}

export type porudzbinaAvgOrderByAggregateInput = {
  broj_racuna?: Prisma.SortOrder
  iznos?: Prisma.SortOrder
  korisnik_id?: Prisma.SortOrder
}

export type porudzbinaMaxOrderByAggregateInput = {
  broj_racuna?: Prisma.SortOrder
  datum?: Prisma.SortOrder
  iznos?: Prisma.SortOrder
  korisnik_id?: Prisma.SortOrder
}

export type porudzbinaMinOrderByAggregateInput = {
  broj_racuna?: Prisma.SortOrder
  datum?: Prisma.SortOrder
  iznos?: Prisma.SortOrder
  korisnik_id?: Prisma.SortOrder
}

export type porudzbinaSumOrderByAggregateInput = {
  broj_racuna?: Prisma.SortOrder
  iznos?: Prisma.SortOrder
  korisnik_id?: Prisma.SortOrder
}

export type porudzbinaCreateNestedOneWithoutDodataInput = {
  create?: Prisma.XOR<Prisma.porudzbinaCreateWithoutDodataInput, Prisma.porudzbinaUncheckedCreateWithoutDodataInput>
  connectOrCreate?: Prisma.porudzbinaCreateOrConnectWithoutDodataInput
  connect?: Prisma.porudzbinaWhereUniqueInput
}

export type porudzbinaUpdateOneRequiredWithoutDodataNestedInput = {
  create?: Prisma.XOR<Prisma.porudzbinaCreateWithoutDodataInput, Prisma.porudzbinaUncheckedCreateWithoutDodataInput>
  connectOrCreate?: Prisma.porudzbinaCreateOrConnectWithoutDodataInput
  upsert?: Prisma.porudzbinaUpsertWithoutDodataInput
  connect?: Prisma.porudzbinaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.porudzbinaUpdateToOneWithWhereWithoutDodataInput, Prisma.porudzbinaUpdateWithoutDodataInput>, Prisma.porudzbinaUncheckedUpdateWithoutDodataInput>
}

export type porudzbinaCreateNestedManyWithoutKorisnikInput = {
  create?: Prisma.XOR<Prisma.porudzbinaCreateWithoutKorisnikInput, Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput> | Prisma.porudzbinaCreateWithoutKorisnikInput[] | Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput[]
  connectOrCreate?: Prisma.porudzbinaCreateOrConnectWithoutKorisnikInput | Prisma.porudzbinaCreateOrConnectWithoutKorisnikInput[]
  createMany?: Prisma.porudzbinaCreateManyKorisnikInputEnvelope
  connect?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
}

export type porudzbinaUncheckedCreateNestedManyWithoutKorisnikInput = {
  create?: Prisma.XOR<Prisma.porudzbinaCreateWithoutKorisnikInput, Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput> | Prisma.porudzbinaCreateWithoutKorisnikInput[] | Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput[]
  connectOrCreate?: Prisma.porudzbinaCreateOrConnectWithoutKorisnikInput | Prisma.porudzbinaCreateOrConnectWithoutKorisnikInput[]
  createMany?: Prisma.porudzbinaCreateManyKorisnikInputEnvelope
  connect?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
}

export type porudzbinaUpdateManyWithoutKorisnikNestedInput = {
  create?: Prisma.XOR<Prisma.porudzbinaCreateWithoutKorisnikInput, Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput> | Prisma.porudzbinaCreateWithoutKorisnikInput[] | Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput[]
  connectOrCreate?: Prisma.porudzbinaCreateOrConnectWithoutKorisnikInput | Prisma.porudzbinaCreateOrConnectWithoutKorisnikInput[]
  upsert?: Prisma.porudzbinaUpsertWithWhereUniqueWithoutKorisnikInput | Prisma.porudzbinaUpsertWithWhereUniqueWithoutKorisnikInput[]
  createMany?: Prisma.porudzbinaCreateManyKorisnikInputEnvelope
  set?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
  disconnect?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
  delete?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
  connect?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
  update?: Prisma.porudzbinaUpdateWithWhereUniqueWithoutKorisnikInput | Prisma.porudzbinaUpdateWithWhereUniqueWithoutKorisnikInput[]
  updateMany?: Prisma.porudzbinaUpdateManyWithWhereWithoutKorisnikInput | Prisma.porudzbinaUpdateManyWithWhereWithoutKorisnikInput[]
  deleteMany?: Prisma.porudzbinaScalarWhereInput | Prisma.porudzbinaScalarWhereInput[]
}

export type porudzbinaUncheckedUpdateManyWithoutKorisnikNestedInput = {
  create?: Prisma.XOR<Prisma.porudzbinaCreateWithoutKorisnikInput, Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput> | Prisma.porudzbinaCreateWithoutKorisnikInput[] | Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput[]
  connectOrCreate?: Prisma.porudzbinaCreateOrConnectWithoutKorisnikInput | Prisma.porudzbinaCreateOrConnectWithoutKorisnikInput[]
  upsert?: Prisma.porudzbinaUpsertWithWhereUniqueWithoutKorisnikInput | Prisma.porudzbinaUpsertWithWhereUniqueWithoutKorisnikInput[]
  createMany?: Prisma.porudzbinaCreateManyKorisnikInputEnvelope
  set?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
  disconnect?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
  delete?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
  connect?: Prisma.porudzbinaWhereUniqueInput | Prisma.porudzbinaWhereUniqueInput[]
  update?: Prisma.porudzbinaUpdateWithWhereUniqueWithoutKorisnikInput | Prisma.porudzbinaUpdateWithWhereUniqueWithoutKorisnikInput[]
  updateMany?: Prisma.porudzbinaUpdateManyWithWhereWithoutKorisnikInput | Prisma.porudzbinaUpdateManyWithWhereWithoutKorisnikInput[]
  deleteMany?: Prisma.porudzbinaScalarWhereInput | Prisma.porudzbinaScalarWhereInput[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type porudzbinaCreateWithoutDodataInput = {
  datum?: Date | string
  iznos?: runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik: Prisma.korisnikCreateNestedOneWithoutPorudzbinaInput
}

export type porudzbinaUncheckedCreateWithoutDodataInput = {
  broj_racuna?: number
  datum?: Date | string
  iznos?: runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id: number
}

export type porudzbinaCreateOrConnectWithoutDodataInput = {
  where: Prisma.porudzbinaWhereUniqueInput
  create: Prisma.XOR<Prisma.porudzbinaCreateWithoutDodataInput, Prisma.porudzbinaUncheckedCreateWithoutDodataInput>
}

export type porudzbinaUpsertWithoutDodataInput = {
  update: Prisma.XOR<Prisma.porudzbinaUpdateWithoutDodataInput, Prisma.porudzbinaUncheckedUpdateWithoutDodataInput>
  create: Prisma.XOR<Prisma.porudzbinaCreateWithoutDodataInput, Prisma.porudzbinaUncheckedCreateWithoutDodataInput>
  where?: Prisma.porudzbinaWhereInput
}

export type porudzbinaUpdateToOneWithWhereWithoutDodataInput = {
  where?: Prisma.porudzbinaWhereInput
  data: Prisma.XOR<Prisma.porudzbinaUpdateWithoutDodataInput, Prisma.porudzbinaUncheckedUpdateWithoutDodataInput>
}

export type porudzbinaUpdateWithoutDodataInput = {
  datum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iznos?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik?: Prisma.korisnikUpdateOneRequiredWithoutPorudzbinaNestedInput
}

export type porudzbinaUncheckedUpdateWithoutDodataInput = {
  broj_racuna?: Prisma.IntFieldUpdateOperationsInput | number
  datum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iznos?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type porudzbinaCreateWithoutKorisnikInput = {
  datum?: Date | string
  iznos?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dodata?: Prisma.dodataCreateNestedManyWithoutPorudzbinaInput
}

export type porudzbinaUncheckedCreateWithoutKorisnikInput = {
  broj_racuna?: number
  datum?: Date | string
  iznos?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dodata?: Prisma.dodataUncheckedCreateNestedManyWithoutPorudzbinaInput
}

export type porudzbinaCreateOrConnectWithoutKorisnikInput = {
  where: Prisma.porudzbinaWhereUniqueInput
  create: Prisma.XOR<Prisma.porudzbinaCreateWithoutKorisnikInput, Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput>
}

export type porudzbinaCreateManyKorisnikInputEnvelope = {
  data: Prisma.porudzbinaCreateManyKorisnikInput | Prisma.porudzbinaCreateManyKorisnikInput[]
  skipDuplicates?: boolean
}

export type porudzbinaUpsertWithWhereUniqueWithoutKorisnikInput = {
  where: Prisma.porudzbinaWhereUniqueInput
  update: Prisma.XOR<Prisma.porudzbinaUpdateWithoutKorisnikInput, Prisma.porudzbinaUncheckedUpdateWithoutKorisnikInput>
  create: Prisma.XOR<Prisma.porudzbinaCreateWithoutKorisnikInput, Prisma.porudzbinaUncheckedCreateWithoutKorisnikInput>
}

export type porudzbinaUpdateWithWhereUniqueWithoutKorisnikInput = {
  where: Prisma.porudzbinaWhereUniqueInput
  data: Prisma.XOR<Prisma.porudzbinaUpdateWithoutKorisnikInput, Prisma.porudzbinaUncheckedUpdateWithoutKorisnikInput>
}

export type porudzbinaUpdateManyWithWhereWithoutKorisnikInput = {
  where: Prisma.porudzbinaScalarWhereInput
  data: Prisma.XOR<Prisma.porudzbinaUpdateManyMutationInput, Prisma.porudzbinaUncheckedUpdateManyWithoutKorisnikInput>
}

export type porudzbinaScalarWhereInput = {
  AND?: Prisma.porudzbinaScalarWhereInput | Prisma.porudzbinaScalarWhereInput[]
  OR?: Prisma.porudzbinaScalarWhereInput[]
  NOT?: Prisma.porudzbinaScalarWhereInput | Prisma.porudzbinaScalarWhereInput[]
  broj_racuna?: Prisma.IntFilter<"porudzbina"> | number
  datum?: Prisma.DateTimeFilter<"porudzbina"> | Date | string
  iznos?: Prisma.DecimalFilter<"porudzbina"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  korisnik_id?: Prisma.IntFilter<"porudzbina"> | number
}

export type porudzbinaCreateManyKorisnikInput = {
  broj_racuna?: number
  datum?: Date | string
  iznos?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type porudzbinaUpdateWithoutKorisnikInput = {
  datum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iznos?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dodata?: Prisma.dodataUpdateManyWithoutPorudzbinaNestedInput
}

export type porudzbinaUncheckedUpdateWithoutKorisnikInput = {
  broj_racuna?: Prisma.IntFieldUpdateOperationsInput | number
  datum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iznos?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dodata?: Prisma.dodataUncheckedUpdateManyWithoutPorudzbinaNestedInput
}

export type porudzbinaUncheckedUpdateManyWithoutKorisnikInput = {
  broj_racuna?: Prisma.IntFieldUpdateOperationsInput | number
  datum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iznos?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}


/**
 * Count Type PorudzbinaCountOutputType
 */

export type PorudzbinaCountOutputType = {
  dodata: number
}

export type PorudzbinaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dodata?: boolean | PorudzbinaCountOutputTypeCountDodataArgs
}

/**
 * PorudzbinaCountOutputType without action
 */
export type PorudzbinaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PorudzbinaCountOutputType
   */
  select?: Prisma.PorudzbinaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PorudzbinaCountOutputType without action
 */
export type PorudzbinaCountOutputTypeCountDodataArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dodataWhereInput
}


export type porudzbinaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  broj_racuna?: boolean
  datum?: boolean
  iznos?: boolean
  korisnik_id?: boolean
  dodata?: boolean | Prisma.porudzbina$dodataArgs<ExtArgs>
  korisnik?: boolean | Prisma.korisnikDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.PorudzbinaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["porudzbina"]>



export type porudzbinaSelectScalar = {
  broj_racuna?: boolean
  datum?: boolean
  iznos?: boolean
  korisnik_id?: boolean
}

export type porudzbinaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"broj_racuna" | "datum" | "iznos" | "korisnik_id", ExtArgs["result"]["porudzbina"]>
export type porudzbinaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dodata?: boolean | Prisma.porudzbina$dodataArgs<ExtArgs>
  korisnik?: boolean | Prisma.korisnikDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.PorudzbinaCountOutputTypeDefaultArgs<ExtArgs>
}

export type $porudzbinaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "porudzbina"
  objects: {
    dodata: Prisma.$dodataPayload<ExtArgs>[]
    korisnik: Prisma.$korisnikPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    broj_racuna: number
    datum: Date
    iznos: runtime.Decimal
    korisnik_id: number
  }, ExtArgs["result"]["porudzbina"]>
  composites: {}
}

export type porudzbinaGetPayload<S extends boolean | null | undefined | porudzbinaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload, S>

export type porudzbinaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<porudzbinaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PorudzbinaCountAggregateInputType | true
  }

export interface porudzbinaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['porudzbina'], meta: { name: 'porudzbina' } }
  /**
   * Find zero or one Porudzbina that matches the filter.
   * @param {porudzbinaFindUniqueArgs} args - Arguments to find a Porudzbina
   * @example
   * // Get one Porudzbina
   * const porudzbina = await prisma.porudzbina.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends porudzbinaFindUniqueArgs>(args: Prisma.SelectSubset<T, porudzbinaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__porudzbinaClient<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Porudzbina that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {porudzbinaFindUniqueOrThrowArgs} args - Arguments to find a Porudzbina
   * @example
   * // Get one Porudzbina
   * const porudzbina = await prisma.porudzbina.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends porudzbinaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, porudzbinaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__porudzbinaClient<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Porudzbina that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {porudzbinaFindFirstArgs} args - Arguments to find a Porudzbina
   * @example
   * // Get one Porudzbina
   * const porudzbina = await prisma.porudzbina.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends porudzbinaFindFirstArgs>(args?: Prisma.SelectSubset<T, porudzbinaFindFirstArgs<ExtArgs>>): Prisma.Prisma__porudzbinaClient<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Porudzbina that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {porudzbinaFindFirstOrThrowArgs} args - Arguments to find a Porudzbina
   * @example
   * // Get one Porudzbina
   * const porudzbina = await prisma.porudzbina.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends porudzbinaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, porudzbinaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__porudzbinaClient<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Porudzbinas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {porudzbinaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Porudzbinas
   * const porudzbinas = await prisma.porudzbina.findMany()
   * 
   * // Get first 10 Porudzbinas
   * const porudzbinas = await prisma.porudzbina.findMany({ take: 10 })
   * 
   * // Only select the `broj_racuna`
   * const porudzbinaWithBroj_racunaOnly = await prisma.porudzbina.findMany({ select: { broj_racuna: true } })
   * 
   */
  findMany<T extends porudzbinaFindManyArgs>(args?: Prisma.SelectSubset<T, porudzbinaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Porudzbina.
   * @param {porudzbinaCreateArgs} args - Arguments to create a Porudzbina.
   * @example
   * // Create one Porudzbina
   * const Porudzbina = await prisma.porudzbina.create({
   *   data: {
   *     // ... data to create a Porudzbina
   *   }
   * })
   * 
   */
  create<T extends porudzbinaCreateArgs>(args: Prisma.SelectSubset<T, porudzbinaCreateArgs<ExtArgs>>): Prisma.Prisma__porudzbinaClient<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Porudzbinas.
   * @param {porudzbinaCreateManyArgs} args - Arguments to create many Porudzbinas.
   * @example
   * // Create many Porudzbinas
   * const porudzbina = await prisma.porudzbina.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends porudzbinaCreateManyArgs>(args?: Prisma.SelectSubset<T, porudzbinaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Porudzbina.
   * @param {porudzbinaDeleteArgs} args - Arguments to delete one Porudzbina.
   * @example
   * // Delete one Porudzbina
   * const Porudzbina = await prisma.porudzbina.delete({
   *   where: {
   *     // ... filter to delete one Porudzbina
   *   }
   * })
   * 
   */
  delete<T extends porudzbinaDeleteArgs>(args: Prisma.SelectSubset<T, porudzbinaDeleteArgs<ExtArgs>>): Prisma.Prisma__porudzbinaClient<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Porudzbina.
   * @param {porudzbinaUpdateArgs} args - Arguments to update one Porudzbina.
   * @example
   * // Update one Porudzbina
   * const porudzbina = await prisma.porudzbina.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends porudzbinaUpdateArgs>(args: Prisma.SelectSubset<T, porudzbinaUpdateArgs<ExtArgs>>): Prisma.Prisma__porudzbinaClient<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Porudzbinas.
   * @param {porudzbinaDeleteManyArgs} args - Arguments to filter Porudzbinas to delete.
   * @example
   * // Delete a few Porudzbinas
   * const { count } = await prisma.porudzbina.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends porudzbinaDeleteManyArgs>(args?: Prisma.SelectSubset<T, porudzbinaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Porudzbinas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {porudzbinaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Porudzbinas
   * const porudzbina = await prisma.porudzbina.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends porudzbinaUpdateManyArgs>(args: Prisma.SelectSubset<T, porudzbinaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Porudzbina.
   * @param {porudzbinaUpsertArgs} args - Arguments to update or create a Porudzbina.
   * @example
   * // Update or create a Porudzbina
   * const porudzbina = await prisma.porudzbina.upsert({
   *   create: {
   *     // ... data to create a Porudzbina
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Porudzbina we want to update
   *   }
   * })
   */
  upsert<T extends porudzbinaUpsertArgs>(args: Prisma.SelectSubset<T, porudzbinaUpsertArgs<ExtArgs>>): Prisma.Prisma__porudzbinaClient<runtime.Types.Result.GetResult<Prisma.$porudzbinaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Porudzbinas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {porudzbinaCountArgs} args - Arguments to filter Porudzbinas to count.
   * @example
   * // Count the number of Porudzbinas
   * const count = await prisma.porudzbina.count({
   *   where: {
   *     // ... the filter for the Porudzbinas we want to count
   *   }
   * })
  **/
  count<T extends porudzbinaCountArgs>(
    args?: Prisma.Subset<T, porudzbinaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PorudzbinaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Porudzbina.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PorudzbinaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PorudzbinaAggregateArgs>(args: Prisma.Subset<T, PorudzbinaAggregateArgs>): Prisma.PrismaPromise<GetPorudzbinaAggregateType<T>>

  /**
   * Group by Porudzbina.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {porudzbinaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends porudzbinaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: porudzbinaGroupByArgs['orderBy'] }
      : { orderBy?: porudzbinaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, porudzbinaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPorudzbinaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the porudzbina model
 */
readonly fields: porudzbinaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for porudzbina.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__porudzbinaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dodata<T extends Prisma.porudzbina$dodataArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.porudzbina$dodataArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dodataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  korisnik<T extends Prisma.korisnikDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.korisnikDefaultArgs<ExtArgs>>): Prisma.Prisma__korisnikClient<runtime.Types.Result.GetResult<Prisma.$korisnikPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the porudzbina model
 */
export interface porudzbinaFieldRefs {
  readonly broj_racuna: Prisma.FieldRef<"porudzbina", 'Int'>
  readonly datum: Prisma.FieldRef<"porudzbina", 'DateTime'>
  readonly iznos: Prisma.FieldRef<"porudzbina", 'Decimal'>
  readonly korisnik_id: Prisma.FieldRef<"porudzbina", 'Int'>
}
    

// Custom InputTypes
/**
 * porudzbina findUnique
 */
export type porudzbinaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
  /**
   * Filter, which porudzbina to fetch.
   */
  where: Prisma.porudzbinaWhereUniqueInput
}

/**
 * porudzbina findUniqueOrThrow
 */
export type porudzbinaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
  /**
   * Filter, which porudzbina to fetch.
   */
  where: Prisma.porudzbinaWhereUniqueInput
}

/**
 * porudzbina findFirst
 */
export type porudzbinaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
  /**
   * Filter, which porudzbina to fetch.
   */
  where?: Prisma.porudzbinaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of porudzbinas to fetch.
   */
  orderBy?: Prisma.porudzbinaOrderByWithRelationInput | Prisma.porudzbinaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for porudzbinas.
   */
  cursor?: Prisma.porudzbinaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` porudzbinas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` porudzbinas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of porudzbinas.
   */
  distinct?: Prisma.PorudzbinaScalarFieldEnum | Prisma.PorudzbinaScalarFieldEnum[]
}

/**
 * porudzbina findFirstOrThrow
 */
export type porudzbinaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
  /**
   * Filter, which porudzbina to fetch.
   */
  where?: Prisma.porudzbinaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of porudzbinas to fetch.
   */
  orderBy?: Prisma.porudzbinaOrderByWithRelationInput | Prisma.porudzbinaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for porudzbinas.
   */
  cursor?: Prisma.porudzbinaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` porudzbinas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` porudzbinas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of porudzbinas.
   */
  distinct?: Prisma.PorudzbinaScalarFieldEnum | Prisma.PorudzbinaScalarFieldEnum[]
}

/**
 * porudzbina findMany
 */
export type porudzbinaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
  /**
   * Filter, which porudzbinas to fetch.
   */
  where?: Prisma.porudzbinaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of porudzbinas to fetch.
   */
  orderBy?: Prisma.porudzbinaOrderByWithRelationInput | Prisma.porudzbinaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing porudzbinas.
   */
  cursor?: Prisma.porudzbinaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` porudzbinas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` porudzbinas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of porudzbinas.
   */
  distinct?: Prisma.PorudzbinaScalarFieldEnum | Prisma.PorudzbinaScalarFieldEnum[]
}

/**
 * porudzbina create
 */
export type porudzbinaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
  /**
   * The data needed to create a porudzbina.
   */
  data: Prisma.XOR<Prisma.porudzbinaCreateInput, Prisma.porudzbinaUncheckedCreateInput>
}

/**
 * porudzbina createMany
 */
export type porudzbinaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many porudzbinas.
   */
  data: Prisma.porudzbinaCreateManyInput | Prisma.porudzbinaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * porudzbina update
 */
export type porudzbinaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
  /**
   * The data needed to update a porudzbina.
   */
  data: Prisma.XOR<Prisma.porudzbinaUpdateInput, Prisma.porudzbinaUncheckedUpdateInput>
  /**
   * Choose, which porudzbina to update.
   */
  where: Prisma.porudzbinaWhereUniqueInput
}

/**
 * porudzbina updateMany
 */
export type porudzbinaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update porudzbinas.
   */
  data: Prisma.XOR<Prisma.porudzbinaUpdateManyMutationInput, Prisma.porudzbinaUncheckedUpdateManyInput>
  /**
   * Filter which porudzbinas to update
   */
  where?: Prisma.porudzbinaWhereInput
  /**
   * Limit how many porudzbinas to update.
   */
  limit?: number
}

/**
 * porudzbina upsert
 */
export type porudzbinaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
  /**
   * The filter to search for the porudzbina to update in case it exists.
   */
  where: Prisma.porudzbinaWhereUniqueInput
  /**
   * In case the porudzbina found by the `where` argument doesn't exist, create a new porudzbina with this data.
   */
  create: Prisma.XOR<Prisma.porudzbinaCreateInput, Prisma.porudzbinaUncheckedCreateInput>
  /**
   * In case the porudzbina was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.porudzbinaUpdateInput, Prisma.porudzbinaUncheckedUpdateInput>
}

/**
 * porudzbina delete
 */
export type porudzbinaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
  /**
   * Filter which porudzbina to delete.
   */
  where: Prisma.porudzbinaWhereUniqueInput
}

/**
 * porudzbina deleteMany
 */
export type porudzbinaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which porudzbinas to delete
   */
  where?: Prisma.porudzbinaWhereInput
  /**
   * Limit how many porudzbinas to delete.
   */
  limit?: number
}

/**
 * porudzbina.dodata
 */
export type porudzbina$dodataArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dodata
   */
  select?: Prisma.dodataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dodata
   */
  omit?: Prisma.dodataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dodataInclude<ExtArgs> | null
  where?: Prisma.dodataWhereInput
  orderBy?: Prisma.dodataOrderByWithRelationInput | Prisma.dodataOrderByWithRelationInput[]
  cursor?: Prisma.dodataWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DodataScalarFieldEnum | Prisma.DodataScalarFieldEnum[]
}

/**
 * porudzbina without action
 */
export type porudzbinaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the porudzbina
   */
  select?: Prisma.porudzbinaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the porudzbina
   */
  omit?: Prisma.porudzbinaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.porudzbinaInclude<ExtArgs> | null
}
