
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `slika_uzorak` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model slika_uzorak
 * 
 */
export type slika_uzorakModel = runtime.Types.Result.DefaultSelection<Prisma.$slika_uzorakPayload>

export type AggregateSlika_uzorak = {
  _count: Slika_uzorakCountAggregateOutputType | null
  _avg: Slika_uzorakAvgAggregateOutputType | null
  _sum: Slika_uzorakSumAggregateOutputType | null
  _min: Slika_uzorakMinAggregateOutputType | null
  _max: Slika_uzorakMaxAggregateOutputType | null
}

export type Slika_uzorakAvgAggregateOutputType = {
  slika_id: number | null
}

export type Slika_uzorakSumAggregateOutputType = {
  slika_id: number | null
}

export type Slika_uzorakMinAggregateOutputType = {
  slika_id: number | null
  naziv_slike: string | null
  link_slike: string | null
  isbn: string | null
}

export type Slika_uzorakMaxAggregateOutputType = {
  slika_id: number | null
  naziv_slike: string | null
  link_slike: string | null
  isbn: string | null
}

export type Slika_uzorakCountAggregateOutputType = {
  slika_id: number
  naziv_slike: number
  link_slike: number
  isbn: number
  _all: number
}


export type Slika_uzorakAvgAggregateInputType = {
  slika_id?: true
}

export type Slika_uzorakSumAggregateInputType = {
  slika_id?: true
}

export type Slika_uzorakMinAggregateInputType = {
  slika_id?: true
  naziv_slike?: true
  link_slike?: true
  isbn?: true
}

export type Slika_uzorakMaxAggregateInputType = {
  slika_id?: true
  naziv_slike?: true
  link_slike?: true
  isbn?: true
}

export type Slika_uzorakCountAggregateInputType = {
  slika_id?: true
  naziv_slike?: true
  link_slike?: true
  isbn?: true
  _all?: true
}

export type Slika_uzorakAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which slika_uzorak to aggregate.
   */
  where?: Prisma.slika_uzorakWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of slika_uzoraks to fetch.
   */
  orderBy?: Prisma.slika_uzorakOrderByWithRelationInput | Prisma.slika_uzorakOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.slika_uzorakWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` slika_uzoraks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` slika_uzoraks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned slika_uzoraks
  **/
  _count?: true | Slika_uzorakCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Slika_uzorakAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Slika_uzorakSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Slika_uzorakMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Slika_uzorakMaxAggregateInputType
}

export type GetSlika_uzorakAggregateType<T extends Slika_uzorakAggregateArgs> = {
      [P in keyof T & keyof AggregateSlika_uzorak]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSlika_uzorak[P]>
    : Prisma.GetScalarType<T[P], AggregateSlika_uzorak[P]>
}




export type slika_uzorakGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.slika_uzorakWhereInput
  orderBy?: Prisma.slika_uzorakOrderByWithAggregationInput | Prisma.slika_uzorakOrderByWithAggregationInput[]
  by: Prisma.Slika_uzorakScalarFieldEnum[] | Prisma.Slika_uzorakScalarFieldEnum
  having?: Prisma.slika_uzorakScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Slika_uzorakCountAggregateInputType | true
  _avg?: Slika_uzorakAvgAggregateInputType
  _sum?: Slika_uzorakSumAggregateInputType
  _min?: Slika_uzorakMinAggregateInputType
  _max?: Slika_uzorakMaxAggregateInputType
}

export type Slika_uzorakGroupByOutputType = {
  slika_id: number
  naziv_slike: string | null
  link_slike: string
  isbn: string
  _count: Slika_uzorakCountAggregateOutputType | null
  _avg: Slika_uzorakAvgAggregateOutputType | null
  _sum: Slika_uzorakSumAggregateOutputType | null
  _min: Slika_uzorakMinAggregateOutputType | null
  _max: Slika_uzorakMaxAggregateOutputType | null
}

export type GetSlika_uzorakGroupByPayload<T extends slika_uzorakGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Slika_uzorakGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Slika_uzorakGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Slika_uzorakGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Slika_uzorakGroupByOutputType[P]>
      }
    >
  >



export type slika_uzorakWhereInput = {
  AND?: Prisma.slika_uzorakWhereInput | Prisma.slika_uzorakWhereInput[]
  OR?: Prisma.slika_uzorakWhereInput[]
  NOT?: Prisma.slika_uzorakWhereInput | Prisma.slika_uzorakWhereInput[]
  slika_id?: Prisma.IntFilter<"slika_uzorak"> | number
  naziv_slike?: Prisma.StringNullableFilter<"slika_uzorak"> | string | null
  link_slike?: Prisma.StringFilter<"slika_uzorak"> | string
  isbn?: Prisma.StringFilter<"slika_uzorak"> | string
  knjiga?: Prisma.XOR<Prisma.KnjigaScalarRelationFilter, Prisma.knjigaWhereInput>
}

export type slika_uzorakOrderByWithRelationInput = {
  slika_id?: Prisma.SortOrder
  naziv_slike?: Prisma.SortOrderInput | Prisma.SortOrder
  link_slike?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
  knjiga?: Prisma.knjigaOrderByWithRelationInput
  _relevance?: Prisma.slika_uzorakOrderByRelevanceInput
}

export type slika_uzorakWhereUniqueInput = Prisma.AtLeast<{
  slika_id?: number
  AND?: Prisma.slika_uzorakWhereInput | Prisma.slika_uzorakWhereInput[]
  OR?: Prisma.slika_uzorakWhereInput[]
  NOT?: Prisma.slika_uzorakWhereInput | Prisma.slika_uzorakWhereInput[]
  naziv_slike?: Prisma.StringNullableFilter<"slika_uzorak"> | string | null
  link_slike?: Prisma.StringFilter<"slika_uzorak"> | string
  isbn?: Prisma.StringFilter<"slika_uzorak"> | string
  knjiga?: Prisma.XOR<Prisma.KnjigaScalarRelationFilter, Prisma.knjigaWhereInput>
}, "slika_id">

export type slika_uzorakOrderByWithAggregationInput = {
  slika_id?: Prisma.SortOrder
  naziv_slike?: Prisma.SortOrderInput | Prisma.SortOrder
  link_slike?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
  _count?: Prisma.slika_uzorakCountOrderByAggregateInput
  _avg?: Prisma.slika_uzorakAvgOrderByAggregateInput
  _max?: Prisma.slika_uzorakMaxOrderByAggregateInput
  _min?: Prisma.slika_uzorakMinOrderByAggregateInput
  _sum?: Prisma.slika_uzorakSumOrderByAggregateInput
}

export type slika_uzorakScalarWhereWithAggregatesInput = {
  AND?: Prisma.slika_uzorakScalarWhereWithAggregatesInput | Prisma.slika_uzorakScalarWhereWithAggregatesInput[]
  OR?: Prisma.slika_uzorakScalarWhereWithAggregatesInput[]
  NOT?: Prisma.slika_uzorakScalarWhereWithAggregatesInput | Prisma.slika_uzorakScalarWhereWithAggregatesInput[]
  slika_id?: Prisma.IntWithAggregatesFilter<"slika_uzorak"> | number
  naziv_slike?: Prisma.StringNullableWithAggregatesFilter<"slika_uzorak"> | string | null
  link_slike?: Prisma.StringWithAggregatesFilter<"slika_uzorak"> | string
  isbn?: Prisma.StringWithAggregatesFilter<"slika_uzorak"> | string
}

export type slika_uzorakCreateInput = {
  naziv_slike?: string | null
  link_slike: string
  knjiga: Prisma.knjigaCreateNestedOneWithoutSlika_uzorakInput
}

export type slika_uzorakUncheckedCreateInput = {
  slika_id?: number
  naziv_slike?: string | null
  link_slike: string
  isbn: string
}

export type slika_uzorakUpdateInput = {
  naziv_slike?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  link_slike?: Prisma.StringFieldUpdateOperationsInput | string
  knjiga?: Prisma.knjigaUpdateOneRequiredWithoutSlika_uzorakNestedInput
}

export type slika_uzorakUncheckedUpdateInput = {
  slika_id?: Prisma.IntFieldUpdateOperationsInput | number
  naziv_slike?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  link_slike?: Prisma.StringFieldUpdateOperationsInput | string
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
}

export type slika_uzorakCreateManyInput = {
  slika_id?: number
  naziv_slike?: string | null
  link_slike: string
  isbn: string
}

export type slika_uzorakUpdateManyMutationInput = {
  naziv_slike?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  link_slike?: Prisma.StringFieldUpdateOperationsInput | string
}

export type slika_uzorakUncheckedUpdateManyInput = {
  slika_id?: Prisma.IntFieldUpdateOperationsInput | number
  naziv_slike?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  link_slike?: Prisma.StringFieldUpdateOperationsInput | string
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Slika_uzorakListRelationFilter = {
  every?: Prisma.slika_uzorakWhereInput
  some?: Prisma.slika_uzorakWhereInput
  none?: Prisma.slika_uzorakWhereInput
}

export type slika_uzorakOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type slika_uzorakOrderByRelevanceInput = {
  fields: Prisma.slika_uzorakOrderByRelevanceFieldEnum | Prisma.slika_uzorakOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type slika_uzorakCountOrderByAggregateInput = {
  slika_id?: Prisma.SortOrder
  naziv_slike?: Prisma.SortOrder
  link_slike?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
}

export type slika_uzorakAvgOrderByAggregateInput = {
  slika_id?: Prisma.SortOrder
}

export type slika_uzorakMaxOrderByAggregateInput = {
  slika_id?: Prisma.SortOrder
  naziv_slike?: Prisma.SortOrder
  link_slike?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
}

export type slika_uzorakMinOrderByAggregateInput = {
  slika_id?: Prisma.SortOrder
  naziv_slike?: Prisma.SortOrder
  link_slike?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
}

export type slika_uzorakSumOrderByAggregateInput = {
  slika_id?: Prisma.SortOrder
}

export type slika_uzorakCreateNestedManyWithoutKnjigaInput = {
  create?: Prisma.XOR<Prisma.slika_uzorakCreateWithoutKnjigaInput, Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput> | Prisma.slika_uzorakCreateWithoutKnjigaInput[] | Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput[]
  connectOrCreate?: Prisma.slika_uzorakCreateOrConnectWithoutKnjigaInput | Prisma.slika_uzorakCreateOrConnectWithoutKnjigaInput[]
  createMany?: Prisma.slika_uzorakCreateManyKnjigaInputEnvelope
  connect?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
}

export type slika_uzorakUncheckedCreateNestedManyWithoutKnjigaInput = {
  create?: Prisma.XOR<Prisma.slika_uzorakCreateWithoutKnjigaInput, Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput> | Prisma.slika_uzorakCreateWithoutKnjigaInput[] | Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput[]
  connectOrCreate?: Prisma.slika_uzorakCreateOrConnectWithoutKnjigaInput | Prisma.slika_uzorakCreateOrConnectWithoutKnjigaInput[]
  createMany?: Prisma.slika_uzorakCreateManyKnjigaInputEnvelope
  connect?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
}

export type slika_uzorakUpdateManyWithoutKnjigaNestedInput = {
  create?: Prisma.XOR<Prisma.slika_uzorakCreateWithoutKnjigaInput, Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput> | Prisma.slika_uzorakCreateWithoutKnjigaInput[] | Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput[]
  connectOrCreate?: Prisma.slika_uzorakCreateOrConnectWithoutKnjigaInput | Prisma.slika_uzorakCreateOrConnectWithoutKnjigaInput[]
  upsert?: Prisma.slika_uzorakUpsertWithWhereUniqueWithoutKnjigaInput | Prisma.slika_uzorakUpsertWithWhereUniqueWithoutKnjigaInput[]
  createMany?: Prisma.slika_uzorakCreateManyKnjigaInputEnvelope
  set?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
  disconnect?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
  delete?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
  connect?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
  update?: Prisma.slika_uzorakUpdateWithWhereUniqueWithoutKnjigaInput | Prisma.slika_uzorakUpdateWithWhereUniqueWithoutKnjigaInput[]
  updateMany?: Prisma.slika_uzorakUpdateManyWithWhereWithoutKnjigaInput | Prisma.slika_uzorakUpdateManyWithWhereWithoutKnjigaInput[]
  deleteMany?: Prisma.slika_uzorakScalarWhereInput | Prisma.slika_uzorakScalarWhereInput[]
}

export type slika_uzorakUncheckedUpdateManyWithoutKnjigaNestedInput = {
  create?: Prisma.XOR<Prisma.slika_uzorakCreateWithoutKnjigaInput, Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput> | Prisma.slika_uzorakCreateWithoutKnjigaInput[] | Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput[]
  connectOrCreate?: Prisma.slika_uzorakCreateOrConnectWithoutKnjigaInput | Prisma.slika_uzorakCreateOrConnectWithoutKnjigaInput[]
  upsert?: Prisma.slika_uzorakUpsertWithWhereUniqueWithoutKnjigaInput | Prisma.slika_uzorakUpsertWithWhereUniqueWithoutKnjigaInput[]
  createMany?: Prisma.slika_uzorakCreateManyKnjigaInputEnvelope
  set?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
  disconnect?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
  delete?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
  connect?: Prisma.slika_uzorakWhereUniqueInput | Prisma.slika_uzorakWhereUniqueInput[]
  update?: Prisma.slika_uzorakUpdateWithWhereUniqueWithoutKnjigaInput | Prisma.slika_uzorakUpdateWithWhereUniqueWithoutKnjigaInput[]
  updateMany?: Prisma.slika_uzorakUpdateManyWithWhereWithoutKnjigaInput | Prisma.slika_uzorakUpdateManyWithWhereWithoutKnjigaInput[]
  deleteMany?: Prisma.slika_uzorakScalarWhereInput | Prisma.slika_uzorakScalarWhereInput[]
}

export type slika_uzorakCreateWithoutKnjigaInput = {
  naziv_slike?: string | null
  link_slike: string
}

export type slika_uzorakUncheckedCreateWithoutKnjigaInput = {
  slika_id?: number
  naziv_slike?: string | null
  link_slike: string
}

export type slika_uzorakCreateOrConnectWithoutKnjigaInput = {
  where: Prisma.slika_uzorakWhereUniqueInput
  create: Prisma.XOR<Prisma.slika_uzorakCreateWithoutKnjigaInput, Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput>
}

export type slika_uzorakCreateManyKnjigaInputEnvelope = {
  data: Prisma.slika_uzorakCreateManyKnjigaInput | Prisma.slika_uzorakCreateManyKnjigaInput[]
  skipDuplicates?: boolean
}

export type slika_uzorakUpsertWithWhereUniqueWithoutKnjigaInput = {
  where: Prisma.slika_uzorakWhereUniqueInput
  update: Prisma.XOR<Prisma.slika_uzorakUpdateWithoutKnjigaInput, Prisma.slika_uzorakUncheckedUpdateWithoutKnjigaInput>
  create: Prisma.XOR<Prisma.slika_uzorakCreateWithoutKnjigaInput, Prisma.slika_uzorakUncheckedCreateWithoutKnjigaInput>
}

export type slika_uzorakUpdateWithWhereUniqueWithoutKnjigaInput = {
  where: Prisma.slika_uzorakWhereUniqueInput
  data: Prisma.XOR<Prisma.slika_uzorakUpdateWithoutKnjigaInput, Prisma.slika_uzorakUncheckedUpdateWithoutKnjigaInput>
}

export type slika_uzorakUpdateManyWithWhereWithoutKnjigaInput = {
  where: Prisma.slika_uzorakScalarWhereInput
  data: Prisma.XOR<Prisma.slika_uzorakUpdateManyMutationInput, Prisma.slika_uzorakUncheckedUpdateManyWithoutKnjigaInput>
}

export type slika_uzorakScalarWhereInput = {
  AND?: Prisma.slika_uzorakScalarWhereInput | Prisma.slika_uzorakScalarWhereInput[]
  OR?: Prisma.slika_uzorakScalarWhereInput[]
  NOT?: Prisma.slika_uzorakScalarWhereInput | Prisma.slika_uzorakScalarWhereInput[]
  slika_id?: Prisma.IntFilter<"slika_uzorak"> | number
  naziv_slike?: Prisma.StringNullableFilter<"slika_uzorak"> | string | null
  link_slike?: Prisma.StringFilter<"slika_uzorak"> | string
  isbn?: Prisma.StringFilter<"slika_uzorak"> | string
}

export type slika_uzorakCreateManyKnjigaInput = {
  slika_id?: number
  naziv_slike?: string | null
  link_slike: string
}

export type slika_uzorakUpdateWithoutKnjigaInput = {
  naziv_slike?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  link_slike?: Prisma.StringFieldUpdateOperationsInput | string
}

export type slika_uzorakUncheckedUpdateWithoutKnjigaInput = {
  slika_id?: Prisma.IntFieldUpdateOperationsInput | number
  naziv_slike?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  link_slike?: Prisma.StringFieldUpdateOperationsInput | string
}

export type slika_uzorakUncheckedUpdateManyWithoutKnjigaInput = {
  slika_id?: Prisma.IntFieldUpdateOperationsInput | number
  naziv_slike?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  link_slike?: Prisma.StringFieldUpdateOperationsInput | string
}



export type slika_uzorakSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  slika_id?: boolean
  naziv_slike?: boolean
  link_slike?: boolean
  isbn?: boolean
  knjiga?: boolean | Prisma.knjigaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["slika_uzorak"]>



export type slika_uzorakSelectScalar = {
  slika_id?: boolean
  naziv_slike?: boolean
  link_slike?: boolean
  isbn?: boolean
}

export type slika_uzorakOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"slika_id" | "naziv_slike" | "link_slike" | "isbn", ExtArgs["result"]["slika_uzorak"]>
export type slika_uzorakInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  knjiga?: boolean | Prisma.knjigaDefaultArgs<ExtArgs>
}

export type $slika_uzorakPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "slika_uzorak"
  objects: {
    knjiga: Prisma.$knjigaPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    slika_id: number
    naziv_slike: string | null
    link_slike: string
    isbn: string
  }, ExtArgs["result"]["slika_uzorak"]>
  composites: {}
}

export type slika_uzorakGetPayload<S extends boolean | null | undefined | slika_uzorakDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload, S>

export type slika_uzorakCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<slika_uzorakFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Slika_uzorakCountAggregateInputType | true
  }

export interface slika_uzorakDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['slika_uzorak'], meta: { name: 'slika_uzorak' } }
  /**
   * Find zero or one Slika_uzorak that matches the filter.
   * @param {slika_uzorakFindUniqueArgs} args - Arguments to find a Slika_uzorak
   * @example
   * // Get one Slika_uzorak
   * const slika_uzorak = await prisma.slika_uzorak.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends slika_uzorakFindUniqueArgs>(args: Prisma.SelectSubset<T, slika_uzorakFindUniqueArgs<ExtArgs>>): Prisma.Prisma__slika_uzorakClient<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Slika_uzorak that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {slika_uzorakFindUniqueOrThrowArgs} args - Arguments to find a Slika_uzorak
   * @example
   * // Get one Slika_uzorak
   * const slika_uzorak = await prisma.slika_uzorak.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends slika_uzorakFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, slika_uzorakFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__slika_uzorakClient<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Slika_uzorak that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {slika_uzorakFindFirstArgs} args - Arguments to find a Slika_uzorak
   * @example
   * // Get one Slika_uzorak
   * const slika_uzorak = await prisma.slika_uzorak.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends slika_uzorakFindFirstArgs>(args?: Prisma.SelectSubset<T, slika_uzorakFindFirstArgs<ExtArgs>>): Prisma.Prisma__slika_uzorakClient<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Slika_uzorak that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {slika_uzorakFindFirstOrThrowArgs} args - Arguments to find a Slika_uzorak
   * @example
   * // Get one Slika_uzorak
   * const slika_uzorak = await prisma.slika_uzorak.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends slika_uzorakFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, slika_uzorakFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__slika_uzorakClient<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Slika_uzoraks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {slika_uzorakFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Slika_uzoraks
   * const slika_uzoraks = await prisma.slika_uzorak.findMany()
   * 
   * // Get first 10 Slika_uzoraks
   * const slika_uzoraks = await prisma.slika_uzorak.findMany({ take: 10 })
   * 
   * // Only select the `slika_id`
   * const slika_uzorakWithSlika_idOnly = await prisma.slika_uzorak.findMany({ select: { slika_id: true } })
   * 
   */
  findMany<T extends slika_uzorakFindManyArgs>(args?: Prisma.SelectSubset<T, slika_uzorakFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Slika_uzorak.
   * @param {slika_uzorakCreateArgs} args - Arguments to create a Slika_uzorak.
   * @example
   * // Create one Slika_uzorak
   * const Slika_uzorak = await prisma.slika_uzorak.create({
   *   data: {
   *     // ... data to create a Slika_uzorak
   *   }
   * })
   * 
   */
  create<T extends slika_uzorakCreateArgs>(args: Prisma.SelectSubset<T, slika_uzorakCreateArgs<ExtArgs>>): Prisma.Prisma__slika_uzorakClient<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Slika_uzoraks.
   * @param {slika_uzorakCreateManyArgs} args - Arguments to create many Slika_uzoraks.
   * @example
   * // Create many Slika_uzoraks
   * const slika_uzorak = await prisma.slika_uzorak.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends slika_uzorakCreateManyArgs>(args?: Prisma.SelectSubset<T, slika_uzorakCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Slika_uzorak.
   * @param {slika_uzorakDeleteArgs} args - Arguments to delete one Slika_uzorak.
   * @example
   * // Delete one Slika_uzorak
   * const Slika_uzorak = await prisma.slika_uzorak.delete({
   *   where: {
   *     // ... filter to delete one Slika_uzorak
   *   }
   * })
   * 
   */
  delete<T extends slika_uzorakDeleteArgs>(args: Prisma.SelectSubset<T, slika_uzorakDeleteArgs<ExtArgs>>): Prisma.Prisma__slika_uzorakClient<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Slika_uzorak.
   * @param {slika_uzorakUpdateArgs} args - Arguments to update one Slika_uzorak.
   * @example
   * // Update one Slika_uzorak
   * const slika_uzorak = await prisma.slika_uzorak.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends slika_uzorakUpdateArgs>(args: Prisma.SelectSubset<T, slika_uzorakUpdateArgs<ExtArgs>>): Prisma.Prisma__slika_uzorakClient<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Slika_uzoraks.
   * @param {slika_uzorakDeleteManyArgs} args - Arguments to filter Slika_uzoraks to delete.
   * @example
   * // Delete a few Slika_uzoraks
   * const { count } = await prisma.slika_uzorak.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends slika_uzorakDeleteManyArgs>(args?: Prisma.SelectSubset<T, slika_uzorakDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Slika_uzoraks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {slika_uzorakUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Slika_uzoraks
   * const slika_uzorak = await prisma.slika_uzorak.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends slika_uzorakUpdateManyArgs>(args: Prisma.SelectSubset<T, slika_uzorakUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Slika_uzorak.
   * @param {slika_uzorakUpsertArgs} args - Arguments to update or create a Slika_uzorak.
   * @example
   * // Update or create a Slika_uzorak
   * const slika_uzorak = await prisma.slika_uzorak.upsert({
   *   create: {
   *     // ... data to create a Slika_uzorak
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Slika_uzorak we want to update
   *   }
   * })
   */
  upsert<T extends slika_uzorakUpsertArgs>(args: Prisma.SelectSubset<T, slika_uzorakUpsertArgs<ExtArgs>>): Prisma.Prisma__slika_uzorakClient<runtime.Types.Result.GetResult<Prisma.$slika_uzorakPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Slika_uzoraks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {slika_uzorakCountArgs} args - Arguments to filter Slika_uzoraks to count.
   * @example
   * // Count the number of Slika_uzoraks
   * const count = await prisma.slika_uzorak.count({
   *   where: {
   *     // ... the filter for the Slika_uzoraks we want to count
   *   }
   * })
  **/
  count<T extends slika_uzorakCountArgs>(
    args?: Prisma.Subset<T, slika_uzorakCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Slika_uzorakCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Slika_uzorak.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Slika_uzorakAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Slika_uzorakAggregateArgs>(args: Prisma.Subset<T, Slika_uzorakAggregateArgs>): Prisma.PrismaPromise<GetSlika_uzorakAggregateType<T>>

  /**
   * Group by Slika_uzorak.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {slika_uzorakGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends slika_uzorakGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: slika_uzorakGroupByArgs['orderBy'] }
      : { orderBy?: slika_uzorakGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, slika_uzorakGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSlika_uzorakGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the slika_uzorak model
 */
readonly fields: slika_uzorakFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for slika_uzorak.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__slika_uzorakClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  knjiga<T extends Prisma.knjigaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.knjigaDefaultArgs<ExtArgs>>): Prisma.Prisma__knjigaClient<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the slika_uzorak model
 */
export interface slika_uzorakFieldRefs {
  readonly slika_id: Prisma.FieldRef<"slika_uzorak", 'Int'>
  readonly naziv_slike: Prisma.FieldRef<"slika_uzorak", 'String'>
  readonly link_slike: Prisma.FieldRef<"slika_uzorak", 'String'>
  readonly isbn: Prisma.FieldRef<"slika_uzorak", 'String'>
}
    

// Custom InputTypes
/**
 * slika_uzorak findUnique
 */
export type slika_uzorakFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  /**
   * Filter, which slika_uzorak to fetch.
   */
  where: Prisma.slika_uzorakWhereUniqueInput
}

/**
 * slika_uzorak findUniqueOrThrow
 */
export type slika_uzorakFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  /**
   * Filter, which slika_uzorak to fetch.
   */
  where: Prisma.slika_uzorakWhereUniqueInput
}

/**
 * slika_uzorak findFirst
 */
export type slika_uzorakFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  /**
   * Filter, which slika_uzorak to fetch.
   */
  where?: Prisma.slika_uzorakWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of slika_uzoraks to fetch.
   */
  orderBy?: Prisma.slika_uzorakOrderByWithRelationInput | Prisma.slika_uzorakOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for slika_uzoraks.
   */
  cursor?: Prisma.slika_uzorakWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` slika_uzoraks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` slika_uzoraks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of slika_uzoraks.
   */
  distinct?: Prisma.Slika_uzorakScalarFieldEnum | Prisma.Slika_uzorakScalarFieldEnum[]
}

/**
 * slika_uzorak findFirstOrThrow
 */
export type slika_uzorakFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  /**
   * Filter, which slika_uzorak to fetch.
   */
  where?: Prisma.slika_uzorakWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of slika_uzoraks to fetch.
   */
  orderBy?: Prisma.slika_uzorakOrderByWithRelationInput | Prisma.slika_uzorakOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for slika_uzoraks.
   */
  cursor?: Prisma.slika_uzorakWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` slika_uzoraks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` slika_uzoraks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of slika_uzoraks.
   */
  distinct?: Prisma.Slika_uzorakScalarFieldEnum | Prisma.Slika_uzorakScalarFieldEnum[]
}

/**
 * slika_uzorak findMany
 */
export type slika_uzorakFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  /**
   * Filter, which slika_uzoraks to fetch.
   */
  where?: Prisma.slika_uzorakWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of slika_uzoraks to fetch.
   */
  orderBy?: Prisma.slika_uzorakOrderByWithRelationInput | Prisma.slika_uzorakOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing slika_uzoraks.
   */
  cursor?: Prisma.slika_uzorakWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` slika_uzoraks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` slika_uzoraks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of slika_uzoraks.
   */
  distinct?: Prisma.Slika_uzorakScalarFieldEnum | Prisma.Slika_uzorakScalarFieldEnum[]
}

/**
 * slika_uzorak create
 */
export type slika_uzorakCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  /**
   * The data needed to create a slika_uzorak.
   */
  data: Prisma.XOR<Prisma.slika_uzorakCreateInput, Prisma.slika_uzorakUncheckedCreateInput>
}

/**
 * slika_uzorak createMany
 */
export type slika_uzorakCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many slika_uzoraks.
   */
  data: Prisma.slika_uzorakCreateManyInput | Prisma.slika_uzorakCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * slika_uzorak update
 */
export type slika_uzorakUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  /**
   * The data needed to update a slika_uzorak.
   */
  data: Prisma.XOR<Prisma.slika_uzorakUpdateInput, Prisma.slika_uzorakUncheckedUpdateInput>
  /**
   * Choose, which slika_uzorak to update.
   */
  where: Prisma.slika_uzorakWhereUniqueInput
}

/**
 * slika_uzorak updateMany
 */
export type slika_uzorakUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update slika_uzoraks.
   */
  data: Prisma.XOR<Prisma.slika_uzorakUpdateManyMutationInput, Prisma.slika_uzorakUncheckedUpdateManyInput>
  /**
   * Filter which slika_uzoraks to update
   */
  where?: Prisma.slika_uzorakWhereInput
  /**
   * Limit how many slika_uzoraks to update.
   */
  limit?: number
}

/**
 * slika_uzorak upsert
 */
export type slika_uzorakUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  /**
   * The filter to search for the slika_uzorak to update in case it exists.
   */
  where: Prisma.slika_uzorakWhereUniqueInput
  /**
   * In case the slika_uzorak found by the `where` argument doesn't exist, create a new slika_uzorak with this data.
   */
  create: Prisma.XOR<Prisma.slika_uzorakCreateInput, Prisma.slika_uzorakUncheckedCreateInput>
  /**
   * In case the slika_uzorak was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.slika_uzorakUpdateInput, Prisma.slika_uzorakUncheckedUpdateInput>
}

/**
 * slika_uzorak delete
 */
export type slika_uzorakDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
  /**
   * Filter which slika_uzorak to delete.
   */
  where: Prisma.slika_uzorakWhereUniqueInput
}

/**
 * slika_uzorak deleteMany
 */
export type slika_uzorakDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which slika_uzoraks to delete
   */
  where?: Prisma.slika_uzorakWhereInput
  /**
   * Limit how many slika_uzoraks to delete.
   */
  limit?: number
}

/**
 * slika_uzorak without action
 */
export type slika_uzorakDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the slika_uzorak
   */
  select?: Prisma.slika_uzorakSelect<ExtArgs> | null
  /**
   * Omit specific fields from the slika_uzorak
   */
  omit?: Prisma.slika_uzorakOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.slika_uzorakInclude<ExtArgs> | null
}
