
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `zanr` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model zanr
 * 
 */
export type zanrModel = runtime.Types.Result.DefaultSelection<Prisma.$zanrPayload>

export type AggregateZanr = {
  _count: ZanrCountAggregateOutputType | null
  _avg: ZanrAvgAggregateOutputType | null
  _sum: ZanrSumAggregateOutputType | null
  _min: ZanrMinAggregateOutputType | null
  _max: ZanrMaxAggregateOutputType | null
}

export type ZanrAvgAggregateOutputType = {
  zanr_id: number | null
}

export type ZanrSumAggregateOutputType = {
  zanr_id: number | null
}

export type ZanrMinAggregateOutputType = {
  zanr_id: number | null
  naziv_zanra: string | null
}

export type ZanrMaxAggregateOutputType = {
  zanr_id: number | null
  naziv_zanra: string | null
}

export type ZanrCountAggregateOutputType = {
  zanr_id: number
  naziv_zanra: number
  _all: number
}


export type ZanrAvgAggregateInputType = {
  zanr_id?: true
}

export type ZanrSumAggregateInputType = {
  zanr_id?: true
}

export type ZanrMinAggregateInputType = {
  zanr_id?: true
  naziv_zanra?: true
}

export type ZanrMaxAggregateInputType = {
  zanr_id?: true
  naziv_zanra?: true
}

export type ZanrCountAggregateInputType = {
  zanr_id?: true
  naziv_zanra?: true
  _all?: true
}

export type ZanrAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which zanr to aggregate.
   */
  where?: Prisma.zanrWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of zanrs to fetch.
   */
  orderBy?: Prisma.zanrOrderByWithRelationInput | Prisma.zanrOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.zanrWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` zanrs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` zanrs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned zanrs
  **/
  _count?: true | ZanrCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ZanrAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ZanrSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ZanrMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ZanrMaxAggregateInputType
}

export type GetZanrAggregateType<T extends ZanrAggregateArgs> = {
      [P in keyof T & keyof AggregateZanr]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateZanr[P]>
    : Prisma.GetScalarType<T[P], AggregateZanr[P]>
}




export type zanrGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.zanrWhereInput
  orderBy?: Prisma.zanrOrderByWithAggregationInput | Prisma.zanrOrderByWithAggregationInput[]
  by: Prisma.ZanrScalarFieldEnum[] | Prisma.ZanrScalarFieldEnum
  having?: Prisma.zanrScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ZanrCountAggregateInputType | true
  _avg?: ZanrAvgAggregateInputType
  _sum?: ZanrSumAggregateInputType
  _min?: ZanrMinAggregateInputType
  _max?: ZanrMaxAggregateInputType
}

export type ZanrGroupByOutputType = {
  zanr_id: number
  naziv_zanra: string
  _count: ZanrCountAggregateOutputType | null
  _avg: ZanrAvgAggregateOutputType | null
  _sum: ZanrSumAggregateOutputType | null
  _min: ZanrMinAggregateOutputType | null
  _max: ZanrMaxAggregateOutputType | null
}

export type GetZanrGroupByPayload<T extends zanrGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ZanrGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ZanrGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ZanrGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ZanrGroupByOutputType[P]>
      }
    >
  >



export type zanrWhereInput = {
  AND?: Prisma.zanrWhereInput | Prisma.zanrWhereInput[]
  OR?: Prisma.zanrWhereInput[]
  NOT?: Prisma.zanrWhereInput | Prisma.zanrWhereInput[]
  zanr_id?: Prisma.IntFilter<"zanr"> | number
  naziv_zanra?: Prisma.StringFilter<"zanr"> | string
  knjiga?: Prisma.KnjigaListRelationFilter
}

export type zanrOrderByWithRelationInput = {
  zanr_id?: Prisma.SortOrder
  naziv_zanra?: Prisma.SortOrder
  knjiga?: Prisma.knjigaOrderByRelationAggregateInput
  _relevance?: Prisma.zanrOrderByRelevanceInput
}

export type zanrWhereUniqueInput = Prisma.AtLeast<{
  zanr_id?: number
  naziv_zanra?: string
  AND?: Prisma.zanrWhereInput | Prisma.zanrWhereInput[]
  OR?: Prisma.zanrWhereInput[]
  NOT?: Prisma.zanrWhereInput | Prisma.zanrWhereInput[]
  knjiga?: Prisma.KnjigaListRelationFilter
}, "zanr_id" | "naziv_zanra">

export type zanrOrderByWithAggregationInput = {
  zanr_id?: Prisma.SortOrder
  naziv_zanra?: Prisma.SortOrder
  _count?: Prisma.zanrCountOrderByAggregateInput
  _avg?: Prisma.zanrAvgOrderByAggregateInput
  _max?: Prisma.zanrMaxOrderByAggregateInput
  _min?: Prisma.zanrMinOrderByAggregateInput
  _sum?: Prisma.zanrSumOrderByAggregateInput
}

export type zanrScalarWhereWithAggregatesInput = {
  AND?: Prisma.zanrScalarWhereWithAggregatesInput | Prisma.zanrScalarWhereWithAggregatesInput[]
  OR?: Prisma.zanrScalarWhereWithAggregatesInput[]
  NOT?: Prisma.zanrScalarWhereWithAggregatesInput | Prisma.zanrScalarWhereWithAggregatesInput[]
  zanr_id?: Prisma.IntWithAggregatesFilter<"zanr"> | number
  naziv_zanra?: Prisma.StringWithAggregatesFilter<"zanr"> | string
}

export type zanrCreateInput = {
  naziv_zanra: string
  knjiga?: Prisma.knjigaCreateNestedManyWithoutZanrInput
}

export type zanrUncheckedCreateInput = {
  zanr_id?: number
  naziv_zanra: string
  knjiga?: Prisma.knjigaUncheckedCreateNestedManyWithoutZanrInput
}

export type zanrUpdateInput = {
  naziv_zanra?: Prisma.StringFieldUpdateOperationsInput | string
  knjiga?: Prisma.knjigaUpdateManyWithoutZanrNestedInput
}

export type zanrUncheckedUpdateInput = {
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  naziv_zanra?: Prisma.StringFieldUpdateOperationsInput | string
  knjiga?: Prisma.knjigaUncheckedUpdateManyWithoutZanrNestedInput
}

export type zanrCreateManyInput = {
  zanr_id?: number
  naziv_zanra: string
}

export type zanrUpdateManyMutationInput = {
  naziv_zanra?: Prisma.StringFieldUpdateOperationsInput | string
}

export type zanrUncheckedUpdateManyInput = {
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  naziv_zanra?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ZanrScalarRelationFilter = {
  is?: Prisma.zanrWhereInput
  isNot?: Prisma.zanrWhereInput
}

export type zanrOrderByRelevanceInput = {
  fields: Prisma.zanrOrderByRelevanceFieldEnum | Prisma.zanrOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type zanrCountOrderByAggregateInput = {
  zanr_id?: Prisma.SortOrder
  naziv_zanra?: Prisma.SortOrder
}

export type zanrAvgOrderByAggregateInput = {
  zanr_id?: Prisma.SortOrder
}

export type zanrMaxOrderByAggregateInput = {
  zanr_id?: Prisma.SortOrder
  naziv_zanra?: Prisma.SortOrder
}

export type zanrMinOrderByAggregateInput = {
  zanr_id?: Prisma.SortOrder
  naziv_zanra?: Prisma.SortOrder
}

export type zanrSumOrderByAggregateInput = {
  zanr_id?: Prisma.SortOrder
}

export type zanrCreateNestedOneWithoutKnjigaInput = {
  create?: Prisma.XOR<Prisma.zanrCreateWithoutKnjigaInput, Prisma.zanrUncheckedCreateWithoutKnjigaInput>
  connectOrCreate?: Prisma.zanrCreateOrConnectWithoutKnjigaInput
  connect?: Prisma.zanrWhereUniqueInput
}

export type zanrUpdateOneRequiredWithoutKnjigaNestedInput = {
  create?: Prisma.XOR<Prisma.zanrCreateWithoutKnjigaInput, Prisma.zanrUncheckedCreateWithoutKnjigaInput>
  connectOrCreate?: Prisma.zanrCreateOrConnectWithoutKnjigaInput
  upsert?: Prisma.zanrUpsertWithoutKnjigaInput
  connect?: Prisma.zanrWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.zanrUpdateToOneWithWhereWithoutKnjigaInput, Prisma.zanrUpdateWithoutKnjigaInput>, Prisma.zanrUncheckedUpdateWithoutKnjigaInput>
}

export type zanrCreateWithoutKnjigaInput = {
  naziv_zanra: string
}

export type zanrUncheckedCreateWithoutKnjigaInput = {
  zanr_id?: number
  naziv_zanra: string
}

export type zanrCreateOrConnectWithoutKnjigaInput = {
  where: Prisma.zanrWhereUniqueInput
  create: Prisma.XOR<Prisma.zanrCreateWithoutKnjigaInput, Prisma.zanrUncheckedCreateWithoutKnjigaInput>
}

export type zanrUpsertWithoutKnjigaInput = {
  update: Prisma.XOR<Prisma.zanrUpdateWithoutKnjigaInput, Prisma.zanrUncheckedUpdateWithoutKnjigaInput>
  create: Prisma.XOR<Prisma.zanrCreateWithoutKnjigaInput, Prisma.zanrUncheckedCreateWithoutKnjigaInput>
  where?: Prisma.zanrWhereInput
}

export type zanrUpdateToOneWithWhereWithoutKnjigaInput = {
  where?: Prisma.zanrWhereInput
  data: Prisma.XOR<Prisma.zanrUpdateWithoutKnjigaInput, Prisma.zanrUncheckedUpdateWithoutKnjigaInput>
}

export type zanrUpdateWithoutKnjigaInput = {
  naziv_zanra?: Prisma.StringFieldUpdateOperationsInput | string
}

export type zanrUncheckedUpdateWithoutKnjigaInput = {
  zanr_id?: Prisma.IntFieldUpdateOperationsInput | number
  naziv_zanra?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ZanrCountOutputType
 */

export type ZanrCountOutputType = {
  knjiga: number
}

export type ZanrCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  knjiga?: boolean | ZanrCountOutputTypeCountKnjigaArgs
}

/**
 * ZanrCountOutputType without action
 */
export type ZanrCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZanrCountOutputType
   */
  select?: Prisma.ZanrCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ZanrCountOutputType without action
 */
export type ZanrCountOutputTypeCountKnjigaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.knjigaWhereInput
}


export type zanrSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  zanr_id?: boolean
  naziv_zanra?: boolean
  knjiga?: boolean | Prisma.zanr$knjigaArgs<ExtArgs>
  _count?: boolean | Prisma.ZanrCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["zanr"]>



export type zanrSelectScalar = {
  zanr_id?: boolean
  naziv_zanra?: boolean
}

export type zanrOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"zanr_id" | "naziv_zanra", ExtArgs["result"]["zanr"]>
export type zanrInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  knjiga?: boolean | Prisma.zanr$knjigaArgs<ExtArgs>
  _count?: boolean | Prisma.ZanrCountOutputTypeDefaultArgs<ExtArgs>
}

export type $zanrPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "zanr"
  objects: {
    knjiga: Prisma.$knjigaPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    zanr_id: number
    naziv_zanra: string
  }, ExtArgs["result"]["zanr"]>
  composites: {}
}

export type zanrGetPayload<S extends boolean | null | undefined | zanrDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$zanrPayload, S>

export type zanrCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<zanrFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ZanrCountAggregateInputType | true
  }

export interface zanrDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['zanr'], meta: { name: 'zanr' } }
  /**
   * Find zero or one Zanr that matches the filter.
   * @param {zanrFindUniqueArgs} args - Arguments to find a Zanr
   * @example
   * // Get one Zanr
   * const zanr = await prisma.zanr.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends zanrFindUniqueArgs>(args: Prisma.SelectSubset<T, zanrFindUniqueArgs<ExtArgs>>): Prisma.Prisma__zanrClient<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Zanr that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {zanrFindUniqueOrThrowArgs} args - Arguments to find a Zanr
   * @example
   * // Get one Zanr
   * const zanr = await prisma.zanr.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends zanrFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, zanrFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__zanrClient<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Zanr that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {zanrFindFirstArgs} args - Arguments to find a Zanr
   * @example
   * // Get one Zanr
   * const zanr = await prisma.zanr.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends zanrFindFirstArgs>(args?: Prisma.SelectSubset<T, zanrFindFirstArgs<ExtArgs>>): Prisma.Prisma__zanrClient<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Zanr that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {zanrFindFirstOrThrowArgs} args - Arguments to find a Zanr
   * @example
   * // Get one Zanr
   * const zanr = await prisma.zanr.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends zanrFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, zanrFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__zanrClient<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Zanrs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {zanrFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Zanrs
   * const zanrs = await prisma.zanr.findMany()
   * 
   * // Get first 10 Zanrs
   * const zanrs = await prisma.zanr.findMany({ take: 10 })
   * 
   * // Only select the `zanr_id`
   * const zanrWithZanr_idOnly = await prisma.zanr.findMany({ select: { zanr_id: true } })
   * 
   */
  findMany<T extends zanrFindManyArgs>(args?: Prisma.SelectSubset<T, zanrFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Zanr.
   * @param {zanrCreateArgs} args - Arguments to create a Zanr.
   * @example
   * // Create one Zanr
   * const Zanr = await prisma.zanr.create({
   *   data: {
   *     // ... data to create a Zanr
   *   }
   * })
   * 
   */
  create<T extends zanrCreateArgs>(args: Prisma.SelectSubset<T, zanrCreateArgs<ExtArgs>>): Prisma.Prisma__zanrClient<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Zanrs.
   * @param {zanrCreateManyArgs} args - Arguments to create many Zanrs.
   * @example
   * // Create many Zanrs
   * const zanr = await prisma.zanr.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends zanrCreateManyArgs>(args?: Prisma.SelectSubset<T, zanrCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Zanr.
   * @param {zanrDeleteArgs} args - Arguments to delete one Zanr.
   * @example
   * // Delete one Zanr
   * const Zanr = await prisma.zanr.delete({
   *   where: {
   *     // ... filter to delete one Zanr
   *   }
   * })
   * 
   */
  delete<T extends zanrDeleteArgs>(args: Prisma.SelectSubset<T, zanrDeleteArgs<ExtArgs>>): Prisma.Prisma__zanrClient<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Zanr.
   * @param {zanrUpdateArgs} args - Arguments to update one Zanr.
   * @example
   * // Update one Zanr
   * const zanr = await prisma.zanr.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends zanrUpdateArgs>(args: Prisma.SelectSubset<T, zanrUpdateArgs<ExtArgs>>): Prisma.Prisma__zanrClient<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Zanrs.
   * @param {zanrDeleteManyArgs} args - Arguments to filter Zanrs to delete.
   * @example
   * // Delete a few Zanrs
   * const { count } = await prisma.zanr.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends zanrDeleteManyArgs>(args?: Prisma.SelectSubset<T, zanrDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Zanrs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {zanrUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Zanrs
   * const zanr = await prisma.zanr.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends zanrUpdateManyArgs>(args: Prisma.SelectSubset<T, zanrUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Zanr.
   * @param {zanrUpsertArgs} args - Arguments to update or create a Zanr.
   * @example
   * // Update or create a Zanr
   * const zanr = await prisma.zanr.upsert({
   *   create: {
   *     // ... data to create a Zanr
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Zanr we want to update
   *   }
   * })
   */
  upsert<T extends zanrUpsertArgs>(args: Prisma.SelectSubset<T, zanrUpsertArgs<ExtArgs>>): Prisma.Prisma__zanrClient<runtime.Types.Result.GetResult<Prisma.$zanrPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Zanrs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {zanrCountArgs} args - Arguments to filter Zanrs to count.
   * @example
   * // Count the number of Zanrs
   * const count = await prisma.zanr.count({
   *   where: {
   *     // ... the filter for the Zanrs we want to count
   *   }
   * })
  **/
  count<T extends zanrCountArgs>(
    args?: Prisma.Subset<T, zanrCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ZanrCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Zanr.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ZanrAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ZanrAggregateArgs>(args: Prisma.Subset<T, ZanrAggregateArgs>): Prisma.PrismaPromise<GetZanrAggregateType<T>>

  /**
   * Group by Zanr.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {zanrGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends zanrGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: zanrGroupByArgs['orderBy'] }
      : { orderBy?: zanrGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, zanrGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetZanrGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the zanr model
 */
readonly fields: zanrFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for zanr.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__zanrClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  knjiga<T extends Prisma.zanr$knjigaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.zanr$knjigaArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$knjigaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the zanr model
 */
export interface zanrFieldRefs {
  readonly zanr_id: Prisma.FieldRef<"zanr", 'Int'>
  readonly naziv_zanra: Prisma.FieldRef<"zanr", 'String'>
}
    

// Custom InputTypes
/**
 * zanr findUnique
 */
export type zanrFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
  /**
   * Filter, which zanr to fetch.
   */
  where: Prisma.zanrWhereUniqueInput
}

/**
 * zanr findUniqueOrThrow
 */
export type zanrFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
  /**
   * Filter, which zanr to fetch.
   */
  where: Prisma.zanrWhereUniqueInput
}

/**
 * zanr findFirst
 */
export type zanrFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
  /**
   * Filter, which zanr to fetch.
   */
  where?: Prisma.zanrWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of zanrs to fetch.
   */
  orderBy?: Prisma.zanrOrderByWithRelationInput | Prisma.zanrOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for zanrs.
   */
  cursor?: Prisma.zanrWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` zanrs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` zanrs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of zanrs.
   */
  distinct?: Prisma.ZanrScalarFieldEnum | Prisma.ZanrScalarFieldEnum[]
}

/**
 * zanr findFirstOrThrow
 */
export type zanrFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
  /**
   * Filter, which zanr to fetch.
   */
  where?: Prisma.zanrWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of zanrs to fetch.
   */
  orderBy?: Prisma.zanrOrderByWithRelationInput | Prisma.zanrOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for zanrs.
   */
  cursor?: Prisma.zanrWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` zanrs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` zanrs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of zanrs.
   */
  distinct?: Prisma.ZanrScalarFieldEnum | Prisma.ZanrScalarFieldEnum[]
}

/**
 * zanr findMany
 */
export type zanrFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
  /**
   * Filter, which zanrs to fetch.
   */
  where?: Prisma.zanrWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of zanrs to fetch.
   */
  orderBy?: Prisma.zanrOrderByWithRelationInput | Prisma.zanrOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing zanrs.
   */
  cursor?: Prisma.zanrWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` zanrs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` zanrs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of zanrs.
   */
  distinct?: Prisma.ZanrScalarFieldEnum | Prisma.ZanrScalarFieldEnum[]
}

/**
 * zanr create
 */
export type zanrCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
  /**
   * The data needed to create a zanr.
   */
  data: Prisma.XOR<Prisma.zanrCreateInput, Prisma.zanrUncheckedCreateInput>
}

/**
 * zanr createMany
 */
export type zanrCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many zanrs.
   */
  data: Prisma.zanrCreateManyInput | Prisma.zanrCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * zanr update
 */
export type zanrUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
  /**
   * The data needed to update a zanr.
   */
  data: Prisma.XOR<Prisma.zanrUpdateInput, Prisma.zanrUncheckedUpdateInput>
  /**
   * Choose, which zanr to update.
   */
  where: Prisma.zanrWhereUniqueInput
}

/**
 * zanr updateMany
 */
export type zanrUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update zanrs.
   */
  data: Prisma.XOR<Prisma.zanrUpdateManyMutationInput, Prisma.zanrUncheckedUpdateManyInput>
  /**
   * Filter which zanrs to update
   */
  where?: Prisma.zanrWhereInput
  /**
   * Limit how many zanrs to update.
   */
  limit?: number
}

/**
 * zanr upsert
 */
export type zanrUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
  /**
   * The filter to search for the zanr to update in case it exists.
   */
  where: Prisma.zanrWhereUniqueInput
  /**
   * In case the zanr found by the `where` argument doesn't exist, create a new zanr with this data.
   */
  create: Prisma.XOR<Prisma.zanrCreateInput, Prisma.zanrUncheckedCreateInput>
  /**
   * In case the zanr was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.zanrUpdateInput, Prisma.zanrUncheckedUpdateInput>
}

/**
 * zanr delete
 */
export type zanrDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
  /**
   * Filter which zanr to delete.
   */
  where: Prisma.zanrWhereUniqueInput
}

/**
 * zanr deleteMany
 */
export type zanrDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which zanrs to delete
   */
  where?: Prisma.zanrWhereInput
  /**
   * Limit how many zanrs to delete.
   */
  limit?: number
}

/**
 * zanr.knjiga
 */
export type zanr$knjigaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the knjiga
   */
  select?: Prisma.knjigaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the knjiga
   */
  omit?: Prisma.knjigaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.knjigaInclude<ExtArgs> | null
  where?: Prisma.knjigaWhereInput
  orderBy?: Prisma.knjigaOrderByWithRelationInput | Prisma.knjigaOrderByWithRelationInput[]
  cursor?: Prisma.knjigaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KnjigaScalarFieldEnum | Prisma.KnjigaScalarFieldEnum[]
}

/**
 * zanr without action
 */
export type zanrDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the zanr
   */
  select?: Prisma.zanrSelect<ExtArgs> | null
  /**
   * Omit specific fields from the zanr
   */
  omit?: Prisma.zanrOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.zanrInclude<ExtArgs> | null
}
